//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STL.PL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class MainForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]


        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("STL.PL.MainForm", typeof(MainForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1148,Y=-56}.
        /// </summary>
        internal static System.Drawing.Point appUpdater1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("appUpdater1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon errorProvider1_Icon {
            get {
                object obj = ResourceManager.GetObject("errorProvider1.Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=834,Y=61}.
        /// </summary>
        internal static System.Drawing.Point errorProvider1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("errorProvider1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grpLogInCourts_BackgroundImage {
            get {
                object obj = ResourceManager.GetObject("grpLogInCourts.BackgroundImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap label5_Image {
            get {
                object obj = ResourceManager.GetObject("label5.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap label6_Image {
            get {
                object obj = ResourceManager.GetObject("label6.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=605,Y=295}.
        /// </summary>
        internal static System.Drawing.Point menuAbout_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuAbout.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=885,Y=100}.
        /// </summary>
        internal static System.Drawing.Point menuAccount_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuAccount.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1208,Y=61}.
        /// </summary>
        internal static System.Drawing.Point menuAccountDetails_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuAccountDetails.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1076,Y=22}.
        /// </summary>
        internal static System.Drawing.Point menuAccountRevise_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuAccountRevise.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=207,Y=529}.
        /// </summary>
        internal static System.Drawing.Point menuAccountStatus_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuAccountStatus.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1287,Y=412}.
        /// </summary>
        internal static System.Drawing.Point menuAcctNoCtrl_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuAcctNoCtrl.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=484,Y=22}.
        /// </summary>
        internal static System.Drawing.Point menuAddAcctCodes_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuAddAcctCodes.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=139}.
        /// </summary>
        internal static System.Drawing.Point menuAddBank_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuAddBank.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=175,Y=61}.
        /// </summary>
        internal static System.Drawing.Point menuAddCustCodes_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuAddCustCodes.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1091,Y=-95}.
        /// </summary>
        internal static System.Drawing.Point menuAllEODTasks_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuAllEODTasks.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=513,Y=61}.
        /// </summary>
        internal static System.Drawing.Point menuAuthoriseDelivery_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuAuthoriseDelivery.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=368,Y=529}.
        /// </summary>
        internal static System.Drawing.Point menuAuthoriseIC_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuAuthoriseIC.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=412}.
        /// </summary>
        internal static System.Drawing.Point menuBailiffReview_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuBailiffReview.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=858,Y=-56}.
        /// </summary>
        internal static System.Drawing.Point menuBehavioural_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuBehavioural.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=187,Y=334}.
        /// </summary>
        internal static System.Drawing.Point menuBERRep_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuBERRep.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1010,Y=139}.
        /// </summary>
        internal static System.Drawing.Point menuBranch_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuBranch.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=786,Y=451}.
        /// </summary>
        internal static System.Drawing.Point menuCalcBailCommission_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuCalcBailCommission.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=505,Y=217}.
        /// </summary>
        internal static System.Drawing.Point menuCancel_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuCancel.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=748,Y=-95}.
        /// </summary>
        internal static System.Drawing.Point menuCancelCollectionNotes_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuCancelCollectionNotes.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1217,Y=295}.
        /// </summary>
        internal static System.Drawing.Point menuCashAndGoReturn_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuCashAndGoReturn.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=399,Y=178}.
        /// </summary>
        internal static System.Drawing.Point menuCashier_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuCashier.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=554,Y=373}.
        /// </summary>
        internal static System.Drawing.Point menuCashierByBranch_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuCashierByBranch.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=244,Y=100}.
        /// </summary>
        internal static System.Drawing.Point menuCashLoanApplication_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuCashLoanApplication.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1100,Y=194}.
        /// </summary>
        internal static System.Drawing.Point menuCashLoanBankTransfer_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuCashLoanBankTransfer.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=184,Y=490}.
        /// </summary>
        internal static System.Drawing.Point menuChangeOrderDetails_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuChangeOrderDetails.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=560,Y=-17}.
        /// </summary>
        internal static System.Drawing.Point menuChangePassword_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuChangePassword.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=481,Y=139}.
        /// </summary>
        internal static System.Drawing.Point menuCodeMaintenance_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuCodeMaintenance.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1365,Y=-95}.
        /// </summary>
        internal static System.Drawing.Point menuCollections_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuCollections.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1131,Y=256}.
        /// </summary>
        internal static System.Drawing.Point menuCommand2_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuCommand2.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=282,Y=451}.
        /// </summary>
        internal static System.Drawing.Point menuCommand3_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuCommand3.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=529}.
        /// </summary>
        internal static System.Drawing.Point menuCommissionEnquiry_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuCommissionEnquiry.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=605,Y=451}.
        /// </summary>
        internal static System.Drawing.Point menuCommissionMaint_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuCommissionMaint.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1045,Y=373}.
        /// </summary>
        internal static System.Drawing.Point menuCommissionReport_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuCommissionReport.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1058,Y=490}.
        /// </summary>
        internal static System.Drawing.Point menuCommissionsSetUp_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuCommissionsSetUp.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=736,Y=-17}.
        /// </summary>
        internal static System.Drawing.Point menuConfig_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuConfig.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1021,Y=178}.
        /// </summary>
        internal static System.Drawing.Point menuCorrection_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuCorrection.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1021,Y=295}.
        /// </summary>
        internal static System.Drawing.Point menuCountryMaintenance_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuCountryMaintenance.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=366,Y=139}.
        /// </summary>
        internal static System.Drawing.Point menuCredit_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuCredit.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=647,Y=22}.
        /// </summary>
        internal static System.Drawing.Point menuCustomer_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuCustomer.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=707,Y=490}.
        /// </summary>
        internal static System.Drawing.Point menuCustomerMailing_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuCustomerMailing.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=441,Y=100}.
        /// </summary>
        internal static System.Drawing.Point menuCustomerSearch_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuCustomerSearch.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=163,Y=22}.
        /// </summary>
        internal static System.Drawing.Point menuCustomiseMenus_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuCustomiseMenus.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=176,Y=256}.
        /// </summary>
        internal static System.Drawing.Point menuDDMandate_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuDDMandate.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=474,Y=412}.
        /// </summary>
        internal static System.Drawing.Point menuDDPaymentExtra_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuDDPaymentExtra.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=648,Y=412}.
        /// </summary>
        internal static System.Drawing.Point menuDDRejection_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuDDRejection.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=678,Y=256}.
        /// </summary>
        internal static System.Drawing.Point menuDeliveryArea_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuDeliveryArea.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=432,Y=334}.
        /// </summary>
        internal static System.Drawing.Point menuDeposits_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuDeposits.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=342,Y=217}.
        /// </summary>
        internal static System.Drawing.Point menuDisbursements_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuDisbursements.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=499,Y=528}.
        /// </summary>
        internal static System.Drawing.Point menuDuplicateCustomers_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuDuplicateCustomers.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1008,Y=-17}.
        /// </summary>
        internal static System.Drawing.Point menuEmployeeMaintenance_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuEmployeeMaintenance.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=914,Y=295}.
        /// </summary>
        internal static System.Drawing.Point menuEOD_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuEOD.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=377,Y=490}.
        /// </summary>
        internal static System.Drawing.Point menuEODInterface_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuEODInterface.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=493,Y=295}.
        /// </summary>
        internal static System.Drawing.Point menuEPOS_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuEPOS.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=295}.
        /// </summary>
        internal static System.Drawing.Point menuExchangeRates_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuExchangeRates.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=214,Y=-17}.
        /// </summary>
        internal static System.Drawing.Point menuExit_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuExit.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=531,Y=490}.
        /// </summary>
        internal static System.Drawing.Point menuFactoringReports_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuFactoringReports.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=100}.
        /// </summary>
        internal static System.Drawing.Point menuFailedDeliveriesCollections_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuFailedDeliveriesCollections.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1107,Y=61}.
        /// </summary>
        internal static System.Drawing.Point menuFile_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuFile.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1163,Y=451}.
        /// </summary>
        internal static System.Drawing.Point menuFinTransQuery_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuFinTransQuery.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=942,Y=22}.
        /// </summary>
        internal static System.Drawing.Point menuFollowUp_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuFollowUp.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=624,Y=217}.
        /// </summary>
        internal static System.Drawing.Point menuGeneralTransactions_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuGeneralTransactions.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1144,Y=100}.
        /// </summary>
        internal static System.Drawing.Point menuGoodsReturn_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuGoodsReturn.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImageListStreamer.
        /// </summary>
        internal static System.Windows.Forms.ImageListStreamer menuIcons_ImageStream {
            get {
                object obj = ResourceManager.GetObject("menuIcons.ImageStream", resourceCulture);
                return ((System.Windows.Forms.ImageListStreamer)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=613,Y=100}.
        /// </summary>
        internal static System.Drawing.Point menuIcons_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuIcons.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=210,Y=178}.
        /// </summary>
        internal static System.Drawing.Point menuImageManagement_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuImageManagement.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1214,Y=-17}.
        /// </summary>
        internal static System.Drawing.Point menuIncomplete_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuIncomplete.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1246,Y=490}.
        /// </summary>
        internal static System.Drawing.Point menuInstantReplacement_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuInstantReplacement.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=547,Y=-56}.
        /// </summary>
        internal static System.Drawing.Point menuInstBookingPrint_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuInstBookingPrint.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=180,Y=-56}.
        /// </summary>
        internal static System.Drawing.Point menuInstManagement_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuInstManagement.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=490}.
        /// </summary>
        internal static System.Drawing.Point menuInterfaceReport_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuInterfaceReport.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=899,Y=178}.
        /// </summary>
        internal static System.Drawing.Point menuJournal_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuJournal.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=192,Y=217}.
        /// </summary>
        internal static System.Drawing.Point menuLetterMerge_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuLetterMerge.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=534,Y=256}.
        /// </summary>
        internal static System.Drawing.Point menuLocateHelp_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuLocateHelp.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1116,Y=217}.
        /// </summary>
        internal static System.Drawing.Point menuLocationEnquiry_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuLocationEnquiry.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=316,Y=-17}.
        /// </summary>
        internal static System.Drawing.Point menuLogOff_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuLogOff.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=692,Y=61}.
        /// </summary>
        internal static System.Drawing.Point menuMandatory_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuMandatory.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=22}.
        /// </summary>
        internal static System.Drawing.Point menuManualSale_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuManualSale.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=770,Y=340}.
        /// </summary>
        internal static System.Drawing.Point menuMmiMatrix_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuMmiMatrix_TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=428,Y=451}.
        /// </summary>
        internal static System.Drawing.Point menuMonitorBookings_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuMonitorBookings.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1238,Y=22}.
        /// </summary>
        internal static System.Drawing.Point menuNewAccount_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuNewAccount.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=782,Y=22}.
        /// </summary>
        internal static System.Drawing.Point menuNewCustomer_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuNewCustomer.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=979,Y=412}.
        /// </summary>
        internal static System.Drawing.Point menuNonStock_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuNonStock.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1067,Y=334}.
        /// </summary>
        internal static System.Drawing.Point menuNumberGeneration_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuNumberGeneration.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=149,Y=139}.
        /// </summary>
        internal static System.Drawing.Point menuOneForOneReplacement_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuOneForOneReplacement.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1100,Y=211}.
        /// </summary>
        internal static System.Drawing.Point menuOnlineProductSearch_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuOnlineProductSearch.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=724,Y=100}.
        /// </summary>
        internal static System.Drawing.Point menuPaidAndTaken_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuPaidAndTaken.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1298,Y=100}.
        /// </summary>
        internal static System.Drawing.Point menuPayment_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuPayment.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=883,Y=490}.
        /// </summary>
        internal static System.Drawing.Point menuPaymentFileDefn_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuPaymentFileDefn.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=355,Y=-56}.
        /// </summary>
        internal static System.Drawing.Point menuPendingInstallations_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuPendingInstallations.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=256}.
        /// </summary>
        internal static System.Drawing.Point menuPrizeVouchers_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuPrizeVouchers.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1286,Y=217}.
        /// </summary>
        internal static System.Drawing.Point menuProductEnquiry_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuProductEnquiry.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=720,Y=-56}.
        /// </summary>
        internal static System.Drawing.Point menuProvisions_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuProvisions.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=798,Y=412}.
        /// </summary>
        internal static System.Drawing.Point menuRebateCalculation_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuRebateCalculation.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=451}.
        /// </summary>
        internal static System.Drawing.Point menuRebateReport_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuRebateReport.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=959,Y=256}.
        /// </summary>
        internal static System.Drawing.Point menuRedeliverReposs_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuRedeliverReposs.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=168,Y=412}.
        /// </summary>
        internal static System.Drawing.Point menuReports_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuReports.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=522,Y=178}.
        /// </summary>
        internal static System.Drawing.Point menuReprintActionSheet_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuReprintActionSheet.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=978,Y=451}.
        /// </summary>
        internal static System.Drawing.Point menuReprintBailCommn_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuReprintBailCommn.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1161,Y=178}.
        /// </summary>
        internal static System.Drawing.Point menuReturnCheque_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuReturnCheque.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=249,Y=373}.
        /// </summary>
        internal static System.Drawing.Point menuReverseCancel_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuReverseCancel.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=875,Y=522}.
        /// </summary>
        internal static System.Drawing.Point menuSalesCommBranchEnquiry_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuSalesCommBranchEnquiry.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=695,Y=525}.
        /// </summary>
        internal static System.Drawing.Point menuSalesCommEnquiry_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuSalesCommEnquiry.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1241,Y=-95}.
        /// </summary>
        internal static System.Drawing.Point menuScoring_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuScoring.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=61}.
        /// </summary>
        internal static System.Drawing.Point menuScoringMatrix_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuScoringMatrix.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=855,Y=-17}.
        /// </summary>
        internal static System.Drawing.Point menuScoringRules_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuScoringRules.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap menuScreenTranslation_Image {
            get {
                object obj = ResourceManager.GetObject("menuScreenTranslation.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=831,Y=139}.
        /// </summary>
        internal static System.Drawing.Point menuScreenTranslation_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuScreenTranslation.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1130,Y=139}.
        /// </summary>
        internal static System.Drawing.Point menuSearchCashAndGo_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuSearchCashAndGo.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=181,Y=295}.
        /// </summary>
        internal static System.Drawing.Point menuSellGiftVoucher_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuSellGiftVoucher.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=311,Y=334}.
        /// </summary>
        internal static System.Drawing.Point menuService_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuService.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=373}.
        /// </summary>
        internal static System.Drawing.Point menuServiceCustomerInteraction_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuServiceCustomerInteraction.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=175,Y=451}.
        /// </summary>
        internal static System.Drawing.Point menuSMS_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuSMS.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1004,Y=-56}.
        /// </summary>
        internal static System.Drawing.Point menuStatements_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuStatements.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=348,Y=295}.
        /// </summary>
        internal static System.Drawing.Point menuStatusCode_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuStatusCode.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=721,Y=295}.
        /// </summary>
        internal static System.Drawing.Point menuStoreCardBatchPrint_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuStoreCardBatchPrint.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=178}.
        /// </summary>
        internal static System.Drawing.Point menuStoreCardRateSetup_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuStoreCardRateSetup.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=562,Y=334}.
        /// </summary>
        internal static System.Drawing.Point menuStrategyConfiguration_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuStrategyConfiguration.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=293,Y=412}.
        /// </summary>
        internal static System.Drawing.Point menuSumryUpdControl_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuSumryUpdControl.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1012,Y=100}.
        /// </summary>
        internal static System.Drawing.Point menuSysMaint_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuSysMaint.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=663,Y=139}.
        /// </summary>
        internal static System.Drawing.Point menuTallymanExtract_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuTallymanExtract.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=338,Y=61}.
        /// </summary>
        internal static System.Drawing.Point menuTelephoneAction_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuTelephoneAction.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1231,Y=373}.
        /// </summary>
        internal static System.Drawing.Point menuTempReceiptInvest_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuTempReceiptInvest.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=765,Y=334}.
        /// </summary>
        internal static System.Drawing.Point menuTermsType_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuTermsType.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=954,Y=-95}.
        /// </summary>
        internal static System.Drawing.Point menuTestMode_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuTestMode.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=339,Y=22}.
        /// </summary>
        internal static System.Drawing.Point menuTransaction_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuTransaction.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=710,Y=178}.
        /// </summary>
        internal static System.Drawing.Point menuTransferTransaction_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuTransferTransaction.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=964,Y=61}.
        /// </summary>
        internal static System.Drawing.Point menuTranslation_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuTranslation.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=325,Y=256}.
        /// </summary>
        internal static System.Drawing.Point menuTransTypeMaintenance_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuTransTypeMaintenance.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=829,Y=256}.
        /// </summary>
        internal static System.Drawing.Point menuTTMatrix_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuTTMatrix.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1115,Y=412}.
        /// </summary>
        internal static System.Drawing.Point menuUnpaidAccounts_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuUnpaidAccounts.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=334}.
        /// </summary>
        internal static System.Drawing.Point menuUpdateDateDue_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuUpdateDateDue.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=436,Y=-17}.
        /// </summary>
        internal static System.Drawing.Point menuVersion_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuVersion.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=-56}.
        /// </summary>
        internal static System.Drawing.Point menuViewStoreCard_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuViewStoreCard.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=410,Y=373}.
        /// </summary>
        internal static System.Drawing.Point menuWarehouse_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuWarehouse.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=862,Y=373}.
        /// </summary>
        internal static System.Drawing.Point menuWarrantyRenewals_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuWarrantyRenewals.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=947,Y=217}.
        /// </summary>
        internal static System.Drawing.Point menuWarrantyReport_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuWarrantyReport.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=1277,Y=256}.
        /// </summary>
        internal static System.Drawing.Point menuWOReview_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuWOReview.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=727,Y=373}.
        /// </summary>
        internal static System.Drawing.Point menuWorkLists_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuWorkLists.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=217}.
        /// </summary>
        internal static System.Drawing.Point menuZoneAutomation_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuZoneAutomation.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pbDownloading_Image {
            get {
                object obj = ResourceManager.GetObject("pbDownloading.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pbSplash_Image {
            get {
                object obj = ResourceManager.GetObject("pbSplash.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=316}.
        /// </summary>
        internal static System.Drawing.Point RePrintInvoice_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("RePrintInvoice.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=817,Y=217}.
        /// </summary>
        internal static System.Drawing.Point sqlCommand1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("sqlCommand1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
    }
}
