using System;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;
using System.Threading;

namespace STL.PL
{
	/// <summary>
	/// Popup prompt to request a manual account number to be entered. A list
	/// of new account numbers is always kept in reserve so that sales can
	/// continue in the event of a system failure. These accounts are subsequently
	/// entered into the system from a paper copy. In this case the reserved
	/// account numbers must be manually entered instead of being automatically
	/// generated by the new sales order screen.
	/// </summary>
	public class ManualAccountNo : System.Windows.Forms.Form
	{
		public STL.PL.AccountTextBox txtAccountNumber;
		private System.Windows.Forms.Label label1;
		private System.Windows.Forms.Button button1;
		/// <summary>
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.Container components = null;

		public ManualAccountNo(TranslationDummy d)
		{
			InitializeComponent();
		}
		public ManualAccountNo()
		{
			//
			// Required for Windows Form Designer support
			//
			InitializeComponent();

		}

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		protected override void Dispose( bool disposing )
		{
			if( disposing )
			{
				if(components != null)
				{
					components.Dispose();
				}
			}
			base.Dispose( disposing );
		}

		#region Windows Form Designer generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
			this.txtAccountNumber = new STL.PL.AccountTextBox();
			this.label1 = new System.Windows.Forms.Label();
			this.button1 = new System.Windows.Forms.Button();
			this.SuspendLayout();
			// 
			// txtAccountNumber
			// 
			this.txtAccountNumber.Location = new System.Drawing.Point(104, 48);
			this.txtAccountNumber.Name = "txtAccountNumber";
			this.txtAccountNumber.Size = new System.Drawing.Size(88, 20);
			this.txtAccountNumber.TabIndex = 1;
			this.txtAccountNumber.Text = "000-0000-0000-0";
			// 
			// label1
			// 
			this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((System.Byte)(0)));
			this.label1.Location = new System.Drawing.Point(16, 16);
			this.label1.Name = "label1";
			this.label1.Size = new System.Drawing.Size(192, 16);
			this.label1.TabIndex = 4;
			this.label1.Text = "Enter Manual RF Account Number:";
			// 
			// button1
			// 
			this.button1.Location = new System.Drawing.Point(112, 96);
			this.button1.Name = "button1";
			this.button1.TabIndex = 5;
			this.button1.Text = "Submit";
			this.button1.Click += new System.EventHandler(this.button1_Click);
			// 
			// ManualAccountNo
			// 
			this.AutoScaleBaseSize = new System.Drawing.Size(5, 13);
			this.ClientSize = new System.Drawing.Size(292, 133);
			this.Controls.AddRange(new System.Windows.Forms.Control[] {
																		  this.button1,
																		  this.label1,
																		  this.txtAccountNumber});
			this.Name = "ManualAccountNo";
			this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "ManualAccountNo";
			this.ResumeLayout(false);

		}
		#endregion

		private void button1_Click(object sender, System.EventArgs e)
		{
			this.Close();
		}

	}
}
