//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.239.
// 
#pragma warning disable 1591

namespace STL.PL.WSPrinting
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "WPrintingSoap", Namespace = "http://strategicthought.com/webservices/")]
    public partial class WPrinting : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private Authentication authenticationValueField;

        private System.Threading.SendOrPostCallback GetFileInfoOperationCompleted;

        private System.Threading.SendOrPostCallback DownloadFileOperationCompleted;

        private System.Threading.SendOrPostCallback GetAgreeementPrintOperationCompleted;

        private System.Threading.SendOrPostCallback GetDNPrintInfoOperationCompleted;

        private System.Threading.SendOrPostCallback GetDNPrintScheduleItemsOperationCompleted;

        private System.Threading.SendOrPostCallback GetDecimalPlacesOperationCompleted;

        private System.Threading.SendOrPostCallback HostNameOperationCompleted;

        private System.Threading.SendOrPostCallback GetASPrintInfoOperationCompleted;

        private bool useDefaultCredentialsSetExplicitly;

        /// <remarks/>
        public WPrinting()
        {
            this.Url = global::STL.PL.Properties.Settings.Default.Courts_NET_PL_WSPrinting_WPrinting;
            if ((this.IsLocalFileSystemWebService(this.Url) == true))
            {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else
            {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        public Authentication AuthenticationValue
        {
            get
            {
                return this.authenticationValueField;
            }
            set
            {
                this.authenticationValueField = value;
            }
        }

        public new string Url
        {
            get
            {
                return base.Url;
            }
            set
            {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true)
                            && (this.useDefaultCredentialsSetExplicitly == false))
                            && (this.IsLocalFileSystemWebService(value) == false)))
                {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }

        public new bool UseDefaultCredentials
        {
            get
            {
                return base.UseDefaultCredentials;
            }
            set
            {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        /// <remarks/>
        public event GetFileInfoCompletedEventHandler GetFileInfoCompleted;

        /// <remarks/>
        public event DownloadFileCompletedEventHandler DownloadFileCompleted;

        /// <remarks/>
        public event GetAgreeementPrintCompletedEventHandler GetAgreeementPrintCompleted;

        /// <remarks/>
        public event GetDNPrintInfoCompletedEventHandler GetDNPrintInfoCompleted;

        /// <remarks/>
        public event GetDNPrintScheduleItemsCompletedEventHandler GetDNPrintScheduleItemsCompleted;

        /// <remarks/>
        public event GetDecimalPlacesCompletedEventHandler GetDecimalPlacesCompleted;

        /// <remarks/>
        public event HostNameCompletedEventHandler HostNameCompleted;

        /// <remarks/>
        public event GetASPrintInfoCompletedEventHandler GetASPrintInfoCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://strategicthought.com/webservices/GetFileInfo", RequestNamespace = "http://strategicthought.com/webservices/", ResponseNamespace = "http://strategicthought.com/webservices/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetFileInfo(ref System.DateTime modified, ref double size, ref string path, string filename, string countrycode)
        {
            object[] results = this.Invoke("GetFileInfo", new object[] {
                        modified,
                        size,
                        path,
                        filename,
                        countrycode});
            modified = ((System.DateTime)(results[0]));
            size = ((double)(results[1]));
            path = ((string)(results[2]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetFileInfo(System.DateTime modified, double size, string path, string filename, string countrycode, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetFileInfo", new object[] {
                        modified,
                        size,
                        path,
                        filename,
                        countrycode}, callback, asyncState);
        }

        /// <remarks/>
        public void EndGetFileInfo(System.IAsyncResult asyncResult, out System.DateTime modified, out double size, out string path)
        {
            object[] results = this.EndInvoke(asyncResult);
            modified = ((System.DateTime)(results[0]));
            size = ((double)(results[1]));
            path = ((string)(results[2]));
        }

        /// <remarks/>
        public void GetFileInfoAsync(System.DateTime modified, double size, string path, string filename, string countrycode)
        {
            this.GetFileInfoAsync(modified, size, path, filename, countrycode, null);
        }

        /// <remarks/>
        public void GetFileInfoAsync(System.DateTime modified, double size, string path, string filename, string countrycode, object userState)
        {
            if ((this.GetFileInfoOperationCompleted == null))
            {
                this.GetFileInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFileInfoOperationCompleted);
            }
            this.InvokeAsync("GetFileInfo", new object[] {
                        modified,
                        size,
                        path,
                        filename,
                        countrycode}, this.GetFileInfoOperationCompleted, userState);
        }

        private void OnGetFileInfoOperationCompleted(object arg)
        {
            if ((this.GetFileInfoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFileInfoCompleted(this, new GetFileInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://strategicthought.com/webservices/DownloadFile", RequestNamespace = "http://strategicthought.com/webservices/", ResponseNamespace = "http://strategicthought.com/webservices/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
        public byte[] DownloadFile(string path)
        {
            object[] results = this.Invoke("DownloadFile", new object[] {
                        path});
            return ((byte[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginDownloadFile(string path, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("DownloadFile", new object[] {
                        path}, callback, asyncState);
        }

        /// <remarks/>
        public byte[] EndDownloadFile(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((byte[])(results[0]));
        }

        /// <remarks/>
        public void DownloadFileAsync(string path)
        {
            this.DownloadFileAsync(path, null);
        }

        /// <remarks/>
        public void DownloadFileAsync(string path, object userState)
        {
            if ((this.DownloadFileOperationCompleted == null))
            {
                this.DownloadFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownloadFileOperationCompleted);
            }
            this.InvokeAsync("DownloadFile", new object[] {
                        path}, this.DownloadFileOperationCompleted, userState);
        }

        private void OnDownloadFileOperationCompleted(object arg)
        {
            if ((this.DownloadFileCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownloadFileCompleted(this, new DownloadFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://strategicthought.com/webservices/GetAgreeementPrint", RequestNamespace = "http://strategicthought.com/webservices/", ResponseNamespace = "http://strategicthought.com/webservices/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public STL.Common.PrintingAgreementResult GetAgreeementPrint(STL.Common.PrintingAgreementRequest input)
        {
            object[] results = this.Invoke("GetAgreeementPrint", new object[] {
                        input});
            return ((STL.Common.PrintingAgreementResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetAgreeementPrint(STL.Common.PrintingAgreementRequest input, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetAgreeementPrint", new object[] {
                        input}, callback, asyncState);
        }

        /// <remarks/>
        public STL.Common.PrintingAgreementResult EndGetAgreeementPrint(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((STL.Common.PrintingAgreementResult)(results[0]));
        }

        /// <remarks/>
        public void GetAgreeementPrintAsync(STL.Common.PrintingAgreementRequest input)
        {
            this.GetAgreeementPrintAsync(input, null);
        }

        /// <remarks/>
        public void GetAgreeementPrintAsync(STL.Common.PrintingAgreementRequest input, object userState)
        {
            if ((this.GetAgreeementPrintOperationCompleted == null))
            {
                this.GetAgreeementPrintOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAgreeementPrintOperationCompleted);
            }
            this.InvokeAsync("GetAgreeementPrint", new object[] {
                        input}, this.GetAgreeementPrintOperationCompleted, userState);
        }

        private void OnGetAgreeementPrintOperationCompleted(object arg)
        {
            if ((this.GetAgreeementPrintCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAgreeementPrintCompleted(this, new GetAgreeementPrintCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://strategicthought.com/webservices/GetDNPrintInfo", RequestNamespace = "http://strategicthought.com/webservices/", ResponseNamespace = "http://strategicthought.com/webservices/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public STL.Common.PrintingDN[] GetDNPrintInfo([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)] STL.Common.DNparameters[] input)
        {
            object[] results = this.Invoke("GetDNPrintInfo", new object[] {
                        input});
            return ((STL.Common.PrintingDN[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetDNPrintInfo(STL.Common.DNparameters[] input, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetDNPrintInfo", new object[] {
                        input}, callback, asyncState);
        }

        /// <remarks/>
        public STL.Common.PrintingDN[] EndGetDNPrintInfo(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((STL.Common.PrintingDN[])(results[0]));
        }

        /// <remarks/>
        public void GetDNPrintInfoAsync(STL.Common.DNparameters[] input)
        {
            this.GetDNPrintInfoAsync(input, null);
        }

        /// <remarks/>
        public void GetDNPrintInfoAsync(STL.Common.DNparameters[] input, object userState)
        {
            if ((this.GetDNPrintInfoOperationCompleted == null))
            {
                this.GetDNPrintInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDNPrintInfoOperationCompleted);
            }
            this.InvokeAsync("GetDNPrintInfo", new object[] {
                        input}, this.GetDNPrintInfoOperationCompleted, userState);
        }

        private void OnGetDNPrintInfoOperationCompleted(object arg)
        {
            if ((this.GetDNPrintInfoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDNPrintInfoCompleted(this, new GetDNPrintInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://strategicthought.com/webservices/GetDNPrintScheduleItems", RequestNamespace = "http://strategicthought.com/webservices/", ResponseNamespace = "http://strategicthought.com/webservices/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public STL.Common.PrintingDN[] GetDNPrintScheduleItems(short loadNo, short branchNo, System.DateTime dateDel, int user)
        {
            object[] results = this.Invoke("GetDNPrintScheduleItems", new object[] {
                        loadNo,
                        branchNo,
                        dateDel,
                        user});
            return ((STL.Common.PrintingDN[])(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetDNPrintScheduleItems(short loadNo, short branchNo, System.DateTime dateDel, int user, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetDNPrintScheduleItems", new object[] {
                        loadNo,
                        branchNo,
                        dateDel,
                        user}, callback, asyncState);
        }

        /// <remarks/>
        public STL.Common.PrintingDN[] EndGetDNPrintScheduleItems(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((STL.Common.PrintingDN[])(results[0]));
        }

        /// <remarks/>
        public void GetDNPrintScheduleItemsAsync(short loadNo, short branchNo, System.DateTime dateDel, int user)
        {
            this.GetDNPrintScheduleItemsAsync(loadNo, branchNo, dateDel, user, null);
        }

        /// <remarks/>
        public void GetDNPrintScheduleItemsAsync(short loadNo, short branchNo, System.DateTime dateDel, int user, object userState)
        {
            if ((this.GetDNPrintScheduleItemsOperationCompleted == null))
            {
                this.GetDNPrintScheduleItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDNPrintScheduleItemsOperationCompleted);
            }
            this.InvokeAsync("GetDNPrintScheduleItems", new object[] {
                        loadNo,
                        branchNo,
                        dateDel,
                        user}, this.GetDNPrintScheduleItemsOperationCompleted, userState);
        }

        private void OnGetDNPrintScheduleItemsOperationCompleted(object arg)
        {
            if ((this.GetDNPrintScheduleItemsCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDNPrintScheduleItemsCompleted(this, new GetDNPrintScheduleItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://strategicthought.com/webservices/GetDecimalPlaces", RequestNamespace = "http://strategicthought.com/webservices/", ResponseNamespace = "http://strategicthought.com/webservices/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDecimalPlaces()
        {
            object[] results = this.Invoke("GetDecimalPlaces", new object[0]);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetDecimalPlaces(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetDecimalPlaces", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public string EndGetDecimalPlaces(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void GetDecimalPlacesAsync()
        {
            this.GetDecimalPlacesAsync(null);
        }

        /// <remarks/>
        public void GetDecimalPlacesAsync(object userState)
        {
            if ((this.GetDecimalPlacesOperationCompleted == null))
            {
                this.GetDecimalPlacesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDecimalPlacesOperationCompleted);
            }
            this.InvokeAsync("GetDecimalPlaces", new object[0], this.GetDecimalPlacesOperationCompleted, userState);
        }

        private void OnGetDecimalPlacesOperationCompleted(object arg)
        {
            if ((this.GetDecimalPlacesCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDecimalPlacesCompleted(this, new GetDecimalPlacesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://strategicthought.com/webservices/HostName", RequestNamespace = "http://strategicthought.com/webservices/", ResponseNamespace = "http://strategicthought.com/webservices/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HostName()
        {
            object[] results = this.Invoke("HostName", new object[0]);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginHostName(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("HostName", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public string EndHostName(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void HostNameAsync()
        {
            this.HostNameAsync(null);
        }

        /// <remarks/>
        public void HostNameAsync(object userState)
        {
            if ((this.HostNameOperationCompleted == null))
            {
                this.HostNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHostNameOperationCompleted);
            }
            this.InvokeAsync("HostName", new object[0], this.HostNameOperationCompleted, userState);
        }

        private void OnHostNameOperationCompleted(object arg)
        {
            if ((this.HostNameCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HostNameCompleted(this, new HostNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://strategicthought.com/webservices/GetASPrintInfo", RequestNamespace = "http://strategicthought.com/webservices/", ResponseNamespace = "http://strategicthought.com/webservices/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public STL.Common.PrintingAction GetASPrintInfo(string acctno, int empeeno)
        {
            object[] results = this.Invoke("GetASPrintInfo", new object[] {
                        acctno,
                        empeeno});
            return ((STL.Common.PrintingAction)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetASPrintInfo(string acctno, int empeeno, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetASPrintInfo", new object[] {
                        acctno,
                        empeeno}, callback, asyncState);
        }

        /// <remarks/>
        public STL.Common.PrintingAction EndGetASPrintInfo(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((STL.Common.PrintingAction)(results[0]));
        }

        /// <remarks/>
        public void GetASPrintInfoAsync(string acctno, int empeeno)
        {
            this.GetASPrintInfoAsync(acctno, empeeno, null);
        }

        /// <remarks/>
        public void GetASPrintInfoAsync(string acctno, int empeeno, object userState)
        {
            if ((this.GetASPrintInfoOperationCompleted == null))
            {
                this.GetASPrintInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetASPrintInfoOperationCompleted);
            }
            this.InvokeAsync("GetASPrintInfo", new object[] {
                        acctno,
                        empeeno}, this.GetASPrintInfoOperationCompleted, userState);
        }

        private void OnGetASPrintInfoOperationCompleted(object arg)
        {
            if ((this.GetASPrintInfoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetASPrintInfoCompleted(this, new GetASPrintInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }

        private bool IsLocalFileSystemWebService(string url)
        {
            if (((url == null)
                        || (url == string.Empty)))
            {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024)
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0)))
            {
                return true;
            }
            return false;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://strategicthought.com/webservices/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://strategicthought.com/webservices/", IsNullable = false)]
    public partial class Authentication : System.Web.Services.Protocols.SoapHeader
    {

        private string userField;

        private int userIdField;

        private string cookieField;

        private string passwordField;

        private string cultureField;

        private string countryField;

        private string versionField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        public string User
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }

        /// <remarks/>
        public int UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        public string Cookie
        {
            get
            {
                return this.cookieField;
            }
            set
            {
                this.cookieField = value;
            }
        }

        /// <remarks/>
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        public string Culture
        {
            get
            {
                return this.cultureField;
            }
            set
            {
                this.cultureField = value;
            }
        }

        /// <remarks/>
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    ///// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://strategicthought.com/webservices/")]
    //public partial class STL.Common.PrintingAction {

    //    private System.Data.DataSet actionSetField;

    //    private string aliasField;

    //    private decimal paymentAmountField;

    //    private decimal arrearsField;

    //    private decimal bailiffFeeField;

    //    private decimal collectionFeeField;

    //    private string custIDField;

    //    private string acctnoField;

    //    private string currstatusField;

    //    private System.DateTime dateLastPaidField;

    //    private System.DateTime deadLineDateField;

    //    private int dayField;

    //    private string firstnameField;

    //    private decimal instAmountField;

    //    private string nameField;

    //    private decimal outstbalField;

    //    private string photoField;

    //    private int privilegeCountField;

    //    private int segmentIdField;

    //    private string signatureFileField;

    //    private string titleField;

    //    private int userField;

    //    /// <remarks/>
    //    public System.Data.DataSet ActionSet {
    //        get {
    //            return this.actionSetField;
    //        }
    //        set {
    //            this.actionSetField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string Alias {
    //        get {
    //            return this.aliasField;
    //        }
    //        set {
    //            this.aliasField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public decimal paymentAmount {
    //        get {
    //            return this.paymentAmountField;
    //        }
    //        set {
    //            this.paymentAmountField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public decimal Arrears {
    //        get {
    //            return this.arrearsField;
    //        }
    //        set {
    //            this.arrearsField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public decimal bailiffFee {
    //        get {
    //            return this.bailiffFeeField;
    //        }
    //        set {
    //            this.bailiffFeeField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public decimal collectionFee {
    //        get {
    //            return this.collectionFeeField;
    //        }
    //        set {
    //            this.collectionFeeField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string custID {
    //        get {
    //            return this.custIDField;
    //        }
    //        set {
    //            this.custIDField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string Acctno {
    //        get {
    //            return this.acctnoField;
    //        }
    //        set {
    //            this.acctnoField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string Currstatus {
    //        get {
    //            return this.currstatusField;
    //        }
    //        set {
    //            this.currstatusField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public System.DateTime DateLastPaid {
    //        get {
    //            return this.dateLastPaidField;
    //        }
    //        set {
    //            this.dateLastPaidField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public System.DateTime DeadLineDate {
    //        get {
    //            return this.deadLineDateField;
    //        }
    //        set {
    //            this.deadLineDateField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public int day {
    //        get {
    //            return this.dayField;
    //        }
    //        set {
    //            this.dayField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string Firstname {
    //        get {
    //            return this.firstnameField;
    //        }
    //        set {
    //            this.firstnameField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public decimal instAmount {
    //        get {
    //            return this.instAmountField;
    //        }
    //        set {
    //            this.instAmountField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string Name {
    //        get {
    //            return this.nameField;
    //        }
    //        set {
    //            this.nameField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public decimal Outstbal {
    //        get {
    //            return this.outstbalField;
    //        }
    //        set {
    //            this.outstbalField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string Photo {
    //        get {
    //            return this.photoField;
    //        }
    //        set {
    //            this.photoField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public int privilegeCount {
    //        get {
    //            return this.privilegeCountField;
    //        }
    //        set {
    //            this.privilegeCountField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public int segmentId {
    //        get {
    //            return this.segmentIdField;
    //        }
    //        set {
    //            this.segmentIdField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string SignatureFile {
    //        get {
    //            return this.signatureFileField;
    //        }
    //        set {
    //            this.signatureFileField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string Title {
    //        get {
    //            return this.titleField;
    //        }
    //        set {
    //            this.titleField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public int user {
    //        get {
    //            return this.userField;
    //        }
    //        set {
    //            this.userField = value;
    //        }
    //    }
    //}

    ///// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://strategicthought.com/webservices/")]
    //public partial class PrintingDN {

    //    private System.Data.DataSet customerField;

    //    private string empnameField;

    //    private string printedbyField;

    //    private decimal amountPayableField;

    //    private decimal chargesField;

    //    private bool codField;

    //    private string acctnoField;

    //    private string printTextField;

    //    private string aliasField;

    //    private string customernameField;

    //    private bool delnotenumField;

    //    private string locnField;

    //    private string buffnoField;

    //    private int userField;

    //    private string origbuffbranchnoField;

    //    /// <remarks/>
    //    public System.Data.DataSet Customer {
    //        get {
    //            return this.customerField;
    //        }
    //        set {
    //            this.customerField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string empname {
    //        get {
    //            return this.empnameField;
    //        }
    //        set {
    //            this.empnameField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string printedby {
    //        get {
    //            return this.printedbyField;
    //        }
    //        set {
    //            this.printedbyField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public decimal amountPayable {
    //        get {
    //            return this.amountPayableField;
    //        }
    //        set {
    //            this.amountPayableField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public decimal charges {
    //        get {
    //            return this.chargesField;
    //        }
    //        set {
    //            this.chargesField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public bool cod {
    //        get {
    //            return this.codField;
    //        }
    //        set {
    //            this.codField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string acctno {
    //        get {
    //            return this.acctnoField;
    //        }
    //        set {
    //            this.acctnoField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string printText {
    //        get {
    //            return this.printTextField;
    //        }
    //        set {
    //            this.printTextField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string alias {
    //        get {
    //            return this.aliasField;
    //        }
    //        set {
    //            this.aliasField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string customername {
    //        get {
    //            return this.customernameField;
    //        }
    //        set {
    //            this.customernameField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public bool delnotenum {
    //        get {
    //            return this.delnotenumField;
    //        }
    //        set {
    //            this.delnotenumField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string locn {
    //        get {
    //            return this.locnField;
    //        }
    //        set {
    //            this.locnField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string buffno {
    //        get {
    //            return this.buffnoField;
    //        }
    //        set {
    //            this.buffnoField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public int user {
    //        get {
    //            return this.userField;
    //        }
    //        set {
    //            this.userField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string origbuffbranchno {
    //        get {
    //            return this.origbuffbranchnoField;
    //        }
    //        set {
    //            this.origbuffbranchnoField = value;
    //        }
    //    }
    //}

    ///// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://strategicthought.com/webservices/")]
    //public partial class DNparameters {

    //    private string custIDField;

    //    private int userSaleField;

    //    private int userField;

    //    private string printTextField;

    //    private string acctnoField;

    //    private int buffLocnField;

    //    private int delnotenumField;

    //    private System.DateTime dateReqDelField;

    //    private string delAddressTypeField;

    //    private string timeReqDelField;

    //    /// <remarks/>
    //    public string custID {
    //        get {
    //            return this.custIDField;
    //        }
    //        set {
    //            this.custIDField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public int userSale {
    //        get {
    //            return this.userSaleField;
    //        }
    //        set {
    //            this.userSaleField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public int user {
    //        get {
    //            return this.userField;
    //        }
    //        set {
    //            this.userField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string printText {
    //        get {
    //            return this.printTextField;
    //        }
    //        set {
    //            this.printTextField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string acctno {
    //        get {
    //            return this.acctnoField;
    //        }
    //        set {
    //            this.acctnoField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public int buffLocn {
    //        get {
    //            return this.buffLocnField;
    //        }
    //        set {
    //            this.buffLocnField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public int delnotenum {
    //        get {
    //            return this.delnotenumField;
    //        }
    //        set {
    //            this.delnotenumField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public System.DateTime dateReqDel {
    //        get {
    //            return this.dateReqDelField;
    //        }
    //        set {
    //            this.dateReqDelField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string delAddressType {
    //        get {
    //            return this.delAddressTypeField;
    //        }
    //        set {
    //            this.delAddressTypeField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string timeReqDel {
    //        get {
    //            return this.timeReqDelField;
    //        }
    //        set {
    //            this.timeReqDelField = value;
    //        }
    //    }
    //}

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://strategicthought.com/webservices/")]
    public partial class NumberFormatInfo
    {

        private int currencyDecimalDigitsField;

        private string currencyDecimalSeparatorField;

        private int[] currencyGroupSizesField;

        private int[] numberGroupSizesField;

        private int[] percentGroupSizesField;

        private string currencyGroupSeparatorField;

        private string currencySymbolField;

        private string naNSymbolField;

        private int currencyNegativePatternField;

        private int numberNegativePatternField;

        private int percentPositivePatternField;

        private int percentNegativePatternField;

        private string negativeInfinitySymbolField;

        private string negativeSignField;

        private int numberDecimalDigitsField;

        private string numberDecimalSeparatorField;

        private string numberGroupSeparatorField;

        private int currencyPositivePatternField;

        private string positiveInfinitySymbolField;

        private string positiveSignField;

        private int percentDecimalDigitsField;

        private string percentDecimalSeparatorField;

        private string percentGroupSeparatorField;

        private string percentSymbolField;

        private string perMilleSymbolField;

        private string[] nativeDigitsField;

        private DigitShapes digitSubstitutionField;

        /// <remarks/>
        public int CurrencyDecimalDigits
        {
            get
            {
                return this.currencyDecimalDigitsField;
            }
            set
            {
                this.currencyDecimalDigitsField = value;
            }
        }

        /// <remarks/>
        public string CurrencyDecimalSeparator
        {
            get
            {
                return this.currencyDecimalSeparatorField;
            }
            set
            {
                this.currencyDecimalSeparatorField = value;
            }
        }

        /// <remarks/>
        public int[] CurrencyGroupSizes
        {
            get
            {
                return this.currencyGroupSizesField;
            }
            set
            {
                this.currencyGroupSizesField = value;
            }
        }

        /// <remarks/>
        public int[] NumberGroupSizes
        {
            get
            {
                return this.numberGroupSizesField;
            }
            set
            {
                this.numberGroupSizesField = value;
            }
        }

        /// <remarks/>
        public int[] PercentGroupSizes
        {
            get
            {
                return this.percentGroupSizesField;
            }
            set
            {
                this.percentGroupSizesField = value;
            }
        }

        /// <remarks/>
        public string CurrencyGroupSeparator
        {
            get
            {
                return this.currencyGroupSeparatorField;
            }
            set
            {
                this.currencyGroupSeparatorField = value;
            }
        }

        /// <remarks/>
        public string CurrencySymbol
        {
            get
            {
                return this.currencySymbolField;
            }
            set
            {
                this.currencySymbolField = value;
            }
        }

        /// <remarks/>
        public string NaNSymbol
        {
            get
            {
                return this.naNSymbolField;
            }
            set
            {
                this.naNSymbolField = value;
            }
        }

        /// <remarks/>
        public int CurrencyNegativePattern
        {
            get
            {
                return this.currencyNegativePatternField;
            }
            set
            {
                this.currencyNegativePatternField = value;
            }
        }

        /// <remarks/>
        public int NumberNegativePattern
        {
            get
            {
                return this.numberNegativePatternField;
            }
            set
            {
                this.numberNegativePatternField = value;
            }
        }

        /// <remarks/>
        public int PercentPositivePattern
        {
            get
            {
                return this.percentPositivePatternField;
            }
            set
            {
                this.percentPositivePatternField = value;
            }
        }

        /// <remarks/>
        public int PercentNegativePattern
        {
            get
            {
                return this.percentNegativePatternField;
            }
            set
            {
                this.percentNegativePatternField = value;
            }
        }

        /// <remarks/>
        public string NegativeInfinitySymbol
        {
            get
            {
                return this.negativeInfinitySymbolField;
            }
            set
            {
                this.negativeInfinitySymbolField = value;
            }
        }

        /// <remarks/>
        public string NegativeSign
        {
            get
            {
                return this.negativeSignField;
            }
            set
            {
                this.negativeSignField = value;
            }
        }

        /// <remarks/>
        public int NumberDecimalDigits
        {
            get
            {
                return this.numberDecimalDigitsField;
            }
            set
            {
                this.numberDecimalDigitsField = value;
            }
        }

        /// <remarks/>
        public string NumberDecimalSeparator
        {
            get
            {
                return this.numberDecimalSeparatorField;
            }
            set
            {
                this.numberDecimalSeparatorField = value;
            }
        }

        /// <remarks/>
        public string NumberGroupSeparator
        {
            get
            {
                return this.numberGroupSeparatorField;
            }
            set
            {
                this.numberGroupSeparatorField = value;
            }
        }

        /// <remarks/>
        public int CurrencyPositivePattern
        {
            get
            {
                return this.currencyPositivePatternField;
            }
            set
            {
                this.currencyPositivePatternField = value;
            }
        }

        /// <remarks/>
        public string PositiveInfinitySymbol
        {
            get
            {
                return this.positiveInfinitySymbolField;
            }
            set
            {
                this.positiveInfinitySymbolField = value;
            }
        }

        /// <remarks/>
        public string PositiveSign
        {
            get
            {
                return this.positiveSignField;
            }
            set
            {
                this.positiveSignField = value;
            }
        }

        /// <remarks/>
        public int PercentDecimalDigits
        {
            get
            {
                return this.percentDecimalDigitsField;
            }
            set
            {
                this.percentDecimalDigitsField = value;
            }
        }

        /// <remarks/>
        public string PercentDecimalSeparator
        {
            get
            {
                return this.percentDecimalSeparatorField;
            }
            set
            {
                this.percentDecimalSeparatorField = value;
            }
        }

        /// <remarks/>
        public string PercentGroupSeparator
        {
            get
            {
                return this.percentGroupSeparatorField;
            }
            set
            {
                this.percentGroupSeparatorField = value;
            }
        }

        /// <remarks/>
        public string PercentSymbol
        {
            get
            {
                return this.percentSymbolField;
            }
            set
            {
                this.percentSymbolField = value;
            }
        }

        /// <remarks/>
        public string PerMilleSymbol
        {
            get
            {
                return this.perMilleSymbolField;
            }
            set
            {
                this.perMilleSymbolField = value;
            }
        }

        /// <remarks/>
        public string[] NativeDigits
        {
            get
            {
                return this.nativeDigitsField;
            }
            set
            {
                this.nativeDigitsField = value;
            }
        }

        /// <remarks/>
        public DigitShapes DigitSubstitution
        {
            get
            {
                return this.digitSubstitutionField;
            }
            set
            {
                this.digitSubstitutionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://strategicthought.com/webservices/")]
    public enum DigitShapes
    {

        /// <remarks/>
        Context,

        /// <remarks/>
        None,

        /// <remarks/>
        NativeNational,
    }

    ///// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://strategicthought.com/webservices/")]
    //public partial class PrintingAgreementResult {

    //    private double itemsPerPageField;

    //    private string filenameField;

    //    private System.Xml.XmlNode lineitemsField;

    //    private int noCopiesField;

    //    private string jointNameField;

    //    private int custCopiesField;

    //    private string relationshipField;

    //    private string jointIDField;

    //    private System.Data.DataSet customerField;

    //    private bool agrTimePrintField;

    //    private System.Data.DataSet agreementField;

    //    private NumberFormatInfo localformatField;

    //    private decimal percenttopayField;

    //    private bool incInsinServAgrPrintField;

    //    private bool insIncludedField;

    //    private decimal chargeablePriceField;

    //    private decimal chargeableAdminPriceField;

    //    private decimal insPcentField;

    //    private int monthsField;

    //    private int paymentHolidaysMaxField;

    //    private short paymentHolidaysMinField;

    //    private short print90Field;

    //    private string termsDescriptionField;

    //    private string agreementTextField;

    //    private bool paymentHolidaysField;

    //    private decimal servicePCentField;

    //    /// <remarks/>
    //    public double itemsPerPage {
    //        get {
    //            return this.itemsPerPageField;
    //        }
    //        set {
    //            this.itemsPerPageField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string filename {
    //        get {
    //            return this.filenameField;
    //        }
    //        set {
    //            this.filenameField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public System.Xml.XmlNode lineitems {
    //        get {
    //            return this.lineitemsField;
    //        }
    //        set {
    //            this.lineitemsField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public int noCopies {
    //        get {
    //            return this.noCopiesField;
    //        }
    //        set {
    //            this.noCopiesField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string JointName {
    //        get {
    //            return this.jointNameField;
    //        }
    //        set {
    //            this.jointNameField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public int custCopies {
    //        get {
    //            return this.custCopiesField;
    //        }
    //        set {
    //            this.custCopiesField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string relationship {
    //        get {
    //            return this.relationshipField;
    //        }
    //        set {
    //            this.relationshipField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string JointID {
    //        get {
    //            return this.jointIDField;
    //        }
    //        set {
    //            this.jointIDField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public System.Data.DataSet customer {
    //        get {
    //            return this.customerField;
    //        }
    //        set {
    //            this.customerField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public bool AgrTimePrint {
    //        get {
    //            return this.agrTimePrintField;
    //        }
    //        set {
    //            this.agrTimePrintField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public System.Data.DataSet agreement {
    //        get {
    //            return this.agreementField;
    //        }
    //        set {
    //            this.agreementField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public NumberFormatInfo localformat {
    //        get {
    //            return this.localformatField;
    //        }
    //        set {
    //            this.localformatField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public decimal percenttopay {
    //        get {
    //            return this.percenttopayField;
    //        }
    //        set {
    //            this.percenttopayField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public bool IncInsinServAgrPrint {
    //        get {
    //            return this.incInsinServAgrPrintField;
    //        }
    //        set {
    //            this.incInsinServAgrPrintField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public bool insIncluded {
    //        get {
    //            return this.insIncludedField;
    //        }
    //        set {
    //            this.insIncludedField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public decimal chargeablePrice {
    //        get {
    //            return this.chargeablePriceField;
    //        }
    //        set {
    //            this.chargeablePriceField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public decimal chargeableAdminPrice {
    //        get {
    //            return this.chargeableAdminPriceField;
    //        }
    //        set {
    //            this.chargeableAdminPriceField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public decimal insPcent {
    //        get {
    //            return this.insPcentField;
    //        }
    //        set {
    //            this.insPcentField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public int months {
    //        get {
    //            return this.monthsField;
    //        }
    //        set {
    //            this.monthsField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public int PaymentHolidaysMax {
    //        get {
    //            return this.paymentHolidaysMaxField;
    //        }
    //        set {
    //            this.paymentHolidaysMaxField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public short PaymentHolidaysMin {
    //        get {
    //            return this.paymentHolidaysMinField;
    //        }
    //        set {
    //            this.paymentHolidaysMinField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public short Print90 {
    //        get {
    //            return this.print90Field;
    //        }
    //        set {
    //            this.print90Field = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string TermsDescription {
    //        get {
    //            return this.termsDescriptionField;
    //        }
    //        set {
    //            this.termsDescriptionField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string AgreementText {
    //        get {
    //            return this.agreementTextField;
    //        }
    //        set {
    //            this.agreementTextField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public bool PaymentHolidays {
    //        get {
    //            return this.paymentHolidaysField;
    //        }
    //        set {
    //            this.paymentHolidaysField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public decimal ServicePCent {
    //        get {
    //            return this.servicePCentField;
    //        }
    //        set {
    //            this.servicePCentField = value;
    //        }
    //    }
    //}

    ///// <remarks/>
    //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    //[System.SerializableAttribute()]
    //[System.Diagnostics.DebuggerStepThroughAttribute()]
    //[System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://strategicthought.com/webservices/")]
    //public partial class PrintingAgreementRequest {

    //    private string customerIDField;

    //    private string accountNoField;

    //    private string accountTypeField;

    //    private string countrycodeField;

    //    /// <remarks/>
    //    public string customerID {
    //        get {
    //            return this.customerIDField;
    //        }
    //        set {
    //            this.customerIDField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string accountNo {
    //        get {
    //            return this.accountNoField;
    //        }
    //        set {
    //            this.accountNoField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string accountType {
    //        get {
    //            return this.accountTypeField;
    //        }
    //        set {
    //            this.accountTypeField = value;
    //        }
    //    }

    //    /// <remarks/>
    //    public string countrycode {
    //        get {
    //            return this.countrycodeField;
    //        }
    //        set {
    //            this.countrycodeField = value;
    //        }
    //    }
    //}

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetFileInfoCompletedEventHandler(object sender, GetFileInfoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFileInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetFileInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.DateTime modified
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }

        /// <remarks/>
        public double size
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[1]));
            }
        }

        /// <remarks/>
        public string path
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DownloadFileCompletedEventHandler(object sender, DownloadFileCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownloadFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal DownloadFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public byte[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAgreeementPrintCompletedEventHandler(object sender, GetAgreeementPrintCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAgreeementPrintCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetAgreeementPrintCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public STL.Common.PrintingAgreementResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((STL.Common.PrintingAgreementResult)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetDNPrintInfoCompletedEventHandler(object sender, GetDNPrintInfoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDNPrintInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetDNPrintInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public STL.Common.PrintingDN[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((STL.Common.PrintingDN[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetDNPrintScheduleItemsCompletedEventHandler(object sender, GetDNPrintScheduleItemsCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDNPrintScheduleItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetDNPrintScheduleItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public STL.Common.PrintingDN[] Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((STL.Common.PrintingDN[])(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetDecimalPlacesCompletedEventHandler(object sender, GetDecimalPlacesCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDecimalPlacesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetDecimalPlacesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void HostNameCompletedEventHandler(object sender, HostNameCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HostNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal HostNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetASPrintInfoCompletedEventHandler(object sender, GetASPrintInfoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetASPrintInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetASPrintInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public STL.Common.PrintingAction Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((STL.Common.PrintingAction)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591