-- transaction: true
-- Change the previous line to false to disable running this whole migration in one transaction.
-- Removing that first line will default to 'true'.
-- 
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Sales].[CurrencyCodes]') AND type in (N'U'))
DROP TABLE [Sales].[CurrencyCodes]
GO

CREATE TABLE [Sales].[CurrencyCodes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CurrencyCode] char(3) NOT NULL,
	[CurrencyName] [varchar](64) NOT NULL,		
CONSTRAINT [PK_Sales.CurrencyCodes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]




INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('AED','United Arab Emirates Dirham')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('AFN','Afghan Afghani')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('ALL','Albanian Lek')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('AMD','Armenian Dram')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('ANG','Netherlands Antillean Guilder')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('AOA','Angolan Kwanza')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('ARS','Argentine Peso')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('AUD','Australian Dollar')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('AWG','Aruban Florin')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('AZN','Azerbaijani Manat')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('BAM','Bosnia and Herzegovina Convertible Mark')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('BBD','Barbados Dollar')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('BDT','Bangladeshi Taka')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('BGN','Bulgarian Lev')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('BHD','Bahraini Dinar')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('BIF','Burundian Franc')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('BMD','Bermudian Dollar')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('BND','Brunei Dollar')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('BOB','Boliviano')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('BOV','Bolivian Mvdol Funds Code')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('BRL','Brazilian Real')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('BSD','Bahamian Dollar')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('BTN','Bhutanese ngultrum')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('BWP','Botswana Pula')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('BYR','Belarusian Ruble')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('BZD','Belize Dollar')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('CAD','Canadian Dollar')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('CDF','Congolese Franc')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('CHE','WIR Euro Complementary Currency')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('CHF','Swiss Franc')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('CHW','WIR Franc Complementary Currency')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('CLF','Unidad de Fomento Funds code')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('CLP','Chilean Peso')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('CNH','Chinese Yuan Traded in Hong Kong')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('CNY','Chinese Yuan')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('COP','Colombian Peso')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('COU','Unidad de Valor Real UVR Funds Code')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('CRC','Costa Rican Colon')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('CUC','Cuban Convertible Peso')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('CUP','Cuban Peso')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('CVE','Cape Verde Escudo')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('CZK','Czech Koruna')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('DJF','Djiboutian Franc')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('DKK','Danish Krone')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('DOP','Dominican Peso')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('DZD','Algerian Dinar')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('EGP','Egyptian Pound')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('ERN','Eritrean Nakfa')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('ETB','Ethiopian Birr')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('EUR','Euro')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('FJD','Fiji Dollar')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('FKP','Falkland Islands Pound')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('GBP','Pound Sterling')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('GEL','Georgian Lari')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('GHS','Ghanaian Cedi')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('GIP','Gibraltar Pound')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('GMD','Gambian Dalasi')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('GNF','Guinean Franc')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('GTQ','Guatemalan Quetzal')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('GYD','Guyanese Dollar')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('HKD','Hong Kong Dollar')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('HNL','Honduran Lempira')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('HRK','Croatian Kuna')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('HTG','Haitian Gourde')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('HUF','Hungarian Forint')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('IDR','Indonesian Rupiah')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('ILS','Israeli New Shekel')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('INR','Indian Rupee')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('IQD','Iraqi Dinar')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('IRR','Iranian Rial')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('ISK','Icelandic Króna')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('JMD','Jamaican Dollar')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('JOD','Jordanian Dinar')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('JPY','Japanese Yen')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('KES','Kenyan Shilling')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('KGS','Kyrgyzstani Som')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('KHR','Cambodian Riel')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('KMF','Comoro Franc')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('KPW','North Korean Won')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('KRW','South Korean Won')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('KWD','Kuwaiti Dinar')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('KYD','Cayman Islands Dollar')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('KZT','Kazakhstani Tenge')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('LAK','Lao Kip')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('LBP','Lebanese Pound')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('LKR','Sri Lankan Rupee')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('LRD','Liberian Dollar')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('LSL','Lesotho Loti')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('LTL','Lithuanian Litas')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('LYD','Libyan Dinar')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('MAD','Moroccan Dirham')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('MDL','Moldovan Leu')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('MGA','Malagasy Ariary')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('MKD','Macedonian Denar')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('MMK','Myanmar Kyat')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('MNT','Mongolian Tugrik')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('MOP','Macanese Pataca')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('MRO','Mauritanian Ouguiya')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('MUR','Mauritian Rupee')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('MVR','Maldivian Rufiyaa')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('MWK','Malawian Kwacha')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('MXN','Mexican Peso')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('MXV','Mexican Unidad de Inversion UDI Funds Code')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('MYR','Malaysian Ringgit')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('MZN','Mozambican Metical')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('NAD','Namibian Dollar')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('NGN','Nigerian Naira')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('NIO','Nicaraguan Cordoba')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('NOK','Norwegian Krone')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('NPR','Nepalese Rupee')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('NZD','New Zealand Dollar')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('OMR','Omani Rial')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('PAB','Panamanian Balboa')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('PEN','Peruvian Nuevo Sol')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('PGK','Papua New Guinean Kina')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('PHP','Philippine Peso')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('PKR','Pakistani Rupee')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('PLN','Polish Zioty')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('PYG','Paraguayan Guaraní')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('QAR','Qatari Riyal')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('RON','Romanian New Leu')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('RSD','Serbian Dinar')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('RUB','Russian Ruble')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('RWF','Rwandan Franc')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('SAR','Saudi Riyal')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('SBD','Solomon Islands Dollar')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('SCR','Seychelles Rupee')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('SDG','Sudanese Pound')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('SEK','Swedish Krona Kronor')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('SGD','Singapore Dollar')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('SHP','Saint Helena Pound')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('SLL','Sierra Leonean Leone')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('SOS','Somali Shilling')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('SRD','Surinamese Dollar')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('SSP','South Sudanese Pound')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('STD','Sao Tome and Principe Dobra')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('SYP','Syrian Pound')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('SZL','Swazi Lilangeni')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('THB','Thai Baht')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('TJS','Tajikistani Somoni')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('TMT','Turkmenistani Manat')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('TND','Tunisian Dinar')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('TOP','Tongan Paanga')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('TRY','Turkish Lira')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('TTD','Trinidad and Tobago Dollar')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('TWD','New Taiwan Dollar')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('TZS','Tanzanian Shilling')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('UAH','Ukrainian Hryvnia')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('UGX','Ugandan Shilling')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('USD','United States Dollar')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('USN','United States Dollar Nnext Day Funds Code')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('USS','United States Dollar Same Day Funds Code')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('UYI','Uruguay Peso en Unidades Indexadas Funds Code')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('UYU','Uruguayan Peso')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('UZS','Uzbekistan Som')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('VEF','Venezuelan Bolivar')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('VND','Vietnamese Dong')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('VUV','Vanuatu Vatu')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('WST','Samoan Tala')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('XAF','CFA Franc BEAC')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('XAG','Silver One Troy Ounce')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('XAU','Gold One Troy Ounce')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('XBA','European Composite Unit Bond Market Unit')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('XBB','European Monetary Unit Bond Market Unit')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('XBC','European Unit of Account 9 Bond Market Unit')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('XBD','European Unit of Account 17 Bond Market Unit')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('XCD','East Caribbean Dollar')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('XDR','Special Drawing Rights')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('XFU','UIC Franc Special Settlement Currency')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('XOF','CFA Franc BCEAO')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('XPD','Palladium One Troy Ounce')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('XPF','CFP Franc Pacifique')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('XPT','Platinum One Troy Ounce')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('XSU','SUCRE')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('XUA','ADB Unit of Account')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('YER','Yemeni Rial')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('ZAR','South African Rand')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('ZMW','Zambian Kwacha')
INSERT INTO Sales.[CurrencyCodes] (CurrencyCode, CurrencyName)  VALUES     ('ZWD','Zimbabwe Dollar')