IF EXISTS (SELECT * FROM sysobjects WHERE NAME = 'VE_SecretToken')
	BEGIN
		DROP TABLE [dbo].[VE_SecretToken]
	END
GO

CREATE TABLE [dbo].[VE_SecretToken](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[token] [nvarchar](max) NOT NULL,
	[expiration] [datetime] NOT NULL,
 CONSTRAINT [PK_VE_SecretToken] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO