IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE Table_Name = 'VE_LineItem' AND  Column_Name = 'MVEUserID')
BEGIN
	ALTER TABLE VE_lineitem ADD MVEUserID int;
	ALTER TABLE VE_lineitem ADD CoSaCSUserID int;
END