
CREATE TABLE Admin.AddtionalProfile
	(
	Id int NOT NULL IDENTITY (1, 1),
	Name varchar(20) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE Admin.AddtionalProfile ADD CONSTRAINT
	PK_AddtionalProfile PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE Admin.AddtionalProfile SET (LOCK_ESCALATION = TABLE)
GO
