
/****** Object:  Table [Config].[DecisionTableType]    Script Date: 11/23/2012 14:27:17 ******/
INSERT [Config].[DecisionTableType] ([Key]) VALUES (N'SR.DecisionTable')

-- -- DELETE FROM Config.DecisionTable  -- -- --
-- -- DELETE FROM Config.DecisionTableType -- --

/****** Object:  Table [Config].[DecisionTable]    Script Date: 11/23/2012 14:27:17 ******/
SET IDENTITY_INSERT [Config].[DecisionTable] ON
INSERT [Config].[DecisionTable] ([Id], [Key], [CreatedUtc], [Value]) VALUES (1, N'SR.DecisionTable', CAST(0x0000A11200E63598 AS DateTime), N'{"conditions":[{"expression":"$scope.serviceRequest.Type","$$hashKey":"00K"},{"expression":"isNaN($scope.serviceRequest.ItemId)","$$hashKey":"00M"},{"expression":"($scope.serviceRequest.WarrantyContractNumber !== null &&\n!isNaN($scope.serviceRequest.WarrantyContractNumber))","$$hashKey":"00O"},{"expression":"((new Date(+$scope.serviceRequest.ItemSoldOn +\n (new Date((365.25/12)*(24*3600*1000)) *\n $scope.serviceRequest.WarrantyLength))) >= (new Date()))","$$hashKey":"00Q"}],"actions":[{"expression":"$scope.hideOptionFoodLoss();","$$hashKey":"010"},{"expression":"$scope.hideCustomerDetails();","$$hashKey":"012"},{"expression":"$scope.hideEvaluation();","$$hashKey":"014"},{"expression":"$scope.hidePrintFoodLoss();","$$hashKey":"016"},{"expression":"$scope.DisableProduct();","$$hashKey":"018"},{"expression":"$scope.displayOutOfWarrantyCoverMessage();","$$hashKey":"01A"}],"rules":[{"values":["SI",null,null,null],"actions":[false,false,false,false,true,false],"$$hashKey":"004"},{"values":["SE","",null,null],"actions":[true,false,false,false,false,false],"$$hashKey":"006"},{"values":["II","","",null],"actions":[true,false,true,false,true,false],"$$hashKey":"008"},{"values":["IE","",null,""],"actions":[true,false,true,false,false,false],"$$hashKey":"00A"},{"values":["S",null,null,null],"actions":[true,true,true,false,false,false],"$$hashKey":"00C"},{"values":["SI",null,"false",null],"actions":[false,false,false,false,false,true],"$$hashKey":"00E"},{"values":["SI",null,null,"false"],"actions":[false,false,false,false,false,true],"$$hashKey":"00G"},{"values":[null,"true",null,null],"actions":[false,false,false,true,false,false],"$$hashKey":"00I"}]}')
INSERT [Config].[DecisionTable] ([Id], [Key], [CreatedUtc], [Value]) VALUES (2, N'SR.DecisionTable', CAST(0x0000A11200E6C814 AS DateTime), N'{"conditions":["$scope.serviceRequest.Type","isNaN($scope.serviceRequest.ItemId)","($scope.serviceRequest.WarrantyContractNumber !== null &&\n!isNaN($scope.serviceRequest.WarrantyContractNumber))","((new Date(+$scope.serviceRequest.ItemSoldOn +\n (new Date((365.25/12)*(24*3600*1000)) *\n $scope.serviceRequest.WarrantyLength))) >= (new Date()))"],"actions":["$scope.hideOptionFoodLoss();","$scope.hideCustomerDetails();","$scope.hideEvaluation();","$scope.hidePrintFoodLoss();","$scope.DisableProduct();","$scope.displayOutOfWarrantyCoverMessage();"],"rules":[{"values":["SI",null,null,null],"actions":[false,false,false,false,true,false],"$$hashKey":"004"},{"values":["SE","",null,null],"actions":[true,false,false,false,false,false],"$$hashKey":"006"},{"values":["II","","",null],"actions":[true,false,true,false,true,false],"$$hashKey":"008"},{"values":["IE","",null,""],"actions":[true,false,true,false,false,false],"$$hashKey":"00A"},{"values":["S",null,null,null],"actions":[true,true,true,false,false,false],"$$hashKey":"00C"},{"values":["SI",null,"false",null],"actions":[false,false,false,false,false,true],"$$hashKey":"00E"},{"values":["SI",null,null,"false"],"actions":[false,false,false,false,false,true],"$$hashKey":"00G"},{"values":[null,"true",null,null],"actions":[false,false,false,true,false,false],"$$hashKey":"00I"}]}')
INSERT [Config].[DecisionTable] ([Id], [Key], [CreatedUtc], [Value]) VALUES (3, N'SR.DecisionTable', CAST(0x0000A11200E72250 AS DateTime), N'{"conditions":[{"expression":"$scope.serviceRequest.Type","$$hashKey":"00K"},{"expression":"isNaN($scope.serviceRequest.ItemId)","$$hashKey":"00M"},{"expression":"($scope.serviceRequest.WarrantyContractNumber !== null &&\n!isNaN($scope.serviceRequest.WarrantyContractNumber))","$$hashKey":"00O"},{"expression":"((new Date(+$scope.serviceRequest.ItemSoldOn +\n (new Date((365.25/12)*(24*3600*1000)) *\n $scope.serviceRequest.WarrantyLength))) >= (new Date()))","$$hashKey":"00Q"}],"actions":[{"expression":"$scope.hideOptionFoodLoss();","$$hashKey":"010"},{"expression":"$scope.hideCustomerDetails();","$$hashKey":"012"},{"expression":"$scope.hideEvaluation();","$$hashKey":"014"},{"expression":"$scope.hidePrintFoodLoss();","$$hashKey":"016"},{"expression":"$scope.DisableProduct();","$$hashKey":"018"},{"expression":"$scope.displayOutOfWarrantyCoverMessage();","$$hashKey":"01A"}],"rules":[{"values":["SI",null,null,null],"actions":[false,false,false,false,true,false],"$$hashKey":"004"},{"values":["SE","",null,null],"actions":[true,false,false,false,false,false],"$$hashKey":"006"},{"values":["II","","",null],"actions":[true,false,true,false,true,false],"$$hashKey":"008"},{"values":["IE","",null,""],"actions":[true,false,true,false,false,false],"$$hashKey":"00A"},{"values":["S",null,null,null],"actions":[true,true,true,false,false,false],"$$hashKey":"00C"},{"values":["SI",null,"false",null],"actions":[false,false,false,false,false,true],"$$hashKey":"00E"},{"values":["SI",null,null,"false"],"actions":[false,false,false,false,false,true],"$$hashKey":"00G"},{"values":[null,"true",null,null],"actions":[false,false,false,true,false,false],"$$hashKey":"00I"}]}')
SET IDENTITY_INSERT [Config].[DecisionTable] OFF
