IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[CMWorkListRights]') AND name = N'PK_CMWorkListRights')
ALTER TABLE [dbo].[CMWorkListRights] DROP CONSTRAINT [PK_CMWorkListRights]
GO

ALTER TABLE dbo.CMWorkListRights
DROP COLUMN empeetype
GO

ALTER TABLE [dbo].[CMWorkListRights] ADD  CONSTRAINT [PK_CMWorkListRights] PRIMARY KEY CLUSTERED 
(
	[EmpeeNo] ASC,
	[WorkList] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


