CREATE TABLE SERVICE.ContactTypeLookup
	(
	Id int NOT NULL IDENTITY (1, 1),
	Type varchar(20) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE SERVICE.ContactTypeLookup ADD CONSTRAINT
	PK_ContactTypeLookup PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO