-- transaction: true
-- Change the previous line to false to disable running this whole migration in one transaction.
-- Removing that first line will default to 'true'.
-- 
-- Put your SQL code here
truncate table [Financial].[TransactionMappingService]

go

insert into [Financial].[TransactionMappingService]
(ChargeType, Label, ServiceType, IsExternal, Replacement, CashNotCredit, Department, Account, Percentage, UseValueColumn, TransactionType)
values
('Customer', 'Labour', '*', 1, NULL, NULL, '*', '9010', 1, 0, 'PAY'),
('Customer', 'Labour', '*', 1, NULL, NULL, '*', '2101', -1, 0, 'PAY'),
('Customer', 'Labour and Additional', '*', 1, NULL, NULL, '*', '9010', 1, 0, 'PAY'),
('Customer', 'Labour and Additional', '*', 1, NULL, NULL, '*', '2101', -1, 0, 'PAY'),
('Customer', 'Additional', '*', 1, NULL, NULL, '*', '9010', 1, 0, 'PAY'),
('Customer', 'Additional', '*', 1, NULL, NULL, '*', '2101', -1, 0, 'PAY'),
('Customer', 'Parts External', '*', 1, NULL, NULL, '*', '9011', 1, 0, 'PAY'),
('Customer', 'Parts External', '*', 1, NULL, NULL, '*', '2101', -1, 0, 'PAY'),
('Supplier', 'Labour and Additional', '*', 0, NULL, NULL, '*', '1392', 1, 1, 'SRS'),
('Supplier', 'Labour and Additional', '*', 0, NULL, NULL, '*', '9020S', -1, 1, 'SRS'),
('Supplier', 'Labour', '*', 0, NULL, NULL, '*', '1392', 1, 1, 'SRS'),
('Supplier', 'Labour', '*', 0, NULL, NULL, '*', '9020S', -1, 1, 'SRS'),
('Supplier', 'Additional', '*', 0, NULL, NULL, '*', '1392', 1, 1, 'SRS'),
('Supplier', 'Additional', '*', 0, NULL, NULL, '*', '9020S', -1, 1, 'SRS'),
('Supplier', 'Labour and Additional', '*', 1, NULL, NULL, '*', '1392', 1, 0, 'SRS'),
('Supplier', 'Labour and Additional', '*', 1, NULL, NULL, '*', '9020S', -1, 0, 'SRS'),
('Supplier', 'Labour', '*', 1, NULL, NULL, '*', '1392', 1, 0, 'SRS'),
('Supplier', 'Labour', '*', 1, NULL, NULL, '*', '9020S', -1, 0, 'SRS'),
('Supplier', 'Additional', '*', 1, NULL, NULL, '*', '1392', 1, 0, 'SRS'),
('Supplier', 'Additional', '*', 1, NULL, NULL, '*', '9020S', -1, 0, 'SRS'),
('Supplier', 'Labour and Additional', '*', 1, NULL, NULL, '*', '9010', 1, 0, 'SRS'),
('Supplier', 'Labour and Additional', '*', 1, NULL, NULL, '*', '2101', -1, 0, 'SRS'),
('Supplier', 'Labour', '*', 1, NULL, NULL, '*', '9010', 1, 0, 'SRS'),
('Supplier', 'Labour', '*', 1, NULL, NULL, '*', '2101', -1, 0, 'SRS'),
('Supplier', 'Additional', '*', 1, NULL, NULL, '*', '9010', 1, 0, 'SRS'),
('Supplier', 'Additional', '*', 1, NULL, NULL, '*', '2101', -1, 0, 'SRS'),
('Supplier', 'Parts Cosacs', '*', 0, NULL, NULL, '*', '1392', 1, 1, 'SRS'),
('Supplier', 'Parts Cosacs', '*', 0, NULL, NULL, '*', '9020S', -1, 1, 'SRS'),
('Supplier', 'Parts Cosacs', '*', 1, NULL, NULL, '*', '1392', -1, 0, 'SRS'),
('Supplier', 'Parts Cosacs', '*', 1, NULL, NULL, '*', '9020S', 1, 0, 'SRS'),
('Supplier', 'Parts External', '*', 0, NULL, NULL, '*', '1392', 1, 1, 'SRS'),
('Supplier', 'Parts External', '*', 0, NULL, NULL, '*', '9020S', -1, 1, 'SRS'),
('Supplier', 'Parts External', '*', 1, NULL, NULL, '*', '1392', 1, 1, 'SRS'),
('Supplier', 'Parts External', '*', 1, NULL, NULL, '*', '9020S', -1, 1, 'SRS'),
('Supplier', 'Parts External', '*', 1, NULL, NULL, '*', '9011', 1, 0, 'SRS'),
('Supplier', 'Parts External', '*', 1, NULL, NULL, '*', '2101', -1, 0, 'SRS'),
('Supplier', 'Parts Salvaged', '*', 0, NULL, NULL, '*', '1392', 1, 1, 'SRS'),
('Supplier', 'Parts Salvaged', '*', 0, NULL, NULL, '*', '9020S', -1, 1, 'SRS'),
('Supplier', 'Parts Salvaged', '*', 0, NULL, NULL, '*', '9011', 1, 0, 'SRS'),
('Supplier', 'Parts Salvaged', '*', 0, NULL, NULL, '*', '2930', -1, 0, 'SRS'),
('Supplier', 'Parts Salvaged', '*', 1, NULL, NULL, '*', '1392', 1, 1, 'SRS'),
('Supplier', 'Parts Salvaged', '*', 1, NULL, NULL, '*', '9020S', -1, 1, 'SRS'),
('Supplier', 'Parts Salvaged', '*', 1, NULL, NULL, '*', '9011', 1, 0, 'SRS'),
('Supplier', 'Parts Salvaged', '*', 1, NULL, NULL, '*', '2930', -1, 0, 'SRS'),
('FYW', 'Labour and Additional', '*', 1, NULL, NULL, '*', '9010', 1, 0, 'SRY'),
('FYW', 'Labour and Additional', '*', 1, NULL, NULL, '*', '2101', -1, 0, 'SRY'),
('FYW', 'Labour', '*', 1, NULL, NULL, '*', '9010', 1, 0, 'SRY'),
('FYW', 'Labour', '*', 1, NULL, NULL, '*', '2101', -1, 0, 'SRY'),
('FYW', 'Additional', '*', 1, NULL, NULL, '*', '9010', 1, 0, 'SRY'),
('FYW', 'Additional', '*', 1, NULL, NULL, '*', '2101', -1, 0, 'SRY'),
('FYW', 'Labour and Additional', '*', 1, NULL, NULL, '*', '2930', 1, 1, 'SRY'),
('FYW', 'Labour and Additional', '*', 1, NULL, NULL, '*', '9020I', -1, 1, 'SRY'),
('FYW', 'Labour', '*', 1, NULL, NULL, '*', '2930', 1, 1, 'SRY'),
('FYW', 'Labour', '*', 1, NULL, NULL, '*', '9020I', -1, 1, 'SRY'),
('FYW', 'Additional', '*', 1, NULL, NULL, '*', '2930', 1, 1, 'SRY'),
('FYW', 'Additional', '*', 1, NULL, NULL, '*', '9020I', -1, 1, 'SRY'),
('FYW', 'Labour and Additional', '*', 0, NULL, NULL, '*', '2930', 1, 1, 'SRY'),
('FYW', 'Labour and Additional', '*', 0, NULL, NULL, '*', '9020I', -1, 1, 'SRY'),
('FYW', 'Labour', '*', 0, NULL, NULL, '*', '2930', 1, 1, 'SRY'),
('FYW', 'Labour', '*', 0, NULL, NULL, '*', '9020I', -1, 1, 'SRY'),
('FYW', 'Additional', '*', 0, NULL, NULL, '*', '2930', 1, 1, 'SRY'),
('FYW', 'Additional', '*', 0, NULL, NULL, '*', '9020I', -1, 1, 'SRY'),
('FYW', 'Parts Salvaged', '*', 0, NULL, NULL, '*', '2930', 1, 1, 'SRY'),
('FYW', 'Parts Salvaged', '*', 0, NULL, NULL, '*', '9020I', -1, 1, 'SRY'),
('FYW', 'Parts Salvaged', '*', 0, NULL, NULL, '*', '9011', 1, 0, 'SRY'),
('FYW', 'Parts Salvaged', '*', 0, NULL, NULL, '*', '2930', -1, 0, 'SRY'),
('FYW', 'Parts Salvaged', '*', 1, NULL, NULL, '*', '2930', 1, 1, 'SRY'),
('FYW', 'Parts Salvaged', '*', 1, NULL, NULL, '*', '9020I', -1, 1, 'SRY'),
('FYW', 'Parts Salvaged', '*', 1, NULL, NULL, '*', '9011', 1, 0, 'SRY'),
('FYW', 'Parts Salvaged', '*', 1, NULL, NULL, '*', '2930', -1, 0, 'SRY'),
('FYW', 'Parts Cosacs', '*', 0, NULL, NULL, '*', '2930', 1, 1, 'SRY'),
('FYW', 'Parts Cosacs', '*', 0, NULL, NULL, '*', '9020I', -1, 1, 'SRY'),
('FYW', 'Parts Cosacs', '*', 1, NULL, NULL, '*', '2930', 1, 1, 'SRY'),
('FYW', 'Parts Cosacs', '*', 1, NULL, NULL, '*', '9020I', -1, 1, 'SRY'),
('FYW', 'Parts External', '*', 1, NULL, NULL, '*', '2930', 1, 1, 'SRY'),
('FYW', 'Parts External', '*', 1, NULL, NULL, '*', '9020I', -1, 1, 'SRY'),
('FYW', 'Parts External', '*', 1, NULL, NULL, '*', '9011', 1, 0, 'SRY'),
('FYW', 'Parts External', '*', 1, NULL, NULL, '*', '2101', -1, 0, 'SRY'),
('EW', 'Labour and Additional', '*', 0, NULL, NULL, '*', '2910', 1, 1, 'SRW'),
('EW', 'Labour and Additional', '*', 0, NULL, NULL, '*', '9020E', -1, 1, 'SRW'),
('EW', 'Labour', '*', 0, NULL, NULL, '*', '2910', 1, 1, 'SRW'),
('EW', 'Labour', '*', 0, NULL, NULL, '*', '9020E', -1, 1, 'SRW'),
('EW', 'Additional', '*', 0, NULL, NULL, '*', '2910', 1, 1, 'SRW'),
('EW', 'Additional', '*', 0, NULL, NULL, '*', '9020E', -1, 1, 'SRW'),
('EW', 'Labour and Additional', '*', 1, NULL, NULL, '*', '9010', 1, 0, 'SRW'),
('EW', 'Labour and Additional', '*', 1, NULL, NULL, '*', '2101', -1, 0, 'SRW'),
('EW', 'Labour', '*', 1, NULL, NULL, '*', '9010', 1, 0, 'SRW'),
('EW', 'Labour', '*', 1, NULL, NULL, '*', '2101', -1, 0, 'SRW'),
('EW', 'Additional', '*', 1, NULL, NULL, '*', '9010', 1, 0, 'SRW'),
('EW', 'Additional', '*', 1, NULL, NULL, '*', '2101', -1, 0, 'SRW'),
('EW', 'Labour and Additional', '*', 1, NULL, NULL, '*', '2910', 1, 1, 'SRW'),
('EW', 'Labour and Additional', '*', 1, NULL, NULL, '*', '9020E', -1, 1, 'SRW'),
('EW', 'Labour', '*', 1, NULL, NULL, '*', '2910', 1, 1, 'SRW'),
('EW', 'Labour', '*', 1, NULL, NULL, '*', '9020E', -1, 1, 'SRW'),
('EW', 'Additional', '*', 1, NULL, NULL, '*', '2910', 1, 1, 'SRW'),
('EW', 'Additional', '*', 1, NULL, NULL, '*', '9020E', -1, 1, 'SRW'),
('EW', 'Parts Cosacs', '*', 0, 1, NULL, '*', '2910', 1, 0, 'SRW'),
('EW', 'Parts Cosacs', '*', 0, 1, NULL, '*', '9020E', -1, 1, 'SRW'),
('EW', 'Parts Cosacs', '*', 0, NULL, NULL, '*', '2910', 1, 1, 'SRW'),
('EW', 'Parts Cosacs', '*', 0, NULL, NULL, '*', '9020E', -1, 1, 'SRW'),
('EW', 'Parts Cosacs', '*', 1, NULL, NULL, '*', '2910', 1, 1, 'SRW'),
('EW', 'Parts Cosacs', '*', 1, NULL, NULL, '*', '9020E', -1, 1, 'SRW'),
('EW', 'Parts External', '*', 1, NULL, NULL, '*', '2910', 1, 1, 'SRW'),
('EW', 'Parts External', '*', 1, NULL, NULL, '*', '9020E', -1, 1, 'SRW'),
('EW', 'Parts External', '*', 1, NULL, NULL, '*', '9011', 1, 0, 'SRW'),
('EW', 'Parts External', '*', 1, NULL, NULL, '*', '2101', -1, 0, 'SRW'),
('EW', 'Parts Salvaged', '*', 0, NULL, NULL, '*', '2910', 1, 1, 'SRW'),
('EW', 'Parts Salvaged', '*', 0, NULL, NULL, '*', '9020E', -1, 1, 'SRW'),
('EW', 'Parts Salvaged', '*', 0, NULL, NULL, '*', '9011', 1, 0, 'SRW'),
('EW', 'Parts Salvaged', '*', 0, NULL, NULL, '*', '2910', -1, 0, 'SRW'),
('EW', 'Parts Salvaged', '*', 1, NULL, NULL, '*', '2910', 1, 1, 'SRW'),
('EW', 'Parts Salvaged', '*', 1, NULL, NULL, '*', '9020E', -1, 1, 'SRW'),
('EW', 'Parts Salvaged', '*', 1, NULL, NULL, '*', '9011', 1, 0, 'SRW'),
('EW', 'Parts Salvaged', '*', 1, NULL, NULL, '*', '2910', -1, 0, 'SRW'),
('Internal', 'Labour and Additional', 'S', 0, NULL, NULL, '*', '9010', 1, 0, 'SRI'),
('Internal', 'Labour and Additional', 'S', 0, NULL, NULL, '*', '9020B', -1, 0, 'SRI'),
('Internal', 'Labour', 'S', 0, NULL, NULL, '*', '9010', 1, 0, 'SRI'),
('Internal', 'Labour', 'S', 0, NULL, NULL, '*', '9020B', -1, 0, 'SRI'),
('Internal', 'Additional', 'S', 0, NULL, NULL, '*', '9010', 1, 0, 'SRI'),
('Internal', 'Additional', 'S', 0, NULL, NULL, '*', '9020B', -1, 0, 'SRI'),
('Internal', 'Labour and Additional', 'S', 1, NULL, NULL, '*', '9010', 1, 0, 'SRI'),
('Internal', 'Labour and Additional', 'S', 1, NULL, NULL, '*', '9020B', -1, 0, 'SRI'),
('Internal', 'Labour', 'S', 1, NULL, NULL, '*', '9010', 1, 0, 'SRI'),
('Internal', 'Labour', 'S', 1, NULL, NULL, '*', '9020B', -1, 0, 'SRI'),
('Internal', 'Additional', 'S', 1, NULL, NULL, '*', '9010', 1, 0, 'SRI'),
('Internal', 'Additional', 'S', 1, NULL, NULL, '*', '9020B', -1, 0, 'SRI'),
('Internal', 'Labour and Additional', '*', 1, NULL, NULL, '*', '9010', 1, 1, 'SRI'),
('Internal', 'Labour and Additional', '*', 1, NULL, NULL, '*', '2101', -1, 1, 'SRI'),
('Internal', 'Labour', '*', 1, NULL, NULL, '*', '9010', 1, 1, 'SRI'),
('Internal', 'Labour', '*', 1, NULL, NULL, '*', '2101', -1, 1, 'SRI'),
('Internal', 'Additional', '*', 1, NULL, NULL, '*', '9010', 1, 1, 'SRI'),
('Internal', 'Additional', '*', 1, NULL, NULL, '*', '2101', -1, 1, 'SRI'),
('Internal', 'Labour and Additional', '*', 1, NULL, NULL, '*', '9010', 1, 1, 'SRI'),
('Internal', 'Labour and Additional', '*', 1, NULL, NULL, '*', '9020I', -1, 1, 'SRI'),
('Internal', 'Labour', '*', 1, NULL, NULL, '*', '9010', 1, 1, 'SRI'),
('Internal', 'Labour', '*', 1, NULL, NULL, '*', '9020I', -1, 1, 'SRI'),
('Internal', 'Additional', '*', 1, NULL, NULL, '*', '9010', 1, 1, 'SRI'),
('Internal', 'Additional', '*', 1, NULL, NULL, '*', '9020I', -1, 1, 'SRI'),
('Internal', 'Labour and Additional', 'SE', 0, 1, NULL, '*', '9010', 1, 0, 'SRI'),
('Internal', 'Labour and Additional', 'SE', 0, 1, NULL, '*', '9020B', -1, 0, 'SRI'),
('Internal', 'Labour', 'SE', 0, 1, NULL, '*', '9010', 1, 0, 'SRI'),
('Internal', 'Labour', 'SE', 0, 1, NULL, '*', '9020B', -1, 0, 'SRI'),
('Internal', 'Additional', 'SE', 0, 1, NULL, '*', '9010', 1, 0, 'SRI'),
('Internal', 'Additional', 'SE', 0, 1, NULL, '*', '9020B', -1, 0, 'SRI'),
('Internal', 'Labour and Additional', 'SE', 1, 1, NULL, '*', '9010', 1, 0, 'SRI'),
('Internal', 'Labour and Additional', 'SE', 1, 1, NULL, '*', '9020B', -1, 0, 'SRI'),
('Internal', 'Labour', 'SE', 1, 1, NULL, '*', '9010', 1, 0, 'SRI'),
('Internal', 'Labour', 'SE', 1, 1, NULL, '*', '9020B', -1, 0, 'SRI'),
('Internal', 'Additional', 'SE', 1, 1, NULL, '*', '9010', 1, 0, 'SRI'),
('Internal', 'Additional', 'SE', 1, 1, NULL, '*', '9020B', -1, 0, 'SRI'),
('Internal', 'Labour and Additional', 'SI', 0, 1, NULL, '*', '9010', 1, 0, 'SRI'),
('Internal', 'Labour and Additional', 'SI', 0, 1, NULL, '*', '9020B', -1, 0, 'SRI'),
('Internal', 'Labour', 'SI', 0, 1, NULL, '*', '9010', 1, 0, 'SRI'),
('Internal', 'Labour', 'SI', 0, 1, NULL, '*', '9020B', -1, 0, 'SRI'),
('Internal', 'Additional', 'SI', 0, 1, NULL, '*', '9010', 1, 0, 'SRI'),
('Internal', 'Additional', 'SI', 0, 1, NULL, '*', '9020B', -1, 0, 'SRI'),
('Internal', 'Labour and Additional', 'SI', 1, 1, NULL, '*', '9010', 1, 0, 'SRI'),
('Internal', 'Labour and Additional', 'SI', 1, 1, NULL, '*', '9020B', -1, 0, 'SRI'),
('Internal', 'Labour', 'SI', 1, 1, NULL, '*', '9010', 1, 0, 'SRI'),
('Internal', 'Labour', 'SI', 1, 1, NULL, '*', '9020B', -1, 0, 'SRI'),
('Internal', 'Additional', 'SI', 1, 1, NULL, '*', '9010', 1, 0, 'SRI'),
('Internal', 'Additional', 'SI', 1, 1, NULL, '*', '9020B', -1, 0, 'SRI'),
('Internal', 'Parts Cosacs', '*', 0, NULL, NULL, '*', '9010', 1, 0, 'SRI'),
('Internal', 'Parts Cosacs', '*', 0, NULL, NULL, '*', '9020I', -1, 0, 'SRI'),
('Internal', 'Parts Cosacs', '*', 1, NULL, NULL, '*', '9010', 1, 0, 'SRI'),
('Internal', 'Parts Cosacs', '*', 1, NULL, NULL, '*', '9020I', -1, 0, 'SRI'),
('Internal', 'Parts External', '*', 0, NULL, NULL, '*', '9010', 1, 0, 'SRI'),
('Internal', 'Parts External', '*', 0, NULL, NULL, '*', '9020I', -1, 0, 'SRI'),
('Internal', 'Parts External', '*', 1, NULL, NULL, '*', '9010', 1, 1, 'SRI'),
('Internal', 'Parts External', '*', 1, NULL, NULL, '*', '9020I', -1, 1, 'SRI'),
('Internal', 'Parts Salvaged', '*', 0, NULL, NULL, '*', '9010', 1, 1, 'SRI'),
('Internal', 'Parts Salvaged', '*', 0, NULL, NULL, '*', '9020I', -1, 1, 'SRI'),
('Internal', 'Parts Salvaged', '*', 0, NULL, NULL, '*', '9011', 1, 0, 'SRI'),
('Internal', 'Parts Salvaged', '*', 0, NULL, NULL, '*', '9010', -1, 0, 'SRI'),
('Internal', 'Parts Salvaged', '*', 1, NULL, NULL, '*', '9010', 1, 1, 'SRI'),
('Internal', 'Parts Salvaged', '*', 1, NULL, NULL, '*', '9020I', -1, 1, 'SRI'),
('Internal', 'Parts Salvaged', '*', 1, NULL, NULL, '*', '9011', 1, 0, 'SRI'),
('Internal', 'Parts Salvaged', '*', 1, NULL, NULL, '*', '9010', -1, 0, 'SRI'),
('Installation Charge Electrical', '*', '*', NULL, NULL, NULL, '*', '6093', 1, 1, 'INE'),
('Installation Charge Electrical', '*', '*', NULL, NULL, 1, '*', '5293', -1, 1, 'INE'),
('Installation Charge Electrical', '*', '*', NULL, NULL, 0, '*', '5193', -1, 1, 'INE'),
('Installation Charge Electrical', 'Labour and Additional', '*', 1, NULL, NULL, '*', '6093', 1, 1, 'INE'),
('Installation Charge Electrical', 'Labour and Additional', '*', 1, NULL, NULL, '*', '2101', -1, 1, 'INE'),
('Installation Charge Electrical', 'Labour', '*', 1, NULL, NULL, '*', '6093', 1, 1, 'INE'),
('Installation Charge Electrical', 'Labour', '*', 1, NULL, NULL, '*', '2101', -1, 1, 'INE'),
('Installation Charge Electrical', 'Additional', '*', 1, NULL, NULL, '*', '6093', 1, 1, 'INE'),
('Installation Charge Electrical', 'Additional', '*', 1, NULL, NULL, '*', '2101', -1, 1, 'INE'),
('Installation Charge Electrical', 'Parts External', '*', 1, NULL, NULL, '*', '9011', 1, 1, 'INE'),
('Installation Charge Electrical', 'Parts External', '*', 1, NULL, NULL, '*', '2101', -1, 1, 'INE'),
('Installation Charge Electrical', 'Parts Salvaged', '*', NULL, NULL, NULL, '*', '9011', 1, 1, 'INE'),
('Installation Charge Electrical', 'Parts Salvaged', '*', NULL, NULL, NULL, '*', '2930', -1, 1, 'INE'),
('Customer', 'Labour and Additional', 'IE', NULL, NULL, NULL, 'Electrical', '6093', 1, 1, 'INE'),
('Customer', 'Labour and Additional', 'IE', NULL, NULL, NULL, 'Electrical', '5293', -1, 1, 'INE'),
('Customer', 'Labour', 'IE', NULL, NULL, NULL, 'Electrical', '6093', 1, 1, 'INE'),
('Customer', 'Labour', 'IE', NULL, NULL, NULL, 'Electrical', '5293', -1, 1, 'INE'),
('Customer', 'Additional', 'IE', NULL, NULL, NULL, 'Electrical', '6093', 1, 1, 'INE'),
('Customer', 'Additional', 'IE', NULL, NULL, NULL, 'Electrical', '5293', -1, 1, 'INE'),
('Customer', 'Labour and Additional', 'IE', NULL, NULL, NULL, 'Furniture', '6093', 1, 1, 'INF'),
('Customer', 'Labour and Additional', 'IE', NULL, NULL, NULL, 'Furniture', '5292', -1, 1, 'INF'),
('Customer', 'Labour', 'IE', NULL, NULL, NULL, 'Furniture', '6093', 1, 1, 'INF'),
('Customer', 'Labour', 'IE', NULL, NULL, NULL, 'Furniture', '5292', -1, 1, 'INF'),
('Customer', 'Additional', 'IE', NULL, NULL, NULL, 'Furniture', '6093', 1, 1, 'INF'),
('Customer', 'Additional', 'IE', NULL, NULL, NULL, 'Furniture', '5292', -1, 1, 'INF'),
('Customer', 'Labour and Additional', 'IE', 1, NULL, NULL, 'Electrical', '6093', 1, 0, 'INE'),
('Customer', 'Labour and Additional', 'IE', 1, NULL, NULL, 'Electrical', '2101', -1, 0, 'INE'),
('Customer', 'Labour', 'IE', 1, NULL, NULL, 'Electrical', '6093', 1, 0, 'INE'),
('Customer', 'Labour', 'IE', 1, NULL, NULL, 'Electrical', '2101', -1, 0, 'INE'),
('Customer', 'Additional', 'IE', 1, NULL, NULL, 'Electrical', '6093', 1, 0, 'INE'),
('Customer', 'Additional', 'IE', 1, NULL, NULL, 'Electrical', '2101', -1, 0, 'INE'),
('Customer', 'Labour and Additional', 'IE', 1, NULL, NULL, 'Furniture', '6093', 1, 0, 'INF'),
('Customer', 'Labour and Additional', 'IE', 1, NULL, NULL, 'Furniture', '2101', -1, 0, 'INF'),
('Customer', 'Labour', 'IE', 1, NULL, NULL, 'Furniture', '6093', 1, 0, 'INF'),
('Customer', 'Labour', 'IE', 1, NULL, NULL, 'Furniture', '2101', -1, 0, 'INF'),
('Customer', 'Additional', 'IE', 1, NULL, NULL, 'Furniture', '6093', 1, 0, 'INF'),
('Customer', 'Additional', 'IE', 1, NULL, NULL, 'Furniture', '2101', -1, 0, 'INF'),
('Customer', 'Parts External', 'IE', 1, NULL, NULL, 'Electrical', '9011', 1, 0, 'INE'),
('Customer', 'Parts External', 'IE', 1, NULL, NULL, 'Electrical', '2101', -1, 0, 'INE'),
('Customer', 'Parts External', 'IE', 1, NULL, NULL, 'Furniture', '9011', 1, 0, 'INF'),
('Customer', 'Parts External', 'IE', 1, NULL, NULL, 'Furniture', '2101', -1, 0, 'INF'),
('Customer', 'Parts External', 'IE', NULL, NULL, NULL, 'Electrical', '6093', 1, 1, 'INE'),
('Customer', 'Parts External', 'IE', NULL, NULL, NULL, 'Electrical', '5293', -1, 1, 'INE'),
('Customer', 'Parts External', 'IE', NULL, NULL, NULL, 'Furniture', '6093', 1, 1, 'INF'),
('Customer', 'Parts External', 'IE', NULL, NULL, NULL, 'Furniture', '5292', -1, 1, 'INF'),
('Customer', 'Parts Cosacs', 'IE', NULL, NULL, NULL, 'Electrical', '6093', 1, 1, 'INE'),
('Customer', 'Parts Cosacs', 'IE', NULL, NULL, NULL, 'Electrical', '5293', -1, 1, 'INE'),
('Customer', 'Parts Cosacs', 'IE', NULL, NULL, NULL, 'Furniture', '6093', 1, 1, 'INF'),
('Customer', 'Parts Cosacs', 'IE', NULL, NULL, NULL, 'Furniture', '5292', -1, 1, 'INF'),
('Customer', 'Parts Salvaged', 'IE', NULL, NULL, NULL, 'Electrical', '6093', 1, 1, 'INE'),
('Customer', 'Parts Salvaged', 'IE', NULL, NULL, NULL, 'Electrical', '5293', -1, 1, 'INE'),
('Customer', 'Parts Salvaged', 'IE', NULL, NULL, NULL, 'Furniture', '6093', 1, 1, 'INF'),
('Customer', 'Parts Salvaged', 'IE', NULL, NULL, NULL, 'Furniture', '5292', -1, 1, 'INF'),
('Installation Charge Furniture', '*', '*', NULL, NULL, NULL, '*', '6093', 1, 1, 'INF'),
('Installation Charge Furniture', '*', '*', NULL, NULL, 1, '*', '5292', -1, 1, 'INF'),
('Installation Charge Furniture', '*', '*', NULL, NULL, 0, '*', '5192', -1, 1, 'INF'),
('Installation Charge Furniture', 'Labour and Additional', '*', 1, NULL, NULL, '*', '6093', 1, 1, 'INF'),
('Installation Charge Furniture', 'Labour and Additional', '*', 1, NULL, NULL, '*', '2101', -1, 1, 'INF'),
('Installation Charge Furniture', 'Labour', '*', 1, NULL, NULL, '*', '6093', 1, 1, 'INF'),
('Installation Charge Furniture', 'Labour', '*', 1, NULL, NULL, '*', '2101', -1, 1, 'INF'),
('Installation Charge Furniture', 'Additional', '*', 1, NULL, NULL, '*', '6093', 1, 1, 'INF'),
('Installation Charge Furniture', 'Additional', '*', 1, NULL, NULL, '*', '2101', -1, 1, 'INF'),
('Installation Charge Furniture', 'Parts External', '*', 1, NULL, NULL, '*', '9011', 1, 1, 'INF'),
('Installation Charge Furniture', 'Parts External', '*', 1, NULL, NULL, '*', '2101', -1, 1, 'INF'),
('Installation Charge Furniture', 'Parts Salvaged', '*', NULL, NULL, NULL, '*', '9011', 1, 1, 'INF'),
('Installation Charge Furniture', 'Parts Salvaged', '*', NULL, NULL, NULL, '*', '2930', -1, 1, 'INF')
go