-- transaction: true
-- Change the previous line to false to disable running this whole migration in one transaction.
-- Removing that first line will default to 'true'.
-- 
-- Put your SQL code here
IF OBJECT_ID('Financial.TransactionMapping') IS NOT NULL
	DROP TABLE Financial.TransactionMapping
GO
CREATE TABLE Financial.TransactionMapping
(
	Id				TinyInt IDENTITY (1, 1) NOT NULL,
	ChargeType		VarChar(64)				NOT NULL,
	Label			VarChar(64)				NOT NULL, 
	ServiceType		VarChar(32)				NOT NULL,
	IsExternal		Bit						NOT NULL,
	Replacement		Bit						NULL,

	Account			VarChar(35)				NOT NULL,
	Percentage		Decimal(3, 2)			NOT NULL,
	UseValueColumn	Bit						NOT NULL,
	TransactionType	Char(3)					NOT NULL
)
GO

ALTER TABLE Financial.TransactionMapping ADD  CONSTRAINT PK_TransactionMapping PRIMARY KEY CLUSTERED 
(
	Id ASC
)
GO

INSERT INTO Financial.TransactionMapping
	(ChargeType, Label, ServiceType, IsExternal, Replacement, Account, Percentage, UseValueColumn, TransactionType)
VALUES
	('Customer', 'Labour', '*', 1, NULL, '9010', 1, 0, 'PAY'),
	('Customer', 'Labour', '*', 1, NULL, '2101', -1, 0, 'PAY'),
	('Customer', 'Parts External', '*', 1, NULL, '9011', 1, 0, 'PAY'),
	('Customer', 'Parts External', '*', 1, NULL, '2101', -1, 0, 'PAY'),
	('Supplier', 'Labour and Additional', '*', 0, NULL, '1392', 1, 1, 'SRS'),
	('Supplier', 'Labour and Additional', '*', 0, NULL, '9020S', -1, 1, 'SRS'),
	('Supplier', 'Labour and Additional', '*', 1, NULL, '1392', 1, 0, 'SRS'),
	('Supplier', 'Labour and Additional', '*', 1, NULL, '9020S', -1, 0, 'SRS'),
	('Supplier', 'Labour and Additional', '*', 1, NULL, '9010', 1, 0, 'SRS'),
	('Supplier', 'Labour and Additional', '*', 1, NULL, '2101', -1, 0, 'SRS'),
	('Supplier', 'Parts Cosacs', '*', 0, NULL, '1392', 1, 1, 'SRS'),
	('Supplier', 'Parts Cosacs', '*', 0, NULL, '9020S', -1, 1, 'SRS'),
	('Supplier', 'Parts Cosacs', '*', 1, NULL, '1392', -1, 0, 'SRS'),
	('Supplier', 'Parts Cosacs', '*', 1, NULL, '9020S', 1, 0, 'SRS'),
	('Supplier', 'Parts Other', '*', 0, NULL, '1392', 1, 1, 'SRS'),
	('Supplier', 'Parts Other', '*', 0, NULL, '9020S', -1, 1, 'SRS'),
	('Supplier', 'Parts External', '*', 1, NULL, '1392', 1, 1, 'SRS'),
	('Supplier', 'Parts External', '*', 1, NULL, '9020S', -1, 1, 'SRS'),
	('Supplier', 'Parts External', '*', 1, NULL, '9011', 1, 0, 'SRS'),
	('Supplier', 'Parts External', '*', 1, NULL, '2101', -1, 0, 'SRS'),
	('Supplier', 'Parts Salvaged', '*', 0, NULL, '1392', 1, 1, 'SRS'),
	('Supplier', 'Parts Salvaged', '*', 0, NULL, '9020S', -1, 1, 'SRS'),
	('Supplier', 'Parts Salvaged', '*', 0, NULL, '9011', 1, 0, 'SRS'),
	('Supplier', 'Parts Salvaged', '*', 0, NULL, '2930', -1, 0, 'SRS'),
	('Supplier', 'Parts Salvaged', '*', 1, NULL, '1392', 1, 1, 'SRS'),
	('Supplier', 'Parts Salvaged', '*', 1, NULL, '9020S', -1, 1, 'SRS'),
	('Supplier', 'Parts Salvaged', '*', 1, NULL, '9011', 1, 0, 'SRS'),
	('Supplier', 'Parts Salvaged', '*', 1, NULL, '2930', -1, 0, 'SRS'),
	('FYW', 'Labour and Additional', '*', 1, NULL, '9010', 1, 0, 'SRY'),
	('FYW', 'Labour and Additional', '*', 1, NULL, '2101', -1, 0, 'SRY'),
	('FYW', 'Labour and Additional', '*', 1, NULL, '2930', 1, 1, 'SRY'),
	('FYW', 'Labour and Additional', '*', 1, NULL, '9020I', -1, 1, 'SRY'),
	('FYW', 'Labour and Additional', '*', 0, NULL, '2930', 1, 1, 'SRY'),
	('FYW', 'Labour and Additional', '*', 0, NULL, '9020I', -1, 1, 'SRY'),
	('FYW', 'Parts Salvaged', '*', 0, NULL, '2930', 1, 1, 'SRY'),
	('FYW', 'Parts Salvaged', '*', 0, NULL, '9020I', -1, 1, 'SRY'),
	('FYW', 'Parts Salvaged', '*', 0, NULL, '9011', 1, 0, 'SRY'),
	('FYW', 'Parts Salvaged', '*', 0, NULL, '2930', -1, 0, 'SRY'),
	('FYW', 'Parts Salvaged', '*', 1, NULL, '2930', 1, 1, 'SRY'),
	('FYW', 'Parts Salvaged', '*', 1, NULL, '9020I', -1, 1, 'SRY'),
	('FYW', 'Parts Salvaged', '*', 1, NULL, '9011', 1, 0, 'SRY'),
	('FYW', 'Parts Salvaged', '*', 1, NULL, '2930', -1, 0, 'SRY'),
	('FYW', 'Parts Cosacs', '*', 0, NULL, '2930', 1, 1, 'SRY'),
	('FYW', 'Parts Cosacs', '*', 0, NULL, '9020I', -1, 1, 'SRY'),
	('FYW', 'Parts Cosacs', '*', 1, NULL, '2930', 1, 1, 'SRY'),
	('FYW', 'Parts Cosacs', '*', 1, NULL, '9020I', -1, 1, 'SRY'),
	('FYW', 'Parts External', '*', 1, NULL, '2930', 1, 1, 'SRY'),
	('FYW', 'Parts External', '*', 1, NULL, '9020I', -1, 1, 'SRY'),
	('FYW', 'Parts External', '*', 1, NULL, '9011', 1, 0, 'SRY'),
	('FYW', 'Parts External', '*', 1, NULL, '2101', -1, 0, 'SRY'),
	('EW', 'Labour and Additional', '*', 0, NULL, '2910', 1, 1, 'SRW'),
	('EW', 'Labour and Additional', '*', 0, NULL, '9020E', -1, 1, 'SRW'),
	('EW', 'Labour and Additional', '*', 1, NULL, '9010', 1, 0, 'SRW'),
	('EW', 'Labour and Additional', '*', 1, NULL, '2101', -1, 0, 'SRW'),
	('EW', 'Labour and Additional', '*', 1, NULL, '2910', 1, 1, 'SRW'),
	('EW', 'Labour and Additional', '*', 1, NULL, '9020E', -1, 1, 'SRW'),
	('EW', 'Parts Cosacs', '*', 0, NULL, '2910', 1, 1, 'SRW'),
	('EW', 'Parts Cosacs', '*', 0, NULL, '9020E', -1, 1, 'SRW'),
	('EW', 'Parts Cosacs', '*', 1, NULL, '2910', 1, 1, 'SRW'),
	('EW', 'Parts Cosacs', '*', 1, NULL, '9020E', -1, 1, 'SRW'),
	('EW', 'Parts External', '*', 1, NULL, '2910', 1, 1, 'SRW'),
	('EW', 'Parts External', '*', 1, NULL, '9020E', -1, 1, 'SRW'),
	('EW', 'Parts External', '*', 1, NULL, '9011', 1, 0, 'SRW'),
	('EW', 'Parts External', '*', 1, NULL, '2101', -1, 0, 'SRW'),
	('EW', 'Parts Salvaged', '*', 0, NULL, '2910', 1, 1, 'SRW'),
	('EW', 'Parts Salvaged', '*', 0, NULL, '9020E', -1, 1, 'SRW'),
	('EW', 'Parts Salvaged', '*', 0, NULL, '9011', 1, 0, 'SRW'),
	('EW', 'Parts Salvaged', '*', 0, NULL, '2910', -1, 0, 'SRW'),
	('EW', 'Parts Salvaged', '*', 1, NULL, '2910', 1, 1, 'SRW'),
	('EW', 'Parts Salvaged', '*', 1, NULL, '9020E', -1, 1, 'SRW'),
	('EW', 'Parts Salvaged', '*', 1, NULL, '9011', 1, 0, 'SRW'),
	('EW', 'Parts Salvaged', '*', 1, NULL, '2910', -1, 0, 'SRW'),
	('Internal', 'Labour and Additional', 'S', 0, NULL, '9010', 1, 0, 'SRI'),
	('Internal', 'Labour and Additional', 'S', 0, NULL, '9020B', -1, 0, 'SRI'),
	('Internal', 'Labour and Additional', 'S', 1, NULL, '9010', 1, 0, 'SRI'),
	('Internal', 'Labour and Additional', 'S', 1, NULL, '9020B', -1, 0, 'SRI'),
	('Internal', 'Labour and Additional', '*', 1, NULL, '9010', 1, 1, 'SRI'),
	('Internal', 'Labour and Additional', '*', 1, NULL, '2101', -1, 1, 'SRI'),
	('Internal', 'Labour and Additional', 'SE', 0, 1, '9010', 1, 0, 'SRI'),
	('Internal', 'Labour and Additional', 'SE', 0, 1, '9020B', -1, 0, 'SRI'),
	('Internal', 'Labour and Additional', 'SE', 1, 1, '9010', 1, 0, 'SRI'),
	('Internal', 'Labour and Additional', 'SE', 1, 1, '9020B', -1, 0, 'SRI'),
	('Internal', 'Labour and Additional', 'SI', 0, 1, '9010', 1, 0, 'SRI'),
	('Internal', 'Labour and Additional', 'SI', 0, 1, '9020B', -1, 0, 'SRI'),
	('Internal', 'Labour and Additional', 'SI', 1, 1, '9010', 1, 0, 'SRI'),
	('Internal', 'Labour and Additional', 'SI', 1, 1, '9020B', -1, 0, 'SRI'),
	('Internal', 'Parts Cosacs', '*', 0, NULL, '9010', 1, 0, 'SRI'),
	('Internal', 'Parts Cosacs', '*', 0, NULL, '9020I', -1, 0, 'SRI'),
	('Internal', 'Parts Cosacs', '*', 1, NULL, '9010', 1, 0, 'SRI'),
	('Internal', 'Parts Cosacs', '*', 1, NULL, '9020I', -1, 0, 'SRI'),
	('Internal', 'Parts Other', '*', 0, NULL, '9010', 1, 0, 'SRI'),
	('Internal', 'Parts Other', '*', 0, NULL, '9020I', -1, 0, 'SRI'),
	('Internal', 'Parts External', '*', 1, NULL, '9010', 1, 1, 'SRI'),
	('Internal', 'Parts External', '*', 1, NULL, '9020I', -1, 1, 'SRI'),
	('Internal', 'Parts Salvaged', '*', 0, NULL, '9010', 1, 1, 'SRI'),
	('Internal', 'Parts Salvaged', '*', 0, NULL, '9020I', -1, 1, 'SRI'),
	('Internal', 'Parts Salvaged', '*', 0, NULL, '9011', 1, 0, 'SRI'),
	('Internal', 'Parts Salvaged', '*', 0, NULL, '9010', -1, 0, 'SRI'),
	('Internal', 'Parts Salvaged', '*', 1, NULL, '9010', 1, 1, 'SRI'),
	('Internal', 'Parts Salvaged', '*', 1, NULL, '9020I', -1, 1, 'SRI'),
	('Internal', 'Parts Salvaged', '*', 1, NULL, '9011', 1, 0, 'SRI'),
	('Internal', 'Parts Salvaged', '*', 1, NULL, '9010', -1, 0, 'SRI')
