insert into Config.DecisionTableType
values ('SR.DecisionTable.ChargeToAuthorisation')

INSERT INTO Config.DecisionTable
        ( [Key], CreatedUtc, Value )
VALUES  ( 'SR.DecisionTable.ChargeToAuthorisation', -- Key - varchar(50)
Getdate(), -- CreatedUtc - datetime
'{
  "conditions": [
    {
      "expression": "this.serviceRequest.Resolution"
    },
    {
      "expression": "\"Inside Supplier Warranty\" &&\nresolutionValidForWarranty(this.serviceRequest.Resolution) &&\ninsideWarranty(this.serviceRequest, this.serviceRequest.ManWarrantyLength || 12)"
    },
    {
      "expression": "\"Inside Extended Warranty\" &&\nresolutionValidForWarranty(this.serviceRequest.Resolution) &&\nthis.serviceRequest.WarrantyContractId &&\ninsideWarranty(this.serviceRequest, this.serviceRequest.WarrantyLength || 0)"
    },
    {
      "expression": "validSRType(this.serviceRequest.Type)"
    }
  ],
  "actions": [
    {
      "expression": "chargeTos(this, [{\n\tkey: ''Customer'',\n\tauthorisationRequired: false\n}, {\n\tkey: ''Deliverer'',\n\tauthorisationRequired: false\n}, {\n\tkey: ''FYW'',\n\tauthorisationRequired: false\n}, {\n\tkey: ''Internal'',\n\tauthorisationRequired: false\n}, {\n\tkey: ''Supplier'',\n\tauthorisationRequired: true\n}]);"
    },
    {
      "expression": "chargeTos(this, [{\n\tkey: ''Customer'',\n\tauthorisationRequired: false\n}, {\n\tkey: ''Deliverer'',\n\tauthorisationRequired: false\n}, {\n\tkey: ''FYW'',\n\tauthorisationRequired: false\n}, {\n\tkey: ''Internal'',\n\tauthorisationRequired: false\n}, {\n\tkey: ''Supplier'',\n\tauthorisationRequired: false\n}]);\n\nthis.serviceRequest.ResolutionPrimaryCharge = ''Deliverer'';"
    },
    {
      "expression": "chargeTos(this, [{\n\tkey: ''Customer'',\n\tauthorisationRequired: false\n}, {\n\tkey: ''Deliverer'',\n\tauthorisationRequired: false\n}, {\n\tkey: ''FYW'',\n\tauthorisationRequired: false\n}, {\n\tkey: ''Internal'',\n\tauthorisationRequired: false\n}, {\n\tkey: ''Supplier'',\n\tauthorisationRequired: false\n}]);\n\nthis.serviceRequest.ResolutionPrimaryCharge = ''Internal'';"
    },
    {
      "expression": "chargeTos(this, [{\n\tkey: ''Customer'',\n\tauthorisationRequired: false\n}, {\n\tkey: ''Deliverer'',\n\tauthorisationRequired: false\n}, {\n\tkey: ''FYW'',\n\tauthorisationRequired: false\n}, {\n\tkey: ''Internal'',\n\tauthorisationRequired: false\n}, {\n\tkey: ''Supplier'',\n\tauthorisationRequired: true\n}]);\n\nthis.serviceRequest.ResolutionPrimaryCharge = ''Customer'';"
    },
    {
      "expression": "chargeTos(this, [{\n\tkey: ''Customer'',\n\tauthorisationRequired: false\n}, {\n\tkey: ''Deliverer'',\n\tauthorisationRequired: false\n}, {\n\tkey: ''FYW'',\n\tauthorisationRequired: false\n}, {\n\tkey: ''Internal'',\n\tauthorisationRequired: false\n}, {\n\tkey: ''Supplier'',\n\tauthorisationRequired: true\n}]);\n\nthis.serviceRequest.ResolutionPrimaryCharge = ''Supplier'';"
    },
    {
      "expression": "chargeTos(this, [{\n\tkey: ''Customer'',\n\tauthorisationRequired: false\n}, {\n\tkey: ''Deliverer'',\n\tauthorisationRequired: false\n}, {\n\tkey: ''EW'',\n\tauthorisationRequired: false\n}, {\n\tkey: ''FYW'',\n\tauthorisationRequired: false\n}, {\n\tkey: ''Internal'',\n\tauthorisationRequired: false\n}, {\n\tkey: ''Supplier'',\n\tauthorisationRequired: false\n}]);\n\nthis.serviceRequest.ResolutionPrimaryCharge = ''EW'';"
    }
  ],
  "rules": [
    {
      "values": [
        "",
        null,
        null,
        "true"
      ],
      "actions": [
        true,
        false,
        false,
        false,
        false,
        false
      ]
    },
    {
      "values": [
        "Damage On Delivery",
        null,
        null,
        "true"
      ],
      "actions": [
        false,
        true,
        false,
        false,
        false,
        false
      ]
    },
    {
      "values": [
        "Beyond Economic Repair",
        null,
        null,
        "true"
      ],
      "actions": [
        false,
        false,
        true,
        false,
        false,
        false
      ]
    },
    {
      "values": [
        "Misuse by the customer",
        null,
        null,
        "true"
      ],
      "actions": [
        false,
        false,
        false,
        true,
        false,
        false
      ]
    },
    {
      "values": [
        "Event or terms NOT covered",
        null,
        null,
        "true"
      ],
      "actions": [
        false,
        false,
        false,
        true,
        false,
        false
      ]
    },
    {
      "values": [
        null,
        "true",
        "",
        "true"
      ],
      "actions": [
        false,
        false,
        false,
        false,
        true,
        false
      ]
    },
    {
      "values": [
        null,
        "false",
        "true",
        "true"
      ],
      "actions": [
        false,
        false,
        false,
        false,
        false,
        true
      ]
    }
  ],
  "extensions": "var addMonths = function (d, months) {\n  d = new Date(+d);\n  d.setMonth(d.getMonth() + months);\n  return d;\n};\n\nvar insideWarranty = function (sr, months) {\n  return addMonths(sr.ItemDeliveredOn, months) >= new Date();\n};\n\nvar chargeTos = function(scope, list) {\n scope.MasterData.ServiceChargeTos = list;\n};\n\nvar resolutionValidForWarranty = function (resolution) {\n  return resolution !== ''Damage On Delivery'' && resolution !== ''Beyond Economic Repair'' && resolution !== ''Misuse by the customer'' && resolution !== ''Event or terms NOT covered'';\n};\n\nvar validSRType = function (srType) {\n  return srType === ''SI'' || srType === ''SE'' || srType === ''S''\n};"
}')


INSERT INTO Config.DecisionTable
        ( [Key], CreatedUtc, Value )
VALUES  ( 'SR.DecisionTable.Workflow', -- Key - varchar(50)
Getdate(), -- CreatedUtc - datetime
'{
  "conditions": [
    {
      "expression": "this.srType"
    },
    {
      "expression": "this.serviceRequest.Type"
    },
    {
      "expression": "!isEmpty(this.serviceRequest.WarrantyContractNumber)"
    },
    {
      "expression": "((new Date(+this.serviceRequest.ItemSoldOn +\n (new Date((365.25/12)*(24*3600*1000)) *\n (this.serviceRequest.WarrantyLength || 0) ))) >= (new Date()))"
    },
    {
      "expression": "this.serviceRequest.Id === 0"
    },
    {
      "expression": "this.CustomerSearch.Type === ''Invoice''"
    },
    {
      "expression": "this.serviceRequest.ResolutionPrimaryCharge"
    },
    {
      "expression": "this.serviceRequest.ResolutionPrimaryCharge === ''Deliverer'' || this.serviceRequest.ResolutionPrimaryCharge === ''Supplier''"
    },
    {
      "expression": "(this.serviceRequest.ResolutionPrimaryCharge === ''Deliverer'' || this.serviceRequest.ResolutionPrimaryCharge === ''Customer'') &&  this.OutstandingBalance > 0"
    },
    {
      "expression": "this.isItemBer"
    },
    {
      "expression": "this.serviceRequest.ServiceEvaluation"
    }
  ],
  "actions": [
    {
      "expression": "this.MasterData.ServiceEvaluation = [''No Fault Found'',''Misuse by the Customer'',''Event or Terms Not Covered'',''Warranty Covered'']"
    },
    {
      "expression": "this.sections.pageHeading.visible = false"
    },
    {
      "expression": "this.sections.searchSelectorInput.visible = true"
    },
    {
      "expression": "this.sections.searchSelectorInput.visible = false"
    },
    {
      "expression": "this.sections.customer.visible = true"
    },
    {
      "expression": "this.sections.customer.visible = false"
    },
    {
      "expression": "this.sections.evaluation.visible = true"
    },
    {
      "expression": "this.sections.evaluation.visible = false"
    },
    {
      "expression": "this.sections.estimate.visible = true"
    },
    {
      "expression": "this.sections.estimate.visible = false"
    },
    {
      "expression": "this.sections.product.enabled = true"
    },
    {
      "expression": "this.sections.product.enabled = false"
    },
    {
      "expression": "this.sections.product.stockLocationVisible = true"
    },
    {
      "expression": "this.sections.product.stockLocationVisible = false"
    },
    {
      "expression": "this.sections.warranty.visible = true"
    },
    {
      "expression": "this.sections.warranty.visible = false"
    },
    {
      "expression": "this.sections.showPrintInvoice.visible = true"
    },
    {
      "expression": "this.sections.showPrintInvoice.visible = false"
    },
    {
      "expression": "this.sections.foodLoss.visible = true"
    },
    {
      "expression": "this.sections.foodLoss.visible = false"
    },
    {
      "expression": "this.sections.customerDetail.visible = true"
    },
    {
      "expression": "this.sections.customerDetail.visible = false"
    },
    {
      "expression": "this.sections.outOfWarrantyCoverMessage.visible = true"
    },
    {
      "expression": "this.sections.outOfWarrantyCoverMessage.visible = false"
    },
    {
      "expression": "this.sections.formReferenceField.visible = true"
    },
    {
      "expression": "this.sections.formReferenceField.visible = false"
    },
    {
      "expression": "this.sections.branchSearch.visible = true"
    },
    {
      "expression": "this.sections.branchSearch.visible = false"
    },
    {
      "expression": "this.sections.payment.visible = true"
    },
    {
      "expression": "this.sections.payment.visible = false"
    },
    {
      "expression": "this.sections.resolutionSection.supplierVisible = true;\nthis.sections.resolutionSection.delivererVisible = false;\nthis.sections.resolutionSection.productVisible = true;"
    },
    {
      "expression": "this.sections.resolutionSection.delivererVisible = true;\nthis.sections.resolutionSection.supplierVisible = false;\nthis.sections.resolutionSection.productVisible = false;"
    },
    {
      "expression": "this.sections.resolutionSection.supplierVisible = false;\nthis.sections.resolutionSection.delivererVisible = false;\nthis.sections.resolutionSection.productVisible = false;"
    },
    {
      "expression": "chargeTos(this, [''Customer'',''Installation Charge Furniture'',''Installation Charge Electrical'']);"
    },
    {
      "expression": "this.sections.product.serviceRetailerVisible = true"
    },
    {
      "expression": "this.sections.finalise.itemReplacedVisible = true;"
    },
    {
      "expression": "this.ServiceResolutions = [''No Fault Found''];\nthis.serviceRequest.Resolution = this.ServiceResolutions[0];\nthis.serviceRequest.ResolutionDate = new Date;"
    },
    {
      "expression": "this.ServiceResolutions = this.MasterData.ServiceResolutions;\nthis.serviceRequest.ResolutionDate = null;"
    },
    {
      "expression": "this.EvaluationRequired = true;"
    },
    {
      "expression": "this.EvaluationRequired = false;"
    }
  ],
  "rules": [
    {
      "values": [
        "SI",
        null,
        null,
        "",
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "actions": [
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ]
    },
    {
      "values": [
        "SE",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "actions": [
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ]
    },
    {
      "values": [
        "II",
        "",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "actions": [
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ]
    },
    {
      "values": [
        "IE",
        null,
        "",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "actions": [
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ]
    },
    {
      "values": [
        "S",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "actions": [
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ]
    },
    {
      "values": [
        "SI",
        "",
        "true",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "actions": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ]
    },
    {
      "values": [
        "SI",
        null,
        "",
        "true",
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "actions": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ]
    },
    {
      "values": [
        null,
        "SI",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "actions": [
        true,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ]
    },
    {
      "values": [
        null,
        "SE",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "actions": [
        true,
        false,
        false,
        true,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false
      ]
    },
    {
      "values": [
        null,
        "II",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "actions": [
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false
      ]
    },
    {
      "values": [
        null,
        "IE",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "actions": [
        false,
        false,
        false,
        true,
        true,
        false,
        false,
        true,
        false,
        true,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false
      ]
    },
    {
      "values": [
        null,
        "S",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "actions": [
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ]
    },
    {
      "values": [
        null,
        null,
        null,
        null,
        "true",
        null,
        null,
        null,
        null,
        null,
        null
      ],
      "actions": [
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ]
    },
    {
      "values": [
        null,
        null,
        null,
        null,
        null,
        "true",
        null,
        null,
        null,
        null,
        null
      ],
      "actions": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ]
    },
    {
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "true",
        null,
        null
      ],
      "actions": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ]
    },
    {
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "false",
        null,
        null
      ],
      "actions": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ]
    },
    {
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        "Deliverer",
        null,
        null,
        null,
        null
      ],
      "actions": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ]
    },
    {
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        "Supplier",
        null,
        null,
        null,
        null
      ],
      "actions": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ]
    },
    {
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "false",
        null,
        null,
        null
      ],
      "actions": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false
      ]
    },
    {
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "true",
        null
      ],
      "actions": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false,
        false
      ]
    },
    {
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "No Fault Found"
      ],
      "actions": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        true
      ]
    },
    {
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Misuse by the Customer"
      ],
      "actions": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        false
      ]
    },
    {
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Event or Terms Not Covered"
      ],
      "actions": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        true,
        false
      ]
    },
    {
      "values": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "Warranty Covered"
      ],
      "actions": [
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        true
      ]
    }
  ],
  "extensions": "var isEmpty = function(val) {\n    return _.isEmpty(val);\n};\n\nvar chargeTos = function(scope, list) {\n scope.MasterData.ServiceChargeTos = list;\n };"
}')