---- transaction: true
---- Change the previous line to false to disable running this whole migration in one transaction.
---- Removing that first line will default to 'true'.
---- 
---- Put your SQL code here
--SET QUOTED_IDENTIFIER ON
--SET ARITHABORT ON
--SET NUMERIC_ROUNDABORT OFF
--SET CONCAT_NULL_YIELDS_NULL ON
--SET ANSI_NULLS ON
--SET ANSI_PADDING ON
--SET ANSI_WARNINGS ON

--ALTER TABLE Sales.PaymentMethod ADD CONSTRAINT
--	FK_PaymentMethod_PaymentType FOREIGN KEY
--	(
--	PaymentTypeId
--	) REFERENCES Sales.PaymentType
--	(
--	Id
--	) ON UPDATE  NO ACTION 
--	 ON DELETE  NO ACTION 
	
