-- transaction: true
-- Change the previous line to false to disable running this whole migration in one transaction.
-- Removing that first line will default to 'true'.
-- 
-- Put your SQL code here

UPDATE Merchandising.HierarchyTag SET Name = 'WASHING MACHINE AND DRYER' WHERE Code = '315'
UPDATE Merchandising.HierarchyTag SET Name = 'LAMINATES SOLID WOOD' WHERE Code = '92F'
UPDATE Merchandising.HierarchyTag SET Name = 'DINING SETS' WHERE Code = '72A'
UPDATE Merchandising.HierarchyTag SET Name = 'INFANTS' WHERE Code = 'D'
UPDATE Merchandising.HierarchyTag SET Name = 'REPOSSESSED GOODS' WHERE Code = '13'
UPDATE Merchandising.HierarchyTag SET Name = 'OPTICAL' WHERE Code = '2'
UPDATE Merchandising.HierarchyTag SET Name = 'TYRES' WHERE Code = '993'
UPDATE Merchandising.HierarchyTag SET Name = 'CELLPHONES AND ACCESSORIES' WHERE Code = '520'
UPDATE Merchandising.HierarchyTag SET Name = 'ACCESSORIES HARDWARE' WHERE Code = 'C01'
UPDATE Merchandising.HierarchyTag SET Name = 'AUDIO ACCESSORIES' WHERE Code = '11J'
UPDATE Merchandising.HierarchyTag SET Name = 'BEDDING ACCESSORIES' WHERE Code = '81A'
UPDATE Merchandising.HierarchyTag SET Name = 'BLANK MEDIA ACCESSORIES' WHERE Code = '55A'
UPDATE Merchandising.HierarchyTag SET Name = 'CAMERA ACCESSORIES' WHERE Code = 'B02'
UPDATE Merchandising.HierarchyTag SET Name = 'CAR AUDIO ACCESSORIES' WHERE Code = '12A'
UPDATE Merchandising.HierarchyTag SET Name = 'FLOORING ACCESSORIES' WHERE Code = '92E'
UPDATE Merchandising.HierarchyTag SET Name = 'FRIDGE ACCESSORIES' WHERE Code = '30K'
UPDATE Merchandising.HierarchyTag SET Name = 'GAMING ACCESSORIES' WHERE Code = '15A'
UPDATE Merchandising.HierarchyTag SET Name = 'LIGHTING ACCESSORIES' WHERE Code = '90C'
UPDATE Merchandising.HierarchyTag SET Name = 'MOBILE ACCESSORIES' WHERE Code = '52D'
UPDATE Merchandising.HierarchyTag SET Name = 'SECURITY ACCESSORIES' WHERE Code = 'B15'
UPDATE Merchandising.HierarchyTag SET Name = 'SEWING MACHINE ACCESSORIES' WHERE Code = '41D'
UPDATE Merchandising.HierarchyTag SET Name = 'STOVES ACCESSORIES' WHERE Code = '31P'
UPDATE Merchandising.HierarchyTag SET Name = 'VENTILATION AND HEATING ACCESSORIES' WHERE Code = '32M'
UPDATE Merchandising.HierarchyTag SET Name = 'VIDEO ACCESSORIES' WHERE Code = '10L'
UPDATE Merchandising.HierarchyTag SET Name = 'WASHING MACHINE AND DRYER ACCESSORIES' WHERE Code = '35H'
UPDATE Merchandising.HierarchyTag SET Name = 'CAMERAS' WHERE Code = '951'
UPDATE Merchandising.HierarchyTag SET Name = 'DINNERWARE' WHERE Code = '915'
UPDATE Merchandising.HierarchyTag SET Name = 'DINNERWARES' WHERE Code = '91D'
UPDATE Merchandising.HierarchyTag SET Name = 'CANDLEHOLDERS' WHERE Code = '95B'
UPDATE Merchandising.HierarchyTag SET Name = 'FITTED KITCHEN' WHERE Code = '73Q'
UPDATE Merchandising.HierarchyTag SET Name = 'DIGITAL PHOTO CAMERA' WHERE Code = 'B03'
UPDATE Merchandising.HierarchyTag SET Name = 'SLR CAMERAS' WHERE Code = 'B04'
UPDATE Merchandising.HierarchyTag SET Name = 'HOME THEATRE SYSTEMS' WHERE Code = '11C'
UPDATE Merchandising.HierarchyTag SET Name = 'LOUNGE FUTON SOFA BED' WHERE Code = '70F'
UPDATE Merchandising.HierarchyTag SET Name = 'MISCELLANEOUS TABLE AND CHAIR SET' WHERE Code = '71J'
UPDATE Merchandising.HierarchyTag SET Name = 'MOTORCYCLE ACCESSORIES' WHERE Code = 'A26'
UPDATE Merchandising.HierarchyTag SET Name = 'MOTORCYCLE PARTS' WHERE Code = 'A25'
UPDATE Merchandising.HierarchyTag SET Name = 'PROJECTORS' WHERE Code = '51F'
UPDATE Merchandising.HierarchyTag SET Name = 'WEARABLES ELECTRONICS' WHERE Code = 'B08'
UPDATE Merchandising.HierarchyTag SET Name = 'FURNITURE OCCASIONAL MISC' WHERE Code = '748'
UPDATE Merchandising.HierarchyTag SET Name = 'FRONT LOAD WASHING MACHINE' WHERE Code = '35C'
UPDATE Merchandising.HierarchyTag SET Name = 'COOKING UTENSILS AND GADGETS' WHERE Code = '91B'
UPDATE Merchandising.HierarchyTag SET Name = 'HEAD UNIT WITH TOUCH SCREEN' WHERE Code = '12E'
UPDATE Merchandising.HierarchyTag SET Name = 'COFFEE SHOP EQUIPMENT' WHERE Code = 'C05'
UPDATE Merchandising.HierarchyTag SET Name = 'COMPUTER AND ACCESSORIES' WHERE Code = '505'
UPDATE Merchandising.HierarchyTag SET Name = 'DECORATIVE ACCESSORIES' WHERE Code = '925'
UPDATE Merchandising.HierarchyTag SET Name = 'OPTICAL ACCESSORIES' WHERE Code = '234'