-- transaction: true
-- Change the previous line to false to disable running this whole migration in one transaction.
-- Removing that first line will default to 'true'.
-- 
-- Put your SQL code here

IF NOT EXISTS(SELECT 1 FROM [$Migration] m where m.Id = 20151124144059)
BEGIN 
	DECLARE @levelId int

	SELECT 	CONVERT(varchar(4) ,'') as DivisionCode, 
       		CONVERT(varchar(100),'') as DivisionName,
       		CONVERT(varchar(4) ,'') as DepartmentCode,
       		CONVERT(varchar(100) ,'') as DepartmentName,
       		CONVERT(varchar(4) ,'') as ClassCode,
       		CONVERT(varchar(100) ,'') as ClassName,
       		CONVERT(varchar(2) ,'') as LegacyCode
	INTO 	#Hierarchy
	DELETE FROM #Hierarchy

	IF  EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'[Merchandising].[HierarchyTag]') AND name = N'UQ_Merchandising_HierarchyTag')
	BEGIN
		ALTER TABLE [Merchandising].[HierarchyTag] DROP CONSTRAINT [UQ_Merchandising_HierarchyTag]
	END 
	ALTER TABLE [Merchandising].[HierarchyTag] ADD  CONSTRAINT [UQ_Merchandising_HierarchyTag] UNIQUE NONCLUSTERED 
	([LevelId] ASC, [Name] ASC, [Code] ASC) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

	INSERT INTO #Hierarchy(DivisionCode, DivisionName, DepartmentCode, DepartmentName, ClassCode, ClassName, LegacyCode)
	SELECT 'R','DISCOUNTS','RR4','DISCOUNTS ELECTRICAL','DED','DS ELEC DAMAGE','36' UNION ALL
	SELECT 'R','DISCOUNTS','RR4','DISCOUNTS ELECTRICAL','DEC','DS ELEC COMPETITION','37' UNION ALL
	SELECT 'R','DISCOUNTS','RR4','DISCOUNTS ELECTRICAL','DEO','DS ELEC OTHER','38' UNION ALL
	SELECT 'R','DISCOUNTS','RR4','DISCOUNTS ELECTRICAL','DEEC','DS ELEC E-COMMERCE','38' UNION ALL
	SELECT 'R','DISCOUNTS','RR4','DISCOUNTS ELECTRICAL','DES','DISCOUNT ELEC STAFF','46' UNION ALL
	SELECT 'R','DISCOUNTS','RR4','DISCOUNTS ELECTRICAL','DEM','DS ELEC MANAGEMENT','47' UNION ALL
	SELECT 'R','DISCOUNTS','RR4','DISCOUNTS ELECTRICAL','DWD','DS WKST DAMAGE','36' UNION ALL
	SELECT 'R','DISCOUNTS','RR4','DISCOUNTS ELECTRICAL','DWC','DS WKST COMPETITION','37' UNION ALL
	SELECT 'R','DISCOUNTS','RR4','DISCOUNTS ELECTRICAL','DWO','DS WKST OTHER','38' UNION ALL
	SELECT 'R','DISCOUNTS','RR4','DISCOUNTS ELECTRICAL','DWEC','DS W/STATION E-COMMERCE','38' UNION ALL
	SELECT 'R','DISCOUNTS','RR4','DISCOUNTS ELECTRICAL','DWS','DS WKST STAFF','46' UNION ALL
	SELECT 'R','DISCOUNTS','RR4','DISCOUNTS ELECTRICAL','DWM','DS WKST MANAGEMENT','47' UNION ALL
	SELECT 'R','DISCOUNTS','RR3','DISCOUNTS FURNITURE','DFM','DS FURN MANAGEMENT','48' UNION ALL
	SELECT 'R','DISCOUNTS','RR3','DISCOUNTS FURNITURE','DFS','DS FURN STAFF','48' UNION ALL
	SELECT 'R','DISCOUNTS','RR3','DISCOUNTS FURNITURE','DFD','DS FURN DAMAGE','86' UNION ALL
	SELECT 'R','DISCOUNTS','RR3','DISCOUNTS FURNITURE','DFC','DS FURN COMPETITION','87' UNION ALL
	SELECT 'R','DISCOUNTS','RR3','DISCOUNTS FURNITURE','DFO','DS FURN OTHER','88' UNION ALL
	SELECT 'R','DISCOUNTS','RR3','DISCOUNTS FURNITURE','DFEC','DS FURN E-COMMERCE','88' UNION ALL
	SELECT 'R','DISCOUNTS','RR2','DISCOUNTS OTHER','DS','DISCOUNT KIT CODES','37' UNION ALL
	SELECT 'R','DISCOUNTS','RR1','DISCOUNT SPARES','7DIS','DISCOUNT ON SPARES','20' UNION ALL
	SELECT 'R','DISCOUNTS','RR2','DISCOUNTS OTHER','CDS','DISCOUNT-SALE','49' UNION ALL
	SELECT 'R','DISCOUNTS','RR2','DISCOUNTS OTHER','TDE1','DISCOUNT FOR $2 000','92' UNION ALL
	SELECT 'R','DISCOUNTS','RR2','DISCOUNTS OTHER','TDE2','DISCOUNT OF $5000','92' UNION ALL
	SELECT 'R','DISCOUNTS','RR2','DISCOUNTS OTHER','TDE3','DISCOUNT OF $10 000','92' UNION ALL
	SELECT 'T','DV CASH LOAN','TT1','DP CASH LOAN','T1A','CL CASH LOAN','76' UNION ALL
	SELECT 'U','INSTALLATION','UU2','INSTALLATION ELECTRICAL','U2A','AC INSTALLATION 12000BTU','93' UNION ALL
	SELECT 'U','INSTALLATION','UU2','INSTALLATION ELECTRICAL','U2B','AC INSTALLATION 18 TO 24000BTU','93' UNION ALL
	SELECT 'U','INSTALLATION','UU2','INSTALLATION ELECTRICAL','U2C','AC INSTALLATION 9000BTU','93' UNION ALL
	SELECT 'U','INSTALLATION','UU1','INSTALLATION GENERIC','U1A','INSTALLATION CHARGE','93' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A107','M/COMP 3PARTY H/BUS PRIV%','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A168','M/3RD PARTY H/BUS 15 SEAT','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A186','M/COMP MCYCL FLAT RATE L1','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A187','MOTOR COMPREHENSIVE','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A188','MOTOR COMPREHENSIVE','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A189','MOTOR COMPREHENSIVE','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A282','M/COMP MCYCL PRIV 179K L1','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A285','M/COMP MCYC PRIV% 172% L1','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A288','M/COMP MCYC PRIV% 180K L1','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A291','M/COMP MCYC PRIV% 195K L1','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A292','M/COMP MCYC PRIV% 200K L1','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A293','M/COMP MCYC PRIV% 225K L1','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A294','M/COMP MCYC PRIV% 250K L1','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A295','M/COMP M/CYC PRIV% 297K','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A296','M/COMP MCYC PRIV% 235K','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A297','M COMP M/CYCLE PRIV% 208K','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A298','M/COMP MCYC PRIV% 218K','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A299','M/COMP M/CYCL PRIV% 221K','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A300','M/COMP MCYC PRIV% 207K','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A301','M/COMM M/CYCL PRIV% 169K','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A302','M/COMP MCYCL PRIV% 163K','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A304','M/COMP MCYC PRIV% 140K L1','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A305','M/COMP MCYC PRIV% 160K L1','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A312','M/COMP MCYC PRIV% 170K L1','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A314','M/COMP MCYC PRIV% 165K L1','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A316','M/COMP MCYC PRIV% 300K L1','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A317','M/COMP MCYC PRIV% 190K L1','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A318','M/COMP MCYC PRIV% 192K L1','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A319','M/COMP M/CYC PRIV% 229K','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A321','M/COMP MCYC PRIV% 267K','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A322','M/COMP M/CYC PRIV% 232K','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A323','M/COMP M/CYC PRIV% 245K','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A324','M/COMP M/CYC PRIV% 172K','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A325','M/COMP M/CYC PRIV% 239K','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A326','M/COMP M/CYC PRIV% 205K','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A327','M/COMP M/CYC PRIV% 210K','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A328','M/COMP M/CYC PRIV% 262K','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A331','M/COMP MCYC PRIV% 239.8K','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A332','M/COMP MCYC $360 420 1Y','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','A333','M/COMP MCYC 192K 1YR','51' UNION ALL
	SELECT 'W','AFFINITY','WW2','INSURANCE','MSI','MOTOR SCOOTER INSURANCE','51' UNION ALL
	SELECT 'W','AFFINITY','WW1','READY ASSIST','RY2S','24 MONTHS SERVICE PACKAGE STAFF','11' UNION ALL
	SELECT 'W','AFFINITY','WW1','READY ASSIST','RY2','24 MONTHS SERVICE PACKAGE','11' UNION ALL
	SELECT 'W','AFFINITY','WW1','READY ASSIST','RY3S','36 MONTHS SERVICE PACKAGE STAFF','11' UNION ALL
	SELECT 'W','AFFINITY','WW1','READY ASSIST','RY3','36 MONTHS SERVICE PACKAGE','11' UNION ALL
	SELECT 'W','AFFINITY','WW1','READY ASSIST','RY1S','12 MONTHS SERVICE PACKAGE STAFF','11' UNION ALL
	SELECT 'W','AFFINITY','WW1','READY ASSIST','RY1','12 MONTHS SERVICE PACKAGE','11' UNION ALL
	SELECT 'S','SERVICE GENERIC','SS1','SERVICE COURTS','S1A','PARTS','20' UNION ALL
	SELECT 'S','SERVICE GENERIC','SS1','SERVICE COURTS','S1C','LABOUR','20' UNION ALL
	SELECT 'S','SERVICE GENERIC','SS2','SERVICE NON COURTS','S2A','OTHERS','20' UNION ALL
	SELECT 'V','CHARGES','VV2','CREDIT CHARGES','V2B','ADD-TO BALANCE CREDIT','90' UNION ALL
	SELECT 'V','CHARGES','VV2','CREDIT CHARGES','V2C','ADD-TO BALANCE','90' UNION ALL
	SELECT 'V','CHARGES','VV2','CREDIT CHARGES','V2D','DEFERRED TERMS','90' UNION ALL
	SELECT 'V','CHARGES','VV2','CREDIT CHARGES','V2A','REBATE','39' UNION ALL
	SELECT 'V','CHARGES','VV5','MOBILE PHONE TOP UP','V5A','GTT CELL POINT CHARGES','4' UNION ALL
	SELECT 'V','CHARGES','VV1','ADMIN CHARGES','V1A','BILL OF SALE','5' UNION ALL
	SELECT 'V','CHARGES','VV3','DELIVERY CHARGES','V3A','DELIVERY CHARGES','94' UNION ALL
	SELECT 'V','CHARGES','VV6','VAT','V6A','VAT','96' UNION ALL
	SELECT 'V','CHARGES','VV4','MISCELLANEOUS','V4A','GIFT PURCHASE','14' UNION ALL
	SELECT 'V','CHARGES','VV4','MISCELLANEOUS','V4B','MISCELLANEOUS','80' UNION ALL
	SELECT 'V','CHARGES','VV4','MISCELLANEOUS','V4C','GIFT WRAP CHARGES','80' UNION ALL
	SELECT 'V','CHARGES','VV4','MISCELLANEOUS','V4D','A B MUSIC SUPPLIES','97' UNION ALL
	SELECT 'V','CHARGES','VV4','MISCELLANEOUS','V4E','ACME','97' UNION ALL
	SELECT 'V','CHARGES','VV4','MISCELLANEOUS','V4F','COURTS NETZONE FEES','97' UNION ALL
	SELECT 'V','CHARGES','VV4','MISCELLANEOUS','V4G','CITY COLLEGE','97' UNION ALL
	SELECT 'V','CHARGES','VV4','MISCELLANEOUS','V4H','ACTIVATION AND SECURITY','97' UNION ALL
	SELECT 'V','CHARGES','VV4','MISCELLANEOUS','V4I','SOLUTIONS 2000','97' UNION ALL
	SELECT 'V','CHARGES','VV4','MISCELLANEOUS','V4J','EASY INS','98' UNION ALL
	SELECT 'V','CHARGES','VV4','MISCELLANEOUS','V4K','GOLD INS','98' UNION ALL
	SELECT 'V','CHARGES','VV4','MISCELLANEOUS','V4L','INSURANCE','98' UNION ALL
	SELECT 'V','CHARGES','VV4','MISCELLANEOUS','V4M','10 PORC PROCESSING FEE','99'
	
	-- Division
	SELECT @levelId = id FROM Merchandising.HierarchyLevel WHERE name = 'Division'
 
	INSERT INTO Merchandising.HierarchyTag (LevelId, Name, Code)
	SELECT DISTINCT @levelId, h.DivisionName, h.DivisionCode
	FROM #Hierarchy h
 
	-- Department
	SELECT @levelId = id FROM Merchandising.HierarchyLevel WHERE name = 'Department'
 
	INSERT INTO Merchandising.HierarchyTag (LevelId, Name, Code)
	SELECT DISTINCT @levelId, h.DepartmentName, h.DepartmentCode
	FROM #Hierarchy h
 
	-- Class
	SELECT @levelId = id FROM Merchandising.HierarchyLevel WHERE name = 'Class'

	INSERT INTO Merchandising.HierarchyTag (LevelId, Name, Code)
	SELECT DISTINCT @levelId, h.ClassName, h.ClassCode
	FROM #Hierarchy h
 
	DROP TABLE #Hierarchy
END