-- transaction: true
-- Change the previous line to false to disable running this whole migration in one transaction.
-- Removing that first line will default to 'true'.
-- 
-- Put your SQL code here
DELETE Financial.TransactionMappingService

INSERT INTO Financial.TransactionMappingService
	(ChargeType, Label, ServiceType, IsExternal, Replacement, CashNotCredit, Department, Account, Percentage, UseValueColumn, TransactionType)
VALUES
    ('Supplier', '*', '*', NULL, NULL, NULL, '*', '1392', 1, 1, 'SRS'),
    ('Supplier', '*', '*', NULL, NULL, NULL, '*', '9020S', -1, 1, 'SRS'),
    ('FYW', '*', '*', NULL, NULL, NULL, '*', '2930', 1, 1, 'SRY'),
    ('FYW', '*', '*', NULL, NULL, NULL, '*', '9020I', -1, 1, 'SRY'),
    ('EW', '*', '*', NULL, NULL, NULL, '*', '2910', 1, 1, 'SRW'),
    ('EW', '*', '*', NULL, NULL, NULL, '*', '9020E', -1, 1, 'SRW'),
    ('Internal', '*', '*', NULL, NULL, NULL, '*', '9010', 1, 1, 'SRI'),
    ('Internal', '*', '*', NULL, NULL, NULL, '*', '9020B', -1, 1, 'SRI'),
    ('Customer', '*', 'II', NULL, NULL, 1, 'PCE', '1301', 1, 1, 'BCP'),
    ('Customer', '*', 'II', NULL, NULL, 1, 'PCE', '5193', -1, 1, 'BCP'),
    ('Customer', '*', 'II', NULL, NULL, 1, 'PCE', '6093', 0, 1, 'INE'),
    ('Customer', '*', 'II', NULL, NULL, 1, 'PCE', '5193', 1, 1, 'INE'),
    ('Customer', '*', 'II', NULL, NULL, 1, 'PCF', '1301', 1, 1, 'BCP'),
    ('Customer', '*', 'II', NULL, NULL, 1, 'PCF', '5192', -1, 1, 'BCP'),
    ('Customer', '*', 'II', NULL, NULL, 1, 'PCF', '6092', 0, 1, 'INF'),
    ('Customer', '*', 'II', NULL, NULL, 1, 'PCF', '5192', 1, 1, 'INF'),
    ('Customer', '*', 'II', NULL, NULL, 0, 'PCE', '1301', 1, 1, 'BHP'),
    ('Customer', '*', 'II', NULL, NULL, 0, 'PCE', '5293', -1, 1, 'BHP'),
    ('Customer', '*', 'II', NULL, NULL, 0, 'PCE', '6093', 0, 1, 'INE'),
    ('Customer', '*', 'II', NULL, NULL, 0, 'PCE', '5293', 1, 1, 'INE'),
    ('Customer', '*', 'II', NULL, NULL, 0, 'PCF', '1301', 1, 1, 'BHP'),
    ('Customer', '*', 'II', NULL, NULL, 0, 'PCF', '5292', -1, 1, 'BHP'),
    ('Customer', '*', 'II', NULL, NULL, 0, 'PCF', '6092', 0, 1, 'INF'),
    ('Customer', '*', 'II', NULL, NULL, 0, 'PCF', '5292', 1, 1, 'INF'),
    ('Customer', '*', 'IE', NULL, NULL, NULL, 'PCE', '1301', 1, 1, 'BCP'),
    ('Customer', '*', 'IE', NULL, NULL, NULL, 'PCE', '5193', -1, 1, 'BCP'),
    ('Customer', '*', 'IE', NULL, NULL, NULL, 'PCE', '6093', 1, 1, 'INE'),
    ('Customer', '*', 'IE', NULL, NULL, NULL, 'PCE', '5193', -1, 1, 'INE'),
    ('Customer', '*', 'IE', NULL, NULL, NULL, 'PCF', '1301', 1, 1, 'BCP'),
    ('Customer', '*', 'IE', NULL, NULL, NULL, 'PCF', '5192', -1, 1, 'BCP'),
    ('Customer', '*', 'IE', NULL, NULL, NULL, 'PCF', '6092', 1, 1, 'INF'),
    ('Customer', '*', 'IE', NULL, NULL, NULL, 'PCF', '5192', -1, 1, 'INF'),
    ('Customer', '*', 'SI', NULL, NULL, 1, '*', '1301', 1, 1, 'BCP'),
    ('Customer', '*', 'SI', NULL, NULL, 1, '*', '9020C', -1, 1, 'BCP'),
    ('Customer', '*', 'SI', NULL, NULL, 0, '*', '1301', 1, 1, 'BHP'),
    ('Customer', '*', 'SI', NULL, NULL, 0, '*', '9020C', -1, 1, 'BHP'),
    ('Customer', '*', 'SE', NULL, NULL, NULL, '*', '1301', 1, 1, 'BCP'),
    ('Customer', '*', 'SE', NULL, NULL, NULL, '*', '9020C', -1, 1, 'BCP'),
    ('Installation Charge Electrical', '*', '*', NULL, NULL, 0, '*', '6093', 1, 1, 'INE'),
    ('Installation Charge Electrical', '*', '*', NULL, NULL, 0, '*', '5293', -1, 1, 'INE'),
    ('Installation Charge Electrical', '*', '*', NULL, NULL, 1, '*', '6093', 1, 1, 'INE'),
    ('Installation Charge Electrical', '*', '*', NULL, NULL, 1, '*', '5193', -1, 1, 'INE'),
    ('Installation Charge Furniture', '*', '*', NULL, NULL, 0, '*', '6092', 1, 1, 'INF'),
    ('Installation Charge Furniture', '*', '*', NULL, NULL, 0, '*', '5292', -1, 1, 'INF'),
    ('Installation Charge Furniture', '*', '*', NULL, NULL, 1, '*', '6092', 1, 1, 'INF'),
    ('Installation Charge Furniture', '*', '*', NULL, NULL, 1, '*', '5192', -1, 1, 'INF'),
    ('Deliverer', '*', '*', NULL, NULL, NULL, '*', '1301', 1, 1, 'SRD'),
    ('Deliverer', '*', '*', NULL, NULL, NULL, '*', '9020D', -1, 1, 'SRD'),
    ('Customer', '*', '*', NULL, NULL, NULL, '*', '2980', 1, 1, 'PAY'),
    ('Customer', '*', '*', NULL, NULL, NULL, '*', '1301', -1, 1, 'PAY'),
    ('Deliverer', '*', '*', NULL, NULL, NULL, '*', '2980', 1, 1, 'PAY'),
    ('Deliverer', '*', '*', NULL, NULL, NULL, '*', '1301', -1, 1, 'PAY'),
    ('Customer Tax', '*', '*', NULL, NULL, NULL, '*', '1301', 1, 1, 'BTX'),
    ('Customer Tax', '*', '*', NULL, NULL, NULL, '*', '2981', -1, 1, 'BTX'),
    ('Customer Tax', '*', '*', NULL, NULL, NULL, '*', '2980', 1, 1, 'PAY'),
    ('Customer Tax', '*', '*', NULL, NULL, NULL, '*', '1301', -1, 1, 'PAY')
