-- transaction: true
-- Change the previous line to false to disable running this whole migration in one transaction.
-- Removing that first line will default to 'true'.
-- 
-- Put your SQL code here

DECLARE @levelId int

SELECT 	
	CONVERT(VARCHAR(4), '') AS DivisionCode, 
    CONVERT(VARCHAR(100), '') AS DivisionName,
    CONVERT(VARCHAR(4), '') AS DepartmentCode,
    CONVERT(VARCHAR(100), '') AS DepartmentName,
    CONVERT(VARCHAR(4), '') AS ClassCode,
    CONVERT(VARCHAR(100), '') AS ClassName,
    CONVERT(VARCHAR(2), '') AS LegacyCode
INTO #Hierarchy
DELETE FROM #Hierarchy

INSERT INTO #Hierarchy (DivisionCode, DivisionName, DepartmentCode, DepartmentName, ClassCode, ClassName, LegacyCode)
	SELECT '1', 'AUDIO VISUAL', '115', 'GAMING', '15B', 'GAMING CONSOLES', '1' UNION
	SELECT '1', 'AUDIO VISUAL', '115', 'GAMING', '15C', 'GAMING SOFTWARE', '1' UNION
	SELECT '1', 'AUDIO VISUAL', '105', 'VISION', '10A', 'DVD PLAYERS', '1' UNION
	SELECT '1', 'AUDIO VISUAL', '105', 'VISION', '10B', 'MEDIA PLAYER', '1' UNION
	SELECT '1', 'AUDIO VISUAL', '105', 'VISION', '10C', 'TV 20INCH LT', '1' UNION
	SELECT '1', 'AUDIO VISUAL', '105', 'VISION', '10D', 'TV 25INCH LT', '1' UNION
	SELECT '1', 'AUDIO VISUAL', '105', 'VISION', '10E', 'TV 30INCH LT', '1' UNION
	SELECT '1', 'AUDIO VISUAL', '105', 'VISION', '10F', 'TV 32INCH', '1' UNION
	SELECT '1', 'AUDIO VISUAL', '105', 'VISION', '10G', 'TV 43INCH LT', '1' UNION
	SELECT '1', 'AUDIO VISUAL', '105', 'VISION', '10H', 'TV 50INCH LT', '1' UNION
	SELECT '1', 'AUDIO VISUAL', '105', 'VISION', '10I', 'TV 55INCH LT', '1' UNION
	SELECT '1', 'AUDIO VISUAL', '105', 'VISION', '10J', 'TV 60INCH LT', '1' UNION
	SELECT '1', 'AUDIO VISUAL', '105', 'VISION', '10K', 'TV 65INCH  GT', '1' UNION
	SELECT '1', 'AUDIO VISUAL', '105', 'VISION', '10L', 'VIDEO ACCESSORIES', '1' UNION
	SELECT '1', 'AUDIO VISUAL', '110', 'AUDIO', '11A', 'AUDIO SEPARATES', '2' UNION
	SELECT '1', 'AUDIO VISUAL', '110', 'AUDIO', '11B', 'BOOMBOXES', '2' UNION
	SELECT '1', 'AUDIO VISUAL', '110', 'AUDIO', '11C', 'HOME THEATRE SYSTEMS', '2' UNION
	SELECT '1', 'AUDIO VISUAL', '110', 'AUDIO', '11D', 'MEGA SYSTEMS', '2' UNION
	SELECT '1', 'AUDIO VISUAL', '110', 'AUDIO', '11E', 'MINI SYSTEMS', '2' UNION
	SELECT '1', 'AUDIO VISUAL', '110', 'AUDIO', '11F', 'PORTABLE SPEAKERS', '2' UNION
	SELECT '1', 'AUDIO VISUAL', '110', 'AUDIO', '11G', 'RADIOS', '2' UNION
	SELECT '1', 'AUDIO VISUAL', '110', 'AUDIO', '11H', 'SPEAKER SYSTEMS', '2' UNION
	SELECT '1', 'AUDIO VISUAL', '110', 'AUDIO', '11I', 'SPEAKERS', '2' UNION
	SELECT '1', 'AUDIO VISUAL', '120', 'CAR AUDIO', '12A', 'CAR AUDIO ACCESSORIES', '2' UNION
	SELECT '1', 'AUDIO VISUAL', '120', 'CAR AUDIO', '12B', 'CAR AUDIO SPEAKERS', '2' UNION
	SELECT '1', 'AUDIO VISUAL', '120', 'CAR AUDIO', '12C', 'COMBOS', '2' UNION
	SELECT '1', 'AUDIO VISUAL', '120', 'CAR AUDIO', '12D', 'EQUALIZERS AND AMPLIFIERS', '2' UNION
	SELECT '1', 'AUDIO VISUAL', '120', 'CAR AUDIO', '12E', 'HEAD UNIT WITH TOUCH SCREEN', '2' UNION
	SELECT '1', 'AUDIO VISUAL', '120', 'CAR AUDIO', '12F', 'HEAD UNITS', '2' UNION
	SELECT '1', 'AUDIO VISUAL', '120', 'CAR AUDIO', '12G', 'MARITIME AUDIO', '2' UNION
	SELECT '1', 'AUDIO VISUAL', '110', 'AUDIO', '11J', 'AUDIO ACCESSORIES', '6' UNION
	SELECT '1', 'AUDIO VISUAL', '115', 'GAMING', '15A', 'GAMING ACCESORIES', '6' UNION
	SELECT 'A', 'AUTOMOTIVE', '993', 'TYRES', 'A49', 'AGRICULTURAL TIRE', '5' UNION
	SELECT 'A', 'AUTOMOTIVE', '993', 'TYRES', 'A47', 'MOTORCYCLE TIRE', '5' UNION
	SELECT 'A', 'AUTOMOTIVE', '993', 'TYRES', 'A48', 'QUADRICYCLE TIRE', '5' UNION
	SELECT 'A', 'AUTOMOTIVE', '993', 'TYRES', 'A45', 'RIN 10', '5' UNION
	SELECT 'A', 'AUTOMOTIVE', '993', 'TYRES', 'A46', 'RIN 12', '5' UNION
	SELECT 'A', 'AUTOMOTIVE', '993', 'TYRES', 'A31', 'RIN 13', '5' UNION
	SELECT 'A', 'AUTOMOTIVE', '993', 'TYRES', 'A32', 'RIN 14', '5' UNION
	SELECT 'A', 'AUTOMOTIVE', '993', 'TYRES', 'A33', 'RIN 15', '5' UNION
	SELECT 'A', 'AUTOMOTIVE', '993', 'TYRES', 'A34', 'RIN 16', '5' UNION
	SELECT 'A', 'AUTOMOTIVE', '993', 'TYRES', 'A35', 'RIN 17', '5' UNION
	SELECT 'A', 'AUTOMOTIVE', '993', 'TYRES', 'A36', 'RIN 18', '5' UNION
	SELECT 'A', 'AUTOMOTIVE', '993', 'TYRES', 'A37', 'RIN 19', '5' UNION
	SELECT 'A', 'AUTOMOTIVE', '993', 'TYRES', 'A43', 'RIN 19 5', '5' UNION
	SELECT 'A', 'AUTOMOTIVE', '993', 'TYRES', 'A38', 'RIN 20', '5' UNION
	SELECT 'A', 'AUTOMOTIVE', '993', 'TYRES', 'A39', 'RIN 21', '5' UNION
	SELECT 'A', 'AUTOMOTIVE', '993', 'TYRES', 'A40', 'RIN 22', '5' UNION
	SELECT 'A', 'AUTOMOTIVE', '993', 'TYRES', 'A41', 'RIN 23', '5' UNION
	SELECT 'A', 'AUTOMOTIVE', '993', 'TYRES', 'A42', 'RIN 24', '5' UNION
	SELECT 'A', 'AUTOMOTIVE', '993', 'TYRES', 'A44', 'RIN 9', '5' UNION
	SELECT 'A', 'AUTOMOTIVE', '991', 'TRANSPORT', 'A13', 'CUADRIMOTOS', '5' UNION
	SELECT 'A', 'AUTOMOTIVE', '991', 'TRANSPORT', 'A14', 'MARINE ENGINES', '5' UNION
	SELECT 'A', 'AUTOMOTIVE', '991', 'TRANSPORT', 'A12', 'MOTORCYCLES', '5' UNION
	SELECT 'A', 'AUTOMOTIVE', '991', 'TRANSPORT', 'A11', 'VEHICLE', '5' UNION
	SELECT 'A', 'AUTOMOTIVE', '992', 'VEHICLES ACCESSORIES', 'A24', 'CAR ACCESSORIES', '5' UNION
	SELECT 'A', 'AUTOMOTIVE', '992', 'VEHICLES ACCESSORIES', 'A21', 'CAR BATTERIES', '5' UNION
	SELECT 'A', 'AUTOMOTIVE', '992', 'VEHICLES ACCESSORIES', 'A23', 'CAR PARTS', '5' UNION
	SELECT 'A', 'AUTOMOTIVE', '992', 'VEHICLES ACCESSORIES', 'A22', 'LUBRICANTS', '5' UNION
	SELECT 'A', 'AUTOMOTIVE', '992', 'VEHICLES ACCESSORIES', 'A26', 'MOTORCYCLE ACCESSORIES', '5' UNION
	SELECT 'A', 'AUTOMOTIVE', '992', 'VEHICLES ACCESSORIES', 'A25', 'MOTORCYCLE PARTS', '5' UNION
	SELECT '5', 'COMPUTER AND OFFICE', '520', 'CELLPHONES AND ACCESSORIES', '52A', 'AIR TIME', '4' UNION
	SELECT '5', 'COMPUTER AND OFFICE', '520', 'CELLPHONES AND ACCESSORIES', '52D', 'MOBILE ACCESSORIES', '4' UNION
	SELECT '5', 'COMPUTER AND OFFICE', '520', 'CELLPHONES AND ACCESSORIES', '52B', 'OPEN PHONES', '4' UNION
	SELECT '5', 'COMPUTER AND OFFICE', '520', 'CELLPHONES AND ACCESSORIES', '52C', 'PRE PAID PHONES', '4' UNION
	SELECT '5', 'COMPUTER AND OFFICE', '510', 'OFFICE SYSTEM', '51B', 'COPIERS', '4' UNION
	SELECT '5', 'COMPUTER AND OFFICE', '510', 'OFFICE SYSTEM', '51C', 'DOMESTIC PHONES', '4' UNION
	SELECT '5', 'COMPUTER AND OFFICE', '510', 'OFFICE SYSTEM', '51D', 'FAX', '4' UNION
	SELECT '5', 'COMPUTER AND OFFICE', '510', 'OFFICE SYSTEM', '51E', 'OTHER OFFICE EQUIPMENT', '4' UNION
	SELECT '5', 'COMPUTER AND OFFICE', '510', 'OFFICE SYSTEM', '51F', 'PROJECTORS', '4' UNION
	SELECT '5', 'COMPUTER AND OFFICE', '510', 'OFFICE SYSTEM', '51A', 'CALCULATORS', '5' UNION
	SELECT '5', 'COMPUTER AND OFFICE', '505', 'COMPUTER AND ACCESSORIES', '50A', 'DESKTOPS', '21' UNION
	SELECT '5', 'COMPUTER AND OFFICE', '505', 'COMPUTER AND ACCESSORIES', '50B', 'LAPTOPS', '21' UNION
	SELECT '5', 'COMPUTER AND OFFICE', '505', 'COMPUTER AND ACCESSORIES', '50C', 'MONITORS', '21' UNION
	SELECT '5', 'COMPUTER AND OFFICE', '505', 'COMPUTER AND ACCESSORIES', '50G', 'TABLETS', '21' UNION
	SELECT '5', 'COMPUTER AND OFFICE', '515', 'BLANK MEDIA', '55B', 'BATTERIES', '22' UNION
	SELECT '5', 'COMPUTER AND OFFICE', '515', 'BLANK MEDIA', '55C', 'BLANK CDS/DVDS/CASSETTES', '22' UNION
	SELECT '5', 'COMPUTER AND OFFICE', '515', 'BLANK MEDIA', '55A', 'BLANK MEDIA ACCESSORIES', '22' UNION
	SELECT '5', 'COMPUTER AND OFFICE', '515', 'BLANK MEDIA', '55D', 'HARD DRIVES', '22' UNION
	SELECT '5', 'COMPUTER AND OFFICE', '515', 'BLANK MEDIA', '55E', 'MEMORY CARDS', '22' UNION
	SELECT '5', 'COMPUTER AND OFFICE', '515', 'BLANK MEDIA', '55F', 'USB FLASH MEMORY', '22' UNION
	SELECT '5', 'COMPUTER AND OFFICE', '505', 'COMPUTER AND ACCESSORIES', '50D', 'PERIPHERALS COMPUTER ACC', '22' UNION
	SELECT '5', 'COMPUTER AND OFFICE', '505', 'COMPUTER AND ACCESSORIES', '50F', 'PRINTER', '22' UNION
	SELECT '5', 'COMPUTER AND OFFICE', '505', 'COMPUTER AND ACCESSORIES', '50E', 'PRINTER SUPPLIES', '22' UNION
	SELECT 'X', 'DV FREE GIFT', '863', 'DP FREE GIFT', 'X01', 'CL FREE GIFT', '84' UNION
	SELECT 'B', 'ELECTRONICS', '951', 'CAMERAS', 'B01', 'CAMCORDERS', '1' UNION
	SELECT 'B', 'ELECTRONICS', '951', 'CAMERAS', 'B02', 'CAMERA ACCESSORIES', '1' UNION
	SELECT 'B', 'ELECTRONICS', '951', 'CAMERAS', 'B03', 'DIGITAL PHOTO CAMERA', '1' UNION
	SELECT 'B', 'ELECTRONICS', '951', 'CAMERAS', 'B04', 'SLR CAMERAS', '1' UNION
	SELECT 'B', 'ELECTRONICS', '954', 'SECURITY SYSTEM', 'B14', 'DVR RECORDERS', '1' UNION
	SELECT 'B', 'ELECTRONICS', '954', 'SECURITY SYSTEM', 'B15', 'SECURITY ACCESSORIES', '1' UNION
	SELECT 'B', 'ELECTRONICS', '954', 'SECURITY SYSTEM', 'B16', 'SECURITY CAMERAS', '1' UNION
	SELECT 'B', 'ELECTRONICS', '954', 'SECURITY SYSTEM', 'B17', 'SECURITY KIT COMBOS', '1' UNION
	SELECT 'B', 'ELECTRONICS', '953', 'MUSICAL INSTRUMENTS', 'B10', 'DRUMS (PERCUSSION)', '2' UNION
	SELECT 'B', 'ELECTRONICS', '953', 'MUSICAL INSTRUMENTS', 'B11', 'GUITARS (STRING)', '2' UNION
	SELECT 'B', 'ELECTRONICS', '953', 'MUSICAL INSTRUMENTS', 'B12', 'KEYBOARDS', '2' UNION
	SELECT 'B', 'ELECTRONICS', '952', 'PERSONAL ELECTRONIC', 'B05', 'MOBILE SPEAKERS', '2' UNION
	SELECT 'B', 'ELECTRONICS', '952', 'PERSONAL ELECTRONIC', 'B06', 'MP3', '2' UNION
	SELECT 'B', 'ELECTRONICS', '952', 'PERSONAL ELECTRONIC', 'B07', 'MP4', '2' UNION
	SELECT 'B', 'ELECTRONICS', '953', 'MUSICAL INSTRUMENTS', 'B09', 'MUSICAL INST ACCESSORIES', '6' UNION
	SELECT 'B', 'ELECTRONICS', '952', 'PERSONAL ELECTRONIC', 'B08', 'WEARABLE ELECTRONICS', '6' UNION
	SELECT 'B', 'ELECTRONICS', '953', 'MUSICAL INSTRUMENTS', 'B13', 'WIND INSTRUMENTS', '2' UNION
	SELECT '7', 'FURNITURE', '716', 'LOUNGE', '70F', 'LOUNGE FUTON SOFA BED', '50' UNION
	SELECT '7', 'FURNITURE', '716', 'LOUNGE', '70A', 'LOUNGE SINGLE PIECES', '50' UNION
	SELECT '7', 'FURNITURE', '716', 'LOUNGE', '74I', 'LOUNGE SOFA SETS', '50' UNION
	SELECT '7', 'FURNITURE', '716', 'LOUNGE', '70E', 'SECTIONAL', '50' UNION
	SELECT '7', 'FURNITURE', '716', 'LOUNGE', '74K', 'SOFA SET MOTION', '50' UNION
	SELECT '7', 'FURNITURE', '716', 'LOUNGE', '70B', 'SOFA SET UPHOLSTERED', '50' UNION
	SELECT '7', 'FURNITURE', '716', 'LOUNGE', '70D', 'TV CHAIRRECLINER', '50' UNION
	SELECT '7', 'FURNITURE', '724', 'DINING', '71E', '5PC DINING SET  METAL', '60' UNION
	SELECT '7', 'FURNITURE', '724', 'DINING', '70G', '5PC DINING SET WOODEN', '60' UNION
	SELECT '7', 'FURNITURE', '724', 'DINING', '71H', '7PC DINING SET  METAL', '60' UNION
	SELECT '7', 'FURNITURE', '724', 'DINING', '70L', '7PC DINING SET WOODEN', '60' UNION
	SELECT '7', 'FURNITURE', '724', 'DINING', '71I', '9PC DINING SET METAL', '60' UNION
	SELECT '7', 'FURNITURE', '724', 'DINING', '70X', '9PC DINING SET WOODEN', '60' UNION
	SELECT '7', 'FURNITURE', '724', 'DINING', '71S', 'DINING SINGLE PIECES', '60' UNION
	SELECT '7', 'FURNITURE', '724', 'DINING', '71V', 'HUTCH SERVER', '60' UNION
	SELECT '7', 'FURNITURE', '724', 'DINING', '71J', 'MISCELLANEOUS TABLE AND CHAIR SET', '60' UNION
	SELECT '7', 'FURNITURE', '724', 'DINING', '71O', 'TABLE WITH BENCH SET', '60' UNION
	SELECT '7', 'FURNITURE', '748', 'FURNITURE OCCASIONAL MISC', '73E', 'BAR STOOL', '60' UNION
	SELECT '7', 'FURNITURE', '748', 'FURNITURE OCCASIONAL MISC', '73F', 'BAR TABLE', '60' UNION
	SELECT '7', 'FURNITURE', '757', 'KITCHEN', '73Q', 'FITTED KITCHEN', '60' UNION
	SELECT '7', 'FURNITURE', '757', 'KITCHEN', '73P', 'KITCHEN CABINETS', '60' UNION
	SELECT '7', 'FURNITURE', '744', 'BEDROOM', '72I', 'BEDROOM SETS', '70' UNION
	SELECT '7', 'FURNITURE', '744', 'BEDROOM', '72O', 'CHEST', '70' UNION
	SELECT '7', 'FURNITURE', '744', 'BEDROOM', '72U', 'CHILDREN BEDROOM FURNITURE', '70' UNION
	SELECT '7', 'FURNITURE', '744', 'BEDROOM', '74J', 'CLOSET WARDROBES', '70' UNION
	SELECT '7', 'FURNITURE', '744', 'BEDROOM', '72N', 'DRESSER AND MIRROR', '70' UNION
	SELECT '7', 'FURNITURE', '744', 'BEDROOM', '72K', 'NIGHTSTAND', '70' UNION
	SELECT '7', 'FURNITURE', '744', 'BEDROOM', '72V', 'OVERBED FURNITURE', '70' UNION
	SELECT '7', 'FURNITURE', '744', 'BEDROOM', '73G', 'SINGLES PIECES BEDROOM', '70' UNION
	SELECT '7', 'FURNITURE', '744', 'BEDROOM', '72P', 'TV CHEST', '70' UNION
	SELECT '7', 'FURNITURE', '744', 'BEDROOM', '72S', 'BED METAL', '75' UNION
	SELECT '7', 'FURNITURE', '744', 'BEDROOM', '72T', 'BED WOODEN', '75' UNION
	SELECT '7', 'FURNITURE', '744', 'BEDROOM', '72R', 'BUNK  WOODEN', '75' UNION
	SELECT '7', 'FURNITURE', '744', 'BEDROOM', '72Q', 'BUNK METAL', '75' UNION
	SELECT '7', 'FURNITURE', '748', 'FURNITURE OCCASIONAL MISC', '73D', 'ACCENT CHAIRS', '80' UNION
	SELECT '7', 'FURNITURE', '748', 'FURNITURE OCCASIONAL MISC', '74H', 'ENTERTAINMENT UNITS', '80' UNION
	SELECT '7', 'FURNITURE', '748', 'FURNITURE OCCASIONAL MISC', '73I', 'OCCASIONAL SINGLE PIECES', '80' UNION
	SELECT '7', 'FURNITURE', '748', 'FURNITURE OCCASIONAL MISC', '73B', 'OCCASIONAL TABLES', '80' UNION
	SELECT '7', 'FURNITURE', '748', 'FURNITURE OCCASIONAL MISC', '73C', 'OCCASIONAL TABLES SETS', '80' UNION
	SELECT '7', 'FURNITURE', '748', 'FURNITURE OCCASIONAL MISC', '73J', 'RACKS/CABINETS/SHELVING', '80' UNION
	SELECT '7', 'FURNITURE', '748', 'FURNITURE OCCASIONAL MISC', '73H', 'TV RACKS', '80' UNION
	SELECT '7', 'FURNITURE', '754', 'OFFICE', '73M', 'BOOKSHELVES', '80' UNION
	SELECT '7', 'FURNITURE', '754', 'OFFICE', '73N', 'DESK AND CHAIR COMBO', '80' UNION
	SELECT '7', 'FURNITURE', '754', 'OFFICE', '73K', 'DESKS', '80' UNION
	SELECT '7', 'FURNITURE', '754', 'OFFICE', '73L', 'OFFICE CHAIRS', '80' UNION
	SELECT '7', 'FURNITURE', '754', 'OFFICE', '73O', 'SINGLE PIECES', '80' UNION
	SELECT '7', 'FURNITURE', '737', 'OUTDOOR', '72A', 'DINING SETS', '80' UNION
	SELECT '7', 'FURNITURE', '737', 'OUTDOOR', '72D', 'OUTDOOR SINGLE PIECES', '80' UNION
	SELECT '7', 'FURNITURE', '737', 'OUTDOOR', '71X', 'OUTDOOR SOFA SETS', '80' UNION
	SELECT 'C', 'HARDW AGRIC INDUST', '962', 'ELECTRICAL GENERATORS', 'C17', 'ELECTRIC PLANTS', '5' UNION
	SELECT 'C', 'HARDW AGRIC INDUST', '962', 'ELECTRICAL GENERATORS', 'C18', 'INVERTERS', '5' UNION
	SELECT 'C', 'HARDW AGRIC INDUST', '962', 'ELECTRICAL GENERATORS', 'C19', 'SOLAR PANELS', '5' UNION
	SELECT 'C', 'HARDW AGRIC INDUST', '961', 'HARDWARE', 'C01', 'ACCESSORIES HARDWARE', '5' UNION
	SELECT 'C', 'HARDW AGRIC INDUST', '961', 'HARDWARE', 'C02', 'BRUSH CUTTERS', '5' UNION
	SELECT 'C', 'HARDW AGRIC INDUST', '961', 'HARDWARE', 'C04', 'CHAINSAWS', '5' UNION
	SELECT 'C', 'HARDW AGRIC INDUST', '961', 'HARDWARE', 'C05', 'COFFEE SHOP EQUIPMENT', '5' UNION
	SELECT 'C', 'HARDW AGRIC INDUST', '961', 'HARDWARE', 'C06', 'ENGINES AND POWER SOURCES', '5' UNION
	SELECT 'C', 'HARDW AGRIC INDUST', '961', 'HARDWARE', 'C07', 'GARDENING EQUIPMENT', '5' UNION
	SELECT 'C', 'HARDW AGRIC INDUST', '961', 'HARDWARE', 'C08', 'GENERAL EQUIPMENT FOR HOME', '5' UNION
	SELECT 'C', 'HARDW AGRIC INDUST', '961', 'HARDWARE', 'C09', 'INDUSTRIAL CLEANING EQUIPMENT', '5' UNION
	SELECT 'C', 'HARDW AGRIC INDUST', '961', 'HARDWARE', 'C11', 'INDUSTRIAL SEWING MACHINE', '5' UNION
	SELECT 'C', 'HARDW AGRIC INDUST', '961', 'HARDWARE', 'C12', 'LAWN', '5' UNION
	SELECT 'C', 'HARDW AGRIC INDUST', '961', 'HARDWARE', 'C14', 'POWER TOOL', '5' UNION
	SELECT 'C', 'HARDW AGRIC INDUST', '961', 'HARDWARE', 'C15', 'POWER WASHERS', '5' UNION
	SELECT 'C', 'HARDW AGRIC INDUST', '961', 'HARDWARE', 'C03', 'CERAMIC FLOOR AND WALL TILES', '5' UNION
	SELECT 'C', 'HARDW AGRIC INDUST', '961', 'HARDWARE', 'C10', 'INDUSTRIAL EXTRACTORS', '5' UNION
	SELECT 'C', 'HARDW AGRIC INDUST', '961', 'HARDWARE', 'C13', 'MATERIALS CONSTRUCTIONS', '5' UNION
	SELECT 'C', 'HARDW AGRIC INDUST', '961', 'HARDWARE', 'C16', 'WAREHOUSE AND SURFACE EQUIPMENT', '5' UNION
	SELECT 'C', 'HARDW AGRIC INDUST', '962', 'ELECTRICAL GENERATORS', 'C20', 'WATER SYSTEMS', '5' UNION
	SELECT '9', 'HOME', '910', 'COOK AND PANTRY', '91A', 'BAKEWARE', '5' UNION
	SELECT '9', 'HOME', '910', 'COOK AND PANTRY', '91B', 'COOKING UTENSILS AND GADGETS', '5' UNION
	SELECT '9', 'HOME', '910', 'COOK AND PANTRY', '91C', 'COOKWARE', '5' UNION
	SELECT '9', 'HOME', '915', 'DINNERWARE', '91D', 'DINNERWARES', '5' UNION
	SELECT '9', 'HOME', '925', 'DECORATIVE ACCESSORIES', '95A', 'ACCENT FURNITURE', '80' UNION
	SELECT '9', 'HOME', '925', 'DECORATIVE ACCESSORIES', '95B', 'CANDLEHOLDERS', '80' UNION
	SELECT '9', 'HOME', '925', 'DECORATIVE ACCESSORIES', '95C', 'DECORATIVE TEXTILES', '80' UNION
	SELECT '9', 'HOME', '925', 'DECORATIVE ACCESSORIES', '95D', 'FLORAL ACCESSORIES', '80' UNION
	SELECT '9', 'HOME', '925', 'DECORATIVE ACCESSORIES', '95E', 'HOME ACCENTS', '80' UNION
	SELECT '9', 'HOME', '925', 'DECORATIVE ACCESSORIES', '95F', 'HOME ORGANIZATION', '80' UNION
	SELECT '9', 'HOME', '925', 'DECORATIVE ACCESSORIES', '95G', 'SCULPTURES', '80' UNION
	SELECT '9', 'HOME', '925', 'DECORATIVE ACCESSORIES', '95H', 'VASES  BOWLS', '80' UNION
	SELECT '9', 'HOME', '925', 'DECORATIVE ACCESSORIES', '95I', 'WALL DECOR/ARTWORK', '80' UNION
	SELECT '9', 'HOME', '905', 'LIGHTING', '90A', 'CEILING LAMPS', '80' UNION
	SELECT '9', 'HOME', '905', 'LIGHTING', '90B', 'FLOOR LAMPS', '80' UNION
	SELECT '9', 'HOME', '905', 'LIGHTING', '90C', 'LIGHTING ACCESORIES', '80' UNION
	SELECT '9', 'HOME', '905', 'LIGHTING', '90D', 'TABLE LAMPS', '80' UNION
	SELECT '9', 'HOME', '925', 'DECORATIVE ACCESSORIES', '95J', 'CURTAINS', '80' UNION
	SELECT '9', 'HOME', '920', 'FLOOR COVERINGS', '92A', 'AREA RUGS LARGE', '81' UNION
	SELECT '9', 'HOME', '920', 'FLOOR COVERINGS', '92B', 'AREA RUGS MEDIUM', '81' UNION
	SELECT '9', 'HOME', '920', 'FLOOR COVERINGS', '92C', 'AREA RUGS SMALL', '81' UNION
	SELECT '9', 'HOME', '920', 'FLOOR COVERINGS', '92D', 'CARPET', '81' UNION
	SELECT '9', 'HOME', '920', 'FLOOR COVERINGS', '92E', 'FLOORING ACCESSORIES', '81' UNION
	SELECT '9', 'HOME', '920', 'FLOOR COVERINGS', '92F', 'LAMINATES SOLID WOOD', '81' UNION
	SELECT '9', 'HOME', '920', 'FLOOR COVERINGS', '92G', 'VINYLFLOOR TILES', '81' UNION
	SELECT 'D', 'INFANTS', '971', 'BABY GOODS', 'D02', 'BABY CHAIRS', '80' UNION
	SELECT 'D', 'INFANTS', '971', 'BABY GOODS', 'D03', 'BABY PRAMS', '80' UNION
	SELECT 'D', 'INFANTS', '971', 'BABY GOODS', 'D05', 'BABY WALKER', '80' UNION
	SELECT 'D', 'INFANTS', '971', 'BABY GOODS', 'D04', 'PLAYARD (PLAYPEN)', '80' UNION
	SELECT 'D', 'INFANTS', '971', 'BABY GOODS', 'D01', 'VARIOUS BABY GOODS', '80' UNION
	SELECT '3', 'MAJOR WHITES', '305', 'FRIDGE', '30A', 'BOTTOM FREEZER', '3' UNION
	SELECT '3', 'MAJOR WHITES', '305', 'FRIDGE', '30B', 'CHEST FREEZER', '3' UNION
	SELECT '3', 'MAJOR WHITES', '305', 'FRIDGE', '30C', 'FROST ONE DOOR', '3' UNION
	SELECT '3', 'MAJOR WHITES', '305', 'FRIDGE', '30D', 'FROST TWO DOORS', '3' UNION
	SELECT '3', 'MAJOR WHITES', '305', 'FRIDGE', '30E', 'NO FROST ONE DOOR', '3' UNION
	SELECT '3', 'MAJOR WHITES', '305', 'FRIDGE', '30F', 'NO FROST TWO DOORS', '3' UNION
	SELECT '3', 'MAJOR WHITES', '305', 'FRIDGE', '30G', 'SHOW CASES AND BOTTLE COOLERS', '3' UNION
	SELECT '3', 'MAJOR WHITES', '305', 'FRIDGE', '30H', 'SIDE BY SIDE', '3' UNION
	SELECT '3', 'MAJOR WHITES', '305', 'FRIDGE', '30I', 'VERTICAL FREEZER', '3' UNION
	SELECT '3', 'MAJOR WHITES', '305', 'FRIDGE', '30J', 'WATER DISPENSER', '3' UNION
	SELECT '3', 'MAJOR WHITES', '310', 'STOVES', '31A', 'ELECTRICAL COOKTOP', '3' UNION
	SELECT '3', 'MAJOR WHITES', '310', 'STOVES', '31B', 'ELECTRICAL PORTABLE COOKER', '3' UNION
	SELECT '3', 'MAJOR WHITES', '310', 'STOVES', '31C', 'ELECTRICAL STOVE LESS THAN 30INCH', '3' UNION
	SELECT '3', 'MAJOR WHITES', '310', 'STOVES', '31D', 'ELECTRICAL STOVE MORE THANEQUAL 30INCH', '3' UNION
	SELECT '3', 'MAJOR WHITES', '310', 'STOVES', '31E', 'ELECTRICAL WALL OVEN', '3' UNION
	SELECT '3', 'MAJOR WHITES', '310', 'STOVES', '31F', 'GAS COOKTOP', '3' UNION
	SELECT '3', 'MAJOR WHITES', '310', 'STOVES', '31G', 'GAS PORTABLE COOKER', '3' UNION
	SELECT '3', 'MAJOR WHITES', '310', 'STOVES', '31H', 'GAS STOVE LESS THAN 30INCH', '3' UNION
	SELECT '3', 'MAJOR WHITES', '310', 'STOVES', '31I', 'GAS STOVE MORE THANEQUAL 30INCH', '3' UNION
	SELECT '3', 'MAJOR WHITES', '310', 'STOVES', '31J', 'GAS SYSTEM', '3' UNION
	SELECT '3', 'MAJOR WHITES', '310', 'STOVES', '31K', 'GAS WALL OVEN', '3' UNION
	SELECT '3', 'MAJOR WHITES', '310', 'STOVES', '31L', 'INDUCTION STOVE', '3' UNION
	SELECT '3', 'MAJOR WHITES', '310', 'STOVES', '31M', 'INDUSTRIAL STOVES', '3' UNION
	SELECT '3', 'MAJOR WHITES', '310', 'STOVES', '31N', 'MICROWAVE', '3' UNION
	SELECT '3', 'MAJOR WHITES', '310', 'STOVES', '31O', 'RANGE HOOD', '3' UNION
	SELECT '3', 'MAJOR WHITES', '320', 'VENTILATION AND HEATING', '32C', 'DEHUMIDIFIER', '3' UNION
	SELECT '3', 'MAJOR WHITES', '320', 'VENTILATION AND HEATING', '32E', 'INVERTER MINISPLIT AIR CONDITIONER', '3' UNION
	SELECT '3', 'MAJOR WHITES', '320', 'VENTILATION AND HEATING', '32F', 'MINISPLIT AIR CONDITIONER', '3' UNION
	SELECT '3', 'MAJOR WHITES', '320', 'VENTILATION AND HEATING', '32H', 'PORTABLE AIR CONDITIONER', '3' UNION
	SELECT '3', 'MAJOR WHITES', '320', 'VENTILATION AND HEATING', '32L', 'WINDOW AIR CONDITIONER', '3' UNION
	SELECT '3', 'MAJOR WHITES', '315', 'WASHING MACHINE AND DRYER', '35A', 'DISHWASHERS', '3' UNION
	SELECT '3', 'MAJOR WHITES', '315', 'WASHING MACHINE AND DRYER', '35B', 'DRYERS', '3' UNION
	SELECT '3', 'MAJOR WHITES', '315', 'WASHING MACHINE AND DRYER', '35C', 'FRONT LOAD WASHING MACHINE', '3' UNION
	SELECT '3', 'MAJOR WHITES', '315', 'WASHING MACHINE AND DRYER', '35D', 'TOP LOAD WASHING MACHINE', '3' UNION
	SELECT '3', 'MAJOR WHITES', '315', 'WASHING MACHINE AND DRYER', '35E', 'TWIN TUB WASHING MACHINE', '3' UNION
	SELECT '3', 'MAJOR WHITES', '315', 'WASHING MACHINE AND DRYER', '35F', 'WASHERDRYER COMBOS', '3' UNION
	SELECT '3', 'MAJOR WHITES', '315', 'WASHING MACHINE AND DRYER', '35G', 'WASHING MACHINE OTHERS', '3' UNION
	SELECT '3', 'MAJOR WHITES', '320', 'VENTILATION AND HEATING', '32B', 'CEILING FAN', '5' UNION
	SELECT '3', 'MAJOR WHITES', '320', 'VENTILATION AND HEATING', '32D', 'FLOOR AND TURBO FAN', '5' UNION
	SELECT '3', 'MAJOR WHITES', '320', 'VENTILATION AND HEATING', '32G', 'OTHER VENTILATOR', '5' UNION
	SELECT '3', 'MAJOR WHITES', '320', 'VENTILATION AND HEATING', '32I', 'STAND AND WALL FAN', '5' UNION
	SELECT '3', 'MAJOR WHITES', '320', 'VENTILATION AND HEATING', '32J', 'TOWER FAN', '5' UNION
	SELECT '3', 'MAJOR WHITES', '320', 'VENTILATION AND HEATING', '32K', 'VENTILATION OTHER EQUIPMENT', '5' UNION
	SELECT '3', 'MAJOR WHITES', '320', 'VENTILATION AND HEATING', '32A', 'AIR COOLER', '3' UNION
	SELECT '3', 'MAJOR WHITES', '305', 'FRIDGE', '30K', 'FRIDGE ACCESSORIES', '3' UNION
	SELECT '3', 'MAJOR WHITES', '310', 'STOVES', '31P', 'STOVES ACCESSORIES', '3' UNION
	SELECT '3', 'MAJOR WHITES', '320', 'VENTILATION AND HEATING', '32M', 'VENTILATION AND HEATING ACCESSORIES', '3' UNION
	SELECT '3', 'MAJOR WHITES', '315', 'WASHING MACHINE AND DRYER', '35H', 'WASHING MACHINE AND DRYER ACCESSORIES', '3' UNION
	SELECT '8', 'MATTRESS', '810', 'BEDDING', '81A', 'BEDDING ACCESSORIES', '75' UNION
	SELECT '8', 'MATTRESS', '810', 'BEDDING', '81B', 'DIVAN BASES', '75' UNION
	SELECT '8', 'MATTRESS', '810', 'BEDDING', '81C', 'MATTRESS FOAM', '75' UNION
	SELECT '8', 'MATTRESS', '810', 'BEDDING', '81D', 'MATTRESS SPRING', '75' UNION
	SELECT '8', 'MATTRESS', '810', 'BEDDING', '81E', 'PILLOWS', '75' UNION
	SELECT '8', 'MATTRESS', '810', 'BEDDING', '81F', 'SHEETS AND COMFORTERS', '75' UNION
	SELECT '2', 'OPTICAL', '236', 'CONTACT LENSES', '213', 'CL OTHERS', '8' UNION
	SELECT '2', 'OPTICAL', '236', 'CONTACT LENSES', '211', 'COSMETIC LENSES', '8' UNION
	SELECT '2', 'OPTICAL', '236', 'CONTACT LENSES', '212', 'COSMETIC RX LENSES', '8' UNION
	SELECT '2', 'OPTICAL', '236', 'CONTACT LENSES', '214', 'PROGRESSIVES', '8' UNION
	SELECT '2', 'OPTICAL', '236', 'CONTACT LENSES', '215', 'RIGID', '8' UNION
	SELECT '2', 'OPTICAL', '236', 'CONTACT LENSES', '216', 'SPHERICAL', '8' UNION
	SELECT '2', 'OPTICAL', '236', 'CONTACT LENSES', '217', 'TORIC', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '250', 'BIFOCAL GLASS', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '251', 'BIFOCAL GLASS PHOTOGREY', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '292', 'BIFOCAL HI INDEX CLEAR 167', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '293', 'BIFOCAL HI INDEX CLEAR 17', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '294', 'BIFOCAL HI INDEX PHOTOCHROMATIC 167', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '295', 'BIFOCAL HI INDEX PHOTOCHROMATIC 17', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '252', 'BIFOCAL PLASTIC AR PWR 1', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '253', 'BIFOCAL PLASTIC PHOTOCROMATIC', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '254', 'BIFOCAL PLASTIC PWR 1', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '255', 'BIFOCAL POLY', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '256', 'BIFOCAL POLY AR', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '257', 'BIFOCAL POLY PHOTOCROMATIC', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '258', 'BIFOCAL POLY PHOTOCROMATIC AR', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '259', 'PHOTOCROMATIC PLASTIC BIFOCAL AR', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '260', 'PROGRESSIVE GLASS', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '261', 'PROGRESSIVE GLASS PHOTOGREY', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '296', 'PROGRESSIVE HI INDEX CLEAR 167', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '297', 'PROGRESSIVE HI INDEX CLEAR 17', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '298', 'PROGRESSIVE HI INDEX PHOTOCHROMATIC 167', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '299', 'PROGRESSIVE HI INDEX PHOTOCHROMATIC 17', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '262', 'PROGRESSIVE PLASTIC', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '263', 'PROGRESSIVE PLASTIC AR', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '264', 'PROGRESSIVE PLASTIC PHOTOCROMATIC', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '265', 'PROGRESSIVE PLASTIC PHOTOCROMATIC AR', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '266', 'PROGRESSIVE POLY', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '267', 'PROGRESSIVE POLY AR', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '268', 'PROGRESSIVE POLY PHOTOCROMATIC', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '269', 'PROGRESSIVE POLY PHOTOCROMATIC AR', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '270', 'SINGLE VISION GLASS', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '271', 'SINGLE VISION GLASS PHOTOGREY', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '288', 'SINGLE VISION HI INDEX CLEAR 167', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '289', 'SINGLE VISION HI INDEX CLEAR 17', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '290', 'SINGLE VISION HI INDEX PHOTOCHROMATIC 167', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '291', 'SINGLE VISION HI INDEX PHOTOCHROMATIC 17', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '272', 'SINGLE VISION PLASTIC AR PWR 1', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '273', 'SINGLE VISION PLASTIC AR PWR 2', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '274', 'SINGLE VISION PLASTIC PHOTOCROMATIC AR PWR 1', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '275', 'SINGLE VISION PLASTIC PHOTOCROMATIC AR PWR 2', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '276', 'SINGLE VISION PLASTIC PHOTOCROMATIC PWR 1', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '277', 'SINGLE VISION PLASTIC PHOTOCROMATIC PWR 2', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '278', 'SINGLE VISION PLASTIC PWR 1', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '279', 'SINGLE VISION PLASTIC PWR 2', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '280', 'SINGLE VISION POLY AR PWR 1', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '281', 'SINGLE VISION POLY AR PWR 2', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '282', 'SINGLE VISION POLY PHOTOCROMATIC AR PWR 1', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '283', 'SINGLE VISION POLY PHOTOCROMATIC AR PWR 2', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '284', 'SINGLE VISION POLY PHOTOCROMATIC PWR 1', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '285', 'SINGLE VISION POLY PHOTOCROMATIC PWR 2', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '286', 'SINGLE VISION POLY PWR 1', '8' UNION
	SELECT '2', 'OPTICAL', '239', 'LENSES', '287', 'SINGLE VISION POLY PWR 2', '8' UNION
	SELECT '2', 'OPTICAL', '234', 'OPTICAL ACCESSORIES', '206', 'AC OTHERS', '8' UNION
	SELECT '2', 'OPTICAL', '234', 'OPTICAL ACCESSORIES', '201', 'CASES', '8' UNION
	SELECT '2', 'OPTICAL', '234', 'OPTICAL ACCESSORIES', '202', 'CONTACT LENS SOLUTIONS', '8' UNION
	SELECT '2', 'OPTICAL', '234', 'OPTICAL ACCESSORIES', '203', 'HANGERS', '8' UNION
	SELECT '2', 'OPTICAL', '234', 'OPTICAL ACCESSORIES', '204', 'MICROFIBERS', '8' UNION
	SELECT '2', 'OPTICAL', '234', 'OPTICAL ACCESSORIES', '205', 'OTHER CLEANING LIQUIDS', '8' UNION
	SELECT '2', 'OPTICAL', '234', 'OPTICAL ACCESSORIES', '20A', 'READING GLASSES', '8' UNION
	SELECT '2', 'OPTICAL', '237', 'PREMIUM FRAMES', '218', 'PF ADULT UNISEX', '8' UNION
	SELECT '2', 'OPTICAL', '237', 'PREMIUM FRAMES', '219', 'PF BOYS', '8' UNION
	SELECT '2', 'OPTICAL', '237', 'PREMIUM FRAMES', '220', 'PF GIRLS', '8' UNION
	SELECT '2', 'OPTICAL', '237', 'PREMIUM FRAMES', '221', 'PF KIDS UNISEX', '8' UNION
	SELECT '2', 'OPTICAL', '237', 'PREMIUM FRAMES', '222', 'PF MEN', '8' UNION
	SELECT '2', 'OPTICAL', '237', 'PREMIUM FRAMES', '223', 'PF WOMEN', '8' UNION
	SELECT '2', 'OPTICAL', '238', 'REGULAR FRAMES', '227', 'RF ADULT UNISEX', '8' UNION
	SELECT '2', 'OPTICAL', '238', 'REGULAR FRAMES', '228', 'RF BOYS', '8' UNION
	SELECT '2', 'OPTICAL', '238', 'REGULAR FRAMES', '229', 'RF GIRLS', '8' UNION
	SELECT '2', 'OPTICAL', '238', 'REGULAR FRAMES', '241', 'RF KIDS UNISEX', '8' UNION
	SELECT '2', 'OPTICAL', '238', 'REGULAR FRAMES', '247', 'RF MEN', '8' UNION
	SELECT '2', 'OPTICAL', '238', 'REGULAR FRAMES', '249', 'RF WOMEN', '8' UNION
	SELECT '2', 'OPTICAL', '235', 'SUNGLASSES', '207', 'KIDS', '8' UNION
	SELECT '2', 'OPTICAL', '235', 'SUNGLASSES', '208', 'SN MEN', '8' UNION
	SELECT '2', 'OPTICAL', '235', 'SUNGLASSES', '210', 'SN WOMEN', '8' UNION
	SELECT '2', 'OPTICAL', '235', 'SUNGLASSES', '209', 'UNISEX', '8' UNION
	SELECT '13', 'REPOSSESSED GOODS', '131', 'REPO PCS', '13Z', 'REPO PC''S GOODS', '25' UNION
	SELECT '13', 'REPOSSESSED GOODS', '132', 'REPO FURNITURE', '13Y', 'REPO FURNITURE GOODS', '85' UNION
	SELECT '13', 'REPOSSESSED GOODS', '133', 'REPO ELECTRICAL', '13X', 'REPO ELEC GOODS', '15' UNION
	SELECT '4', 'SDA', '405', 'SMALL APPLIANCES', '40W', 'VACUUM CLEANERS', '3' UNION
	SELECT '4', 'SDA', '415', 'PERSONAL CARE', '45A', 'GROOMING CLIPPER AND TRIMMER', '5' UNION
	SELECT '4', 'SDA', '415', 'PERSONAL CARE', '45B', 'IRON STRAIGHTENER AND CURLS', '5' UNION
	SELECT '4', 'SDA', '415', 'PERSONAL CARE', '45C', 'MASSAGERS', '5' UNION
	SELECT '4', 'SDA', '415', 'PERSONAL CARE', '45D', 'PERSONAL CARE COMBOS', '5' UNION
	SELECT '4', 'SDA', '415', 'PERSONAL CARE', '45E', 'PERSONAL CARE DRYER', '5' UNION
	SELECT '4', 'SDA', '415', 'PERSONAL CARE', '45F', 'PERSONAL CARE OTHERS', '5' UNION
	SELECT '4', 'SDA', '415', 'PERSONAL CARE', '45G', 'SHAVERS AND EPILATORS', '5' UNION
	SELECT '4', 'SDA', '410', 'SEWING MACHINES', '41A', 'ELECTRIC', '5' UNION
	SELECT '4', 'SDA', '410', 'SEWING MACHINES', '41B', 'INDUSTRIAL', '5' UNION
	SELECT '4', 'SDA', '410', 'SEWING MACHINES', '41C', 'MANUAL', '5' UNION
	SELECT '4', 'SDA', '410', 'SEWING MACHINES', '41D', 'SEWING MACHINE ACCESSORIES', '5' UNION
	SELECT '4', 'SDA', '405', 'SMALL APPLIANCES', '40A', 'BLENDERS', '5' UNION
	SELECT '4', 'SDA', '405', 'SMALL APPLIANCES', '40B', 'CITRUS JUICER', '5' UNION
	SELECT '4', 'SDA', '405', 'SMALL APPLIANCES', '40C', 'COFFEE MAKERS', '5' UNION
	SELECT '4', 'SDA', '405', 'SMALL APPLIANCES', '40D', 'ELECTRIC GRILL', '5' UNION
	SELECT '4', 'SDA', '405', 'SMALL APPLIANCES', '40E', 'ELECTRIC SKILLET', '5' UNION
	SELECT '4', 'SDA', '405', 'SMALL APPLIANCES', '40F', 'FOOD PREPARATIONS', '5' UNION
	SELECT '4', 'SDA', '405', 'SMALL APPLIANCES', '40G', 'FOOD PROCESSOR', '5' UNION
	SELECT '4', 'SDA', '405', 'SMALL APPLIANCES', '40H', 'FRYER', '5' UNION
	SELECT '4', 'SDA', '405', 'SMALL APPLIANCES', '40I', 'FRYERS AND GRILLS', '5' UNION
	SELECT '4', 'SDA', '405', 'SMALL APPLIANCES', '40J', 'IRONS', '5' UNION
	SELECT '4', 'SDA', '405', 'SMALL APPLIANCES', '40K', 'JUICE EXTRACTOR', '5' UNION
	SELECT '4', 'SDA', '405', 'SMALL APPLIANCES', '40L', 'KETTLES', '5' UNION
	SELECT '4', 'SDA', '405', 'SMALL APPLIANCES', '40M', 'MISCELLANEOUS', '5' UNION
	SELECT '4', 'SDA', '405', 'SMALL APPLIANCES', '40N', 'MIXER', '5' UNION
	SELECT '4', 'SDA', '405', 'SMALL APPLIANCES', '40O', 'PRESSURE COOKER', '5' UNION
	SELECT '4', 'SDA', '405', 'SMALL APPLIANCES', '40P', 'RICE COOKER', '5' UNION
	SELECT '4', 'SDA', '405', 'SMALL APPLIANCES', '40Q', 'SANDWICH MAKER', '5' UNION
	SELECT '4', 'SDA', '405', 'SMALL APPLIANCES', '40R', 'SDA COMBOS', '5' UNION
	SELECT '4', 'SDA', '405', 'SMALL APPLIANCES', '40S', 'SEALER', '5' UNION
	SELECT '4', 'SDA', '405', 'SMALL APPLIANCES', '40T', 'SLOW COOKER', '5' UNION
	SELECT '4', 'SDA', '405', 'SMALL APPLIANCES', '40U', 'TOASTER OVEN', '5' UNION
	SELECT '4', 'SDA', '405', 'SMALL APPLIANCES', '40V', 'TOASTERS', '5' UNION
	SELECT '4', 'SDA', '405', 'SMALL APPLIANCES', '40X', 'WAFFLES MAKERS', '5' UNION
	SELECT '12', 'SPARE PARTS', '121', 'SPARE PARTS FOR ELECTRICAL', '12X', 'E SPARE PARTS', '20' UNION
	SELECT '12', 'SPARE PARTS', '122', 'SPARE PARTS FOR FURNITURE', '12Y', 'F SPARE PARTS', '20' UNION
	SELECT '6', 'SPECIALTIES', '630', 'TOYS', '61D', 'DRONES', '1' UNION
	SELECT '6', 'SPECIALTIES', '645', 'INDIVIDUAL SPORT', '60K', 'FITNESS', '5' UNION
	SELECT '6', 'SPECIALTIES', '640', 'OUTDOOR SPORT', '60C', 'BARBEQUES', '5' UNION
	SELECT '6', 'SPECIALTIES', '640', 'OUTDOOR SPORT', '61M', 'BICYCLES EQUAL OR LESS THAN 20', '5' UNION
	SELECT '6', 'SPECIALTIES', '640', 'OUTDOOR SPORT', '657', 'BICYCLES MORE THAN 20', '5' UNION
	SELECT '6', 'SPECIALTIES', '640', 'OUTDOOR SPORT', '658', 'COOLER', '5' UNION
	SELECT '6', 'SPECIALTIES', '640', 'OUTDOOR SPORT', '60B', 'MOTOR BIKES', '5' UNION
	SELECT '6', 'SPECIALTIES', '640', 'OUTDOOR SPORT', '667', 'OTHERS', '5' UNION
	SELECT '6', 'SPECIALTIES', '640', 'OUTDOOR SPORT', '60O', 'PROFESSIONAL BIKES', '5' UNION
	SELECT '6', 'SPECIALTIES', '640', 'OUTDOOR SPORT', '661', 'SWIMMING POOLS', '5' UNION
	SELECT '6', 'SPECIALTIES', '630', 'TOYS', '60Z', 'ESCALE HOUSES', '5' UNION
	SELECT '6', 'SPECIALTIES', '630', 'TOYS', '60Y', 'MISCELLANEOUS TOYS', '5' UNION
	SELECT '6', 'SPECIALTIES', '630', 'TOYS', '60X', 'RIDES', '5' UNION
	SELECT '6', 'SPECIALTIES', '630', 'TOYS', '60W', 'TOY FOR BOYS', '5' UNION
	SELECT '6', 'SPECIALTIES', '630', 'TOYS', '60V', 'TOY FOR GIRLS', '5' UNION

	--Non-stock hierarchy
	SELECT 'R', 'DISCOUNTS', 'RR4', 'DISCOUNTS ELECTRICAL', 'DED', 'DS ELEC DAMAGE', '36' UNION
	SELECT 'R', 'DISCOUNTS', 'RR4', 'DISCOUNTS ELECTRICAL', 'DEC', 'DS ELEC COMPETITION', '37' UNION
	SELECT 'R', 'DISCOUNTS', 'RR4', 'DISCOUNTS ELECTRICAL', 'DEO', 'DS ELEC OTHER', '38' UNION
	SELECT 'R', 'DISCOUNTS', 'RR4', 'DISCOUNTS ELECTRICAL', 'DEEC', 'DS ELEC E-COMMERCE', '38' UNION
	SELECT 'R', 'DISCOUNTS', 'RR4', 'DISCOUNTS ELECTRICAL', 'DES', 'DISCOUNT ELEC STAFF', '46' UNION
	SELECT 'R', 'DISCOUNTS', 'RR4', 'DISCOUNTS ELECTRICAL', 'DEM', 'DS ELEC MANAGEMENT', '47' UNION
	SELECT 'R', 'DISCOUNTS', 'RR4', 'DISCOUNTS ELECTRICAL', 'DWD', 'DS WKST DAMAGE', '36' UNION
	SELECT 'R', 'DISCOUNTS', 'RR4', 'DISCOUNTS ELECTRICAL', 'DWC', 'DS WKST COMPETITION', '37' UNION
	SELECT 'R', 'DISCOUNTS', 'RR4', 'DISCOUNTS ELECTRICAL', 'DWO', 'DS WKST OTHER', '38' UNION
	SELECT 'R', 'DISCOUNTS', 'RR4', 'DISCOUNTS ELECTRICAL', 'DWEC', 'DS W/STATION E-COMMERCE', '38' UNION
	SELECT 'R', 'DISCOUNTS', 'RR4', 'DISCOUNTS ELECTRICAL', 'DWS', 'DS WKST STAFF', '46' UNION
	SELECT 'R', 'DISCOUNTS', 'RR4', 'DISCOUNTS ELECTRICAL', 'DWM', 'DS WKST MANAGEMENT', '47' UNION
	SELECT 'R', 'DISCOUNTS', 'RR3', 'DISCOUNTS FURNITURE', 'DFM', 'DS FURN MANAGEMENT', '48' UNION
	SELECT 'R', 'DISCOUNTS', 'RR3', 'DISCOUNTS FURNITURE', 'DFS', 'DS FURN STAFF', '48' UNION
	SELECT 'R', 'DISCOUNTS', 'RR3', 'DISCOUNTS FURNITURE', 'DFD', 'DS FURN DAMAGE', '86' UNION
	SELECT 'R', 'DISCOUNTS', 'RR3', 'DISCOUNTS FURNITURE', 'DFC', 'DS FURN COMPETITION', '87' UNION
	SELECT 'R', 'DISCOUNTS', 'RR3', 'DISCOUNTS FURNITURE', 'DFO', 'DS FURN OTHER', '88' UNION
	SELECT 'R', 'DISCOUNTS', 'RR3', 'DISCOUNTS FURNITURE', 'DFEC', 'DS FURN E-COMMERCE', '88' UNION
	SELECT 'R', 'DISCOUNTS', 'RR2', 'DISCOUNTS OTHER', 'DS', 'DISCOUNT KIT CODES', '37' UNION
	SELECT 'R', 'DISCOUNTS', 'RR1', 'DISCOUNT SPARES', '7DIS', 'DISCOUNT ON SPARES', '20' UNION
	SELECT 'R', 'DISCOUNTS', 'RR2', 'DISCOUNTS OTHER', 'CDS', 'DISCOUNT-SALE', '49' UNION
	SELECT 'R', 'DISCOUNTS', 'RR2', 'DISCOUNTS OTHER', 'TDE1', 'DISCOUNT FOR $2 000', '92' UNION
	SELECT 'R', 'DISCOUNTS', 'RR2', 'DISCOUNTS OTHER', 'TDE2', 'DISCOUNT OF $5000', '92' UNION
	SELECT 'R', 'DISCOUNTS', 'RR2', 'DISCOUNTS OTHER', 'TDE3', 'DISCOUNT OF $10 000', '92' UNION
	SELECT 'T', 'DV CASH LOAN', 'TT1', 'DP CASH LOAN', 'T1A', 'CL CASH LOAN', '76' UNION
	SELECT 'U', 'INSTALLATION', 'UU2', 'INSTALLATION ELECTRICAL', 'U2A', 'AC INSTALLATION 12000BTU', '93' UNION
	SELECT 'U', 'INSTALLATION', 'UU2', 'INSTALLATION ELECTRICAL', 'U2B', 'AC INSTALLATION 18 TO 24000BTU', '93' UNION
	SELECT 'U', 'INSTALLATION', 'UU2', 'INSTALLATION ELECTRICAL', 'U2C', 'AC INSTALLATION 9000BTU', '93' UNION
	SELECT 'U', 'INSTALLATION', 'UU1', 'INSTALLATION GENERIC', 'U1A', 'INSTALLATION CHARGE', '93' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A107', 'M/COMP 3PARTY H/BUS PRIV%', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A168', 'M/3RD PARTY H/BUS 15 SEAT', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A186', 'M/COMP MCYCL FLAT RATE L1', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A187', 'MOTOR COMPREHENSIVE 1', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A188', 'MOTOR COMPREHENSIVE 2', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A189', 'MOTOR COMPREHENSIVE 3', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A282', 'M/COMP MCYCL PRIV 179K L1', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A285', 'M/COMP MCYC PRIV% 172% L1', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A288', 'M/COMP MCYC PRIV% 180K L1', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A291', 'M/COMP MCYC PRIV% 195K L1', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A292', 'M/COMP MCYC PRIV% 200K L1', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A293', 'M/COMP MCYC PRIV% 225K L1', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A294', 'M/COMP MCYC PRIV% 250K L1', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A295', 'M/COMP M/CYC PRIV% 297K', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A296', 'M/COMP MCYC PRIV% 235K', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A297', 'M COMP M/CYCLE PRIV% 208K', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A298', 'M/COMP MCYC PRIV% 218K', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A299', 'M/COMP M/CYCL PRIV% 221K', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A300', 'M/COMP MCYC PRIV% 207K', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A301', 'M/COMM M/CYCL PRIV% 169K', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A302', 'M/COMP MCYCL PRIV% 163K', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A304', 'M/COMP MCYC PRIV% 140K L1', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A305', 'M/COMP MCYC PRIV% 160K L1', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A312', 'M/COMP MCYC PRIV% 170K L1', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A314', 'M/COMP MCYC PRIV% 165K L1', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A316', 'M/COMP MCYC PRIV% 300K L1', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A317', 'M/COMP MCYC PRIV% 190K L1', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A318', 'M/COMP MCYC PRIV% 192K L1', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A319', 'M/COMP M/CYC PRIV% 229K', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A321', 'M/COMP MCYC PRIV% 267K', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A322', 'M/COMP M/CYC PRIV% 232K', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A323', 'M/COMP M/CYC PRIV% 245K', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A324', 'M/COMP M/CYC PRIV% 172K', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A325', 'M/COMP M/CYC PRIV% 239K', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A326', 'M/COMP M/CYC PRIV% 205K', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A327', 'M/COMP M/CYC PRIV% 210K', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A328', 'M/COMP M/CYC PRIV% 262K', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A331', 'M/COMP MCYC PRIV% 239.8K', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A332', 'M/COMP MCYC $360 420 1Y', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'A333', 'M/COMP MCYC 192K 1YR', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW2', 'INSURANCE', 'MSI', 'MOTOR SCOOTER INSURANCE', '51' UNION
	SELECT 'W', 'AFFINITY', 'WW1', 'READY ASSIST', 'RY2S', '24 MONTHS SERVICE PACKAGE STAFF', '11' UNION
	SELECT 'W', 'AFFINITY', 'WW1', 'READY ASSIST', 'RY2', '24 MONTHS SERVICE PACKAGE', '11' UNION
	SELECT 'W', 'AFFINITY', 'WW1', 'READY ASSIST', 'RY3S', '36 MONTHS SERVICE PACKAGE STAFF', '11' UNION
	SELECT 'W', 'AFFINITY', 'WW1', 'READY ASSIST', 'RY3', '36 MONTHS SERVICE PACKAGE', '11' UNION
	SELECT 'W', 'AFFINITY', 'WW1', 'READY ASSIST', 'RY1S', '12 MONTHS SERVICE PACKAGE STAFF', '11' UNION
	SELECT 'W', 'AFFINITY', 'WW1', 'READY ASSIST', 'RY1', '12 MONTHS SERVICE PACKAGE', '11' UNION
	SELECT 'S', 'SERVICE GENERIC', 'SS1', 'SERVICE COURTS', 'S1A', 'PARTS', '20' UNION
	SELECT 'S', 'SERVICE GENERIC', 'SS1', 'SERVICE COURTS', 'S1C', 'LABOUR', '20' UNION
	SELECT 'S', 'SERVICE GENERIC', 'SS2', 'SERVICE NON COURTS', 'S2A', 'NON-STOCKS OTHERS', '20' UNION
	SELECT 'V', 'CHARGES', 'VV2', 'CREDIT CHARGES', 'V2B', 'ADD-TO BALANCE CREDIT', '90' UNION
	SELECT 'V', 'CHARGES', 'VV2', 'CREDIT CHARGES', 'V2C', 'ADD-TO BALANCE', '90' UNION
	SELECT 'V', 'CHARGES', 'VV2', 'CREDIT CHARGES', 'V2D', 'DEFERRED TERMS', '90' UNION
	SELECT 'V', 'CHARGES', 'VV2', 'CREDIT CHARGES', 'V2A', 'REBATE', '39' UNION
	SELECT 'V', 'CHARGES', 'VV5', 'MOBILE PHONE TOP UP', 'V5A', 'GTT CELL POINT CHARGES', '4' UNION
	SELECT 'V', 'CHARGES', 'VV1', 'ADMIN CHARGES', 'V1A', 'BILL OF SALE', '5' UNION
	SELECT 'V', 'CHARGES', 'VV3', 'DELIVERY CHARGES', 'V3A', 'DELIVERY CHARGES', '94' UNION
	SELECT 'V', 'CHARGES', 'VV6', 'VAT', 'V6A', 'VAT', '96' UNION
	SELECT 'V', 'CHARGES', 'VV4', 'MISCELLANEOUS', 'V4A', 'GIFT PURCHASE', '14' UNION
	SELECT 'V', 'CHARGES', 'VV4', 'MISCELLANEOUS', 'V4B', 'NON-STOCKS MISCELLANEOUS', '80' UNION
	SELECT 'V', 'CHARGES', 'VV4', 'MISCELLANEOUS', 'V4C', 'GIFT WRAP CHARGES', '80' UNION
	SELECT 'V', 'CHARGES', 'VV4', 'MISCELLANEOUS', 'V4D', 'A B MUSIC SUPPLIES', '97' UNION
	SELECT 'V', 'CHARGES', 'VV4', 'MISCELLANEOUS', 'V4E', 'ACME', '97' UNION
	SELECT 'V', 'CHARGES', 'VV4', 'MISCELLANEOUS', 'V4F', 'COURTS NETZONE FEES', '97' UNION
	SELECT 'V', 'CHARGES', 'VV4', 'MISCELLANEOUS', 'V4G', 'CITY COLLEGE', '97' UNION
	SELECT 'V', 'CHARGES', 'VV4', 'MISCELLANEOUS', 'V4H', 'ACTIVATION AND SECURITY', '97' UNION
	SELECT 'V', 'CHARGES', 'VV4', 'MISCELLANEOUS', 'V4I', 'SOLUTIONS 2000', '97' UNION
	SELECT 'V', 'CHARGES', 'VV4', 'MISCELLANEOUS', 'V4J', 'EASY INS', '98' UNION
	SELECT 'V', 'CHARGES', 'VV4', 'MISCELLANEOUS', 'V4K', 'GOLD INS', '98' UNION
	SELECT 'V', 'CHARGES', 'VV4', 'MISCELLANEOUS', 'V4L', 'INSURANCE', '98' UNION
	SELECT 'V', 'CHARGES', 'VV4', 'MISCELLANEOUS', 'V4M', '10 PORC PROCESSING FEE', '99'
	
-- Delete HierarchyTag data
IF EXISTS (SELECT 1 FROM Merchandising.HierarchyTag)
BEGIN
	ALTER TABLE [Merchandising].[ProductHierarchy] NOCHECK CONSTRAINT [FK_ProductHierarchy_HierarchyTag]
	ALTER TABLE [Merchandising].[PromotionHierarchy] NOCHECK CONSTRAINT [FK_PromotionHierarchy_HierarchyTag]
	DELETE FROM Merchandising.HierarchyTag
	ALTER TABLE [Merchandising].[ProductHierarchy] CHECK CONSTRAINT [FK_ProductHierarchy_HierarchyTag]
	ALTER TABLE [Merchandising].[PromotionHierarchy] CHECK CONSTRAINT [FK_PromotionHierarchy_HierarchyTag]
END
	
IF EXISTS (SELECT 1 FROM Merchandising.HierarchyLevel)
BEGIN
	ALTER TABLE [Merchandising].[ProductHierarchy] NOCHECK CONSTRAINT [Merchandising_ProductHierarchy_HierarchyLevelId_FK]
	ALTER TABLE [Merchandising].[StockCountHierarchy] NOCHECK CONSTRAINT [FK_Merchandising_StockCountHierarchy_Level]
	ALTER TABLE [Merchandising].[PromotionHierarchy] NOCHECK CONSTRAINT [FK_PromotionHierarchy_HierarchyLevel]
	DELETE FROM Merchandising.HierarchyLevel
	ALTER TABLE [Merchandising].[ProductHierarchy] CHECK CONSTRAINT [Merchandising_ProductHierarchy_HierarchyLevelId_FK]
	ALTER TABLE [Merchandising].[StockCountHierarchy] CHECK CONSTRAINT [FK_Merchandising_StockCountHierarchy_Level]
	ALTER TABLE [Merchandising].[PromotionHierarchy] CHECK CONSTRAINT [FK_PromotionHierarchy_HierarchyLevel]
END

SET IDENTITY_INSERT Merchandising.HierarchyLevel ON
INSERT INTO Merchandising.HierarchyLevel (Id, Name)
VALUES 
	(1, 'Division'),
	(2, 'Department'),
	(3, 'Class')
SET IDENTITY_INSERT Merchandising.HierarchyLevel OFF

DBCC CHECKIDENT ('Merchandising.HierarchyTag', RESEED, 0);

-- Division
SELECT @levelId = id FROM Merchandising.HierarchyLevel WHERE name = 'Division'
 
INSERT INTO Merchandising.HierarchyTag (LevelId, Name, Code)
SELECT DISTINCT @levelId, h.DivisionName, h.DivisionCode
FROM #Hierarchy h
 
-- Department
SELECT @levelId = id FROM Merchandising.HierarchyLevel WHERE name = 'Department'
 
INSERT INTO Merchandising.HierarchyTag (LevelId, Name, Code)
SELECT DISTINCT @levelId, h.DepartmentName, h.DepartmentCode
FROM #Hierarchy h
 
-- Class
SELECT @levelId = id FROM Merchandising.HierarchyLevel WHERE name = 'Class'

INSERT INTO Merchandising.HierarchyTag (LevelId, Name, Code)
SELECT DISTINCT @levelId, h.ClassName, h.ClassCode
FROM #Hierarchy h
 
-- ClassMapping
DELETE FROM Merchandising.ClassMapping
 
DBCC CHECKIDENT ('Merchandising.ClassMapping', RESEED, 0);

INSERT INTO Merchandising.ClassMapping (ClassCode, LegacyCode)
SELECT DISTINCT h.ClassCode, h.LegacyCode 
FROM #Hierarchy h

DROP TABLE #Hierarchy