IF EXISTS (SELECT * FROM sysobjects 
   WHERE NAME = 'CustUnipay'
   )
BEGIN
DROP table CustUnipay
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CustUnipay](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CustId] [nvarchar](20) NOT NULL,
	[UnipayId] [nvarchar](200) NOT NULL,
	[CreatedOn] [datetime] NOT NULL,
	[UpdatedOn] [datetime] NOT NULL,
 CONSTRAINT [PK_CustUnipay] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO 


