//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Blue.Cosacs.Communication.Messages {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bluebridgeltd.com/cosacs/2012/schema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.bluebridgeltd.com/cosacs/2012/schema.xsd", IsNullable=false)]
    public partial class MailMessage {
        
        private From fromField;
        
        private System.Nullable<short> templateIdField;
        
        private string templateNameIdField;
        
        private System.Nullable<bool> overrideUnsubscribeField;
        
        private Mail[] mailsField;
        
        /// <remarks/>
        public From From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> TemplateId {
            get {
                return this.templateIdField;
            }
            set {
                this.templateIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TemplateNameId {
            get {
                return this.templateNameIdField;
            }
            set {
                this.templateNameIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> OverrideUnsubscribe {
            get {
                return this.overrideUnsubscribeField;
            }
            set {
                this.overrideUnsubscribeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Mail[] Mails {
            get {
                return this.mailsField;
            }
            set {
                this.mailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bluebridgeltd.com/cosacs/2012/schema.xsd")]
    public partial class From {
        
        private string fromMailField;
        
        private string fromNameField;
        
        /// <remarks/>
        public string FromMail {
            get {
                return this.fromMailField;
            }
            set {
                this.fromMailField = value;
            }
        }
        
        /// <remarks/>
        public string FromName {
            get {
                return this.fromNameField;
            }
            set {
                this.fromNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bluebridgeltd.com/cosacs/2012/schema.xsd")]
    public partial class KeyValuePair {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bluebridgeltd.com/cosacs/2012/schema.xsd")]
    public partial class Mail {
        
        private From fromField;
        
        private string toField;
        
        private string customerIdField;
        
        private System.Nullable<short> templateIdField;
        
        private string templateNameIdField;
        
        private System.Nullable<bool> overrideUnsubscribeField;
        
        private KeyValuePair[] arrayOfTagsField;
        
        private string subjectField;
        
        /// <remarks/>
        public From From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        public string To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> TemplateId {
            get {
                return this.templateIdField;
            }
            set {
                this.templateIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TemplateNameId {
            get {
                return this.templateNameIdField;
            }
            set {
                this.templateNameIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> OverrideUnsubscribe {
            get {
                return this.overrideUnsubscribeField;
            }
            set {
                this.overrideUnsubscribeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public KeyValuePair[] ArrayOfTags {
            get {
                return this.arrayOfTagsField;
            }
            set {
                this.arrayOfTagsField = value;
            }
        }
        
        /// <remarks/>
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
    }
}
