IF EXISTS (SELECT * FROM SYSOBJECTS 
           WHERE NAME = 'StripTime'
            AND xtype = 'FN')
BEGIN 
DROP FUNCTION dbo.StripTime
END
GO

CREATE FUNCTION StripTime (@date DATETIME)
RETURNS DATETIME
AS
BEGIN
	RETURN(SELECT CAST(FLOOR( CAST( @date AS FLOAT ) ) AS DATETIME))
END
GO