if exists (select * from dbo.sysobjects where id = object_id('dbo.dn_CustomerMailingQuerySave') 
        and OBJECTPROPERTY(id, 'IsProcedure') = 1)
drop procedure dbo.dn_CustomerMailingQuerySave
GO

SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

CREATE PROCEDURE dn_CustomerMailingQuerySave
   @EmpeenoSave 	int,
	 @datesaved 	datetime,
	 @QueryName 	varchar(128),
	 @CustomerCodeSet 	varchar(64),
	 @NoCustomerCodeSet 	varchar(64),
	 @AccountCodeSet 	varchar(64),
	 @NoAccountCodeSet 	varchar(64),
	 @ArrearsRestriction 	varchar(4),
	 @Arrears 	money,
	 @maxcurrstatus	char(1),
	 @maxeverstatus	char(1),
	 @branchset	varchar(64),
	 @accttypes	varchar(2),
	 @itemset	varchar(64),
	 @itemsetstartdate	datetime,
	 @itemsetenddate 	datetime,
	 @noitemset	varchar(64),
	 @noitemsetstartdate	datetime,
	 @noitemsetenddate	datetime,
	 @itemcatset	varchar(64),
	 @itemCatsetstartdate	datetime,
	 @itemCatsetenddate	datetime,
	 @noitemCatset	varchar(64),
	 @noitemCatsetstartdate	datetime,
	 @noitemCatsetenddate	datetime,
	 @itemsdelivered 	smallint,
	 @itemstartswithset	varchar(64),
	 @itemstartswithstartdate	datetime,
	 @itemstartswithenddate	datetime,
	 @noitemstartswithset	varchar(64),
	 @noitemstartswithstartdate	datetime,
	 @noitemstartswithenddate	datetime,
	 @noletterset	varchar(64),
	 @nolettersetStartdate	datetime,
	 @nolettersetEnddate	datetime,
	 @letterset 	varchar(64),
	 @lettersetstartdate	datetime,
	 @lettersetenddate	datetime,
	 @customerstartage	smallint,
	 @customerEndage	smallint,
	 @totals	char(1),
	 @resulttype	varchar(10),
	 @excludecancellations	smallint,
    @return int OUT



AS 
SET @RETURN = 0

UPDATE CustomerMailingQuery 

SET  EmpeenoSave	 = @EmpeenoSave,
	 datesaved	 = @datesaved,
	 QueryName	 = @QueryName,
	 CustomerCodeSet	 = @CustomerCodeSet,
	 NoCustomerCodeSet	 = @NoCustomerCodeSet,
	 AccountCodeSet	 = @AccountCodeSet,
	 NoAccountCodeSet	 = @NoAccountCodeSet,
	 ArrearsRestriction	 = @ArrearsRestriction,
	 Arrears	 = @Arrears,
	 maxcurrstatus	 = @maxcurrstatus,
	 maxeverstatus	 = @maxeverstatus,
	 branchset	 = @branchset,
	 accttypes	 = @accttypes,
	 itemset	 = @itemset,
	 itemsetstartdate	 = @itemsetstartdate,
	 itemsetenddate	 = @itemsetenddate,
	 noitemset	 = @noitemset,
	 noitemsetstartdate	 = @noitemsetstartdate,
	 noitemsetenddate	 = @noitemsetenddate,
	 itemcatset	 = @itemcatset,
	 itemCatsetstartdate	 = @itemCatsetstartdate,
	 itemCatsetenddate	 = @itemCatsetenddate,
	 noitemCatset	 = @noitemCatset,
	 noitemCatsetstartdate	 = @noitemCatsetstartdate,
	 noitemCatsetenddate	 = @noitemCatsetenddate,
	 itemsdelivered	 = @itemsdelivered,
	 itemstartswithset	 = @itemstartswithset,
	 itemstartswithstartdate	 = @itemstartswithstartdate,
	 itemstartswithenddate	 = @itemstartswithenddate,
	 noitemstartswithset	 = @noitemstartswithset,
	 noitemstartswithstartdate	 = @noitemstartswithstartdate,
	 noitemstartswithenddate	 = @noitemstartswithenddate,
	 noletterset	 = @noletterset,
	 nolettersetStartdate	 = @nolettersetStartdate,
	 nolettersetEnddate	 = @nolettersetEnddate,
	 letterset	 = @letterset,
	 lettersetstartdate	 = @lettersetstartdate,
	 lettersetenddate	 = @lettersetenddate,
	 customerstartage	 = @customerstartage,
	 customerEndage	 = @customerEndage,
	 totals	 = @totals,
	 resulttype	 = @resulttype,
	 excludecancellations	 = @excludecancellations

WHERE 
	( EmpeenoSave	 = @EmpeenoSave AND
	 QueryName	 = @QueryName)
if @@rowcount =0
 INSERT INTO CustomerMailingQuery 
	 ( EmpeenoSave,
	 datesaved,
	 QueryName,
	 CustomerCodeSet,
	 NoCustomerCodeSet,
	 AccountCodeSet,
	 NoAccountCodeSet,
	 ArrearsRestriction,
	 Arrears,
	 maxcurrstatus,
	 maxeverstatus,
	 branchset,
	 accttypes,
	 itemset,
	 itemsetstartdate,
	 itemsetenddate,
	 noitemset,
	 noitemsetstartdate,
	 noitemsetenddate,
	 itemcatset,
	 itemCatsetstartdate,
	 itemCatsetenddate,
	 noitemCatset,
	 noitemCatsetstartdate,
	 noitemCatsetenddate,
	 itemsdelivered,
	 itemstartswithset,
	 itemstartswithstartdate,
	 itemstartswithenddate,
	 noitemstartswithset,
	 noitemstartswithstartdate,
	 noitemstartswithenddate,
	 noletterset,
	 nolettersetStartdate,
	 nolettersetEnddate,
	 letterset,
	 lettersetstartdate,
	 lettersetenddate,
	 customerstartage,
	 customerEndage,
	 totals,
	 resulttype,
	 excludecancellations) 
 
VALUES 
	( @EmpeenoSave,
	 @datesaved,
	 @QueryName,
	 @CustomerCodeSet,
	 @NoCustomerCodeSet,
	 @AccountCodeSet,
	 @NoAccountCodeSet,
	 @ArrearsRestriction,
	 @Arrears,
	 @maxcurrstatus,
	 @maxeverstatus,
	 @branchset,
	 @accttypes,
	 @itemset,
	 @itemsetstartdate,
	 @itemsetenddate,
	 @noitemset,
	 @noitemsetstartdate,
	 @noitemsetenddate,
	 @itemcatset,
	 @itemCatsetstartdate,
	 @itemCatsetenddate,
	 @noitemCatset,
	 @noitemCatsetstartdate,
	 @noitemCatsetenddate,
	 @itemsdelivered,
	 @itemstartswithset,
	 @itemstartswithstartdate,
	 @itemstartswithenddate,
	 @noitemstartswithset,
	 @noitemstartswithstartdate,
	 @noitemstartswithenddate,
	 @noletterset,
	 @nolettersetStartdate,
	 @nolettersetEnddate,
	 @letterset,
	 @lettersetstartdate,
	 @lettersetenddate,
	 @customerstartage,
	 @customerEndage,
	 @totals,
	 @resulttype,
	 @excludecancellations)
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO