IF EXISTS (SELECT * FROM sysobjects 
		   WHERE NAME = 'usp_SCDE_CalculateScore'
		   AND xtype = 'p')
BEGIN
	DROP PROCEDURE usp_SCDE_CalculateScore
END
GO
CREATE PROCEDURE [dbo].[usp_SCDE_CalculateScore]
@customerID  varchar(20),
@accountNo char(12),
@InterceptScore DECIMAL(25,18),
@CustType CHAR(1),
@rl_age DECIMAL(25,18),
@rl_employmentstatus_woe DECIMAL(25,18),
@rl_gender_woe DECIMAL(25,18),
@rl_maritalstatus_woe DECIMAL(25,18),
@rl_mobilenumber_woe DECIMAL(25,18),
@rl_occupation_woe DECIMAL(25,18),
@rl_postcode_woe DECIMAL(25,18),
@rl_residentialstatus_woe DECIMAL(25,18),
@rl_timecurrentemployment DECIMAL(25,18),
@rl_numberdependents DECIMAL(25,18),
@rl_timecurrentaddress DECIMAL(25,18),
@rl_avg_agreement_total_1m_sq DECIMAL(25,18),
@rl_avg_balance_arrears_1m_ln DECIMAL(25,18),
@rl_avg_balance_arrears_12m_ln DECIMAL(25,18),
@rl_balancearrears_pound_6m DECIMAL(25,18),
@rl_balancearrears_pound_6m_ln DECIMAL(25,18),
@rl_count_daysarrear_30more_17m_ln DECIMAL(25,18),
@rl_count_daysarrear_60more_17m_ln DECIMAL(25,18),
@rl_flag_customerstatus_his_woe DECIMAL(25,18),
@rl_daysarrears_pound_6m DECIMAL(25,18),
@rl_max_perc_outs_3m_sq DECIMAL(25,18),
@rl_max_perc_outsarrears_6m_ln DECIMAL(25,18),
@rl_newest_credit_sq DECIMAL(25,18),
@rl_number_account_17m DECIMAL(25,18),
@rl_number_account_opened_3m DECIMAL(25,18),
@rl_number_account_opened_3m_cr DECIMAL(25,18),
@rl_numberdependents_cr DECIMAL(25,18),
@rl_numberdependents_sq DECIMAL(25,18),
@rl_oldest_credit_ln DECIMAL(25,18),
@rl_ratio_ndependent_to_age DECIMAL(25,18),
@rl_ratio_tcurrentemploy_to_age DECIMAL(25,18),
@rl_timecurrentaddress_ln DECIMAL(25,18),
@rl_timecurrentemployment_ln DECIMAL(25,18),
@rl_timecurrentemployment_sr DECIMAL(25,18),
@Return INT OUTPUT
AS
-----------------------------------------------------------------------------------
BEGIN  TRY


	DECLARE @Score INT=0;
		DECLARE @scoreType CHAR(1)=''
		  SELECT * INTO #Equifax_Variable FROM Equifax_Variable 
		  DECLARE @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE CHAR(1)
		 
		  IF(@CustType='E')
			BEGIN 
				SET @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE = 'E'
				SET @scoreType = 'D'
			END 
		ELSE 
			BEGIN 
				SET @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE = 'N'
				SET @scoreType = 'C'
			END 
----------------------------------------------------------------------------------
	DECLARE 	@LOGODDS DECIMAL(25,15) =0.00 

	DECLARE     @INTERCEPTSIGN NVARCHAR(10)='',
				@InterceptValuewithSign float,
				@LOGValue NVARCHAR(10)='',
				@country CHAR(1)

	IF(@scoreType = 'C')
		BEGIN 
			SELECT @INTERCEPTSIGN = VALUE FROM COUNTRYMAINTENANCE WHERE CODENAME='EquifaxAInterceptSign';
			SELECT @LOGValue =		VALUE FROM COUNTRYMAINTENANCE WHERE CODENAME  	='EquifaxALogValue';
		END 

	IF(@scoreType = 'D')
		BEGIN 
			SELECT @INTERCEPTSIGN = VALUE FROM COUNTRYMAINTENANCE WHERE CODENAME ='EquifaxBInterceptSign';
			SELECT @LOGValue = VALUE FROM COUNTRYMAINTENANCE WHERE CODENAME='EquifaxBLogValue';
		END 

	IF(@INTERCEPTSIGN = '+')
		BEGIN 
			SET @InterceptValuewithSign = 0 + @InterceptScore
		END 
	ELSE
		BEGIN 
			SET @InterceptValuewithSign = 0 - @InterceptScore
		END
	select @country=countrycode from country

	
-----------------------------------------------------------------------------------
--***********************************************************************************************

	DECLARE @OCCUPATION_WOE			DECIMAL(25,18) = 0.00,
	@RATIO_TCURRENTEMPLOY_TO_AGE	DECIMAL(25,18) = 0.00,
	@MARITALSTATUS_WOE				DECIMAL(25,18) = 0.00,
	@AGE							DECIMAL(25,18) = 0.00,
	@RESIDENTIALSTATUS_WOE			DECIMAL(25,18) = 0.00,
	@FLAG_CUSTOMERSTATUS_HIS_WOE	DECIMAL(25,18) = 0.00,
	@MOBILENUMBER_WOE				DECIMAL(25,18) = 0.00,
	@RATIO_NDEPENDENT_TO_AGE		DECIMAL(25,18) = 0.00,
	@TIMECURRENTADDRESS				DECIMAL(25,18) = 0.00,
	@TIMECURRENTADDRESS_LN			DECIMAL(25,18) = 0.00,
	@EMPLOYMENTSTATUS_WOE			DECIMAL(25,18) = 0.00,
	@GENDER_WOE						DECIMAL(25,18) = 0.00,
	@POSTCODE_WOE					DECIMAL(25,18) = 0.00,
	@NUMBERDEPENDENTS				DECIMAL(25,18) = 0.00,
	@TIMECURRENTEMPLOYMENT_SR		DECIMAL(25,18) = 0.00,
	@OLDEST_CREDIT_LN				DECIMAL(25,18) = 0.00,
	@TIMECURRENTEMPLOYMENT_LN		DECIMAL(25,18) = 0.00,
	@TIMECURRENTEMPLOYMENT			DECIMAL(25,18) = 0.00,
	@NUMBER_ACCOUNT_OPENED_3M		DECIMAL(25,18) = 0.00,
	@NUMBER_ACCOUNT_OPENED_3M_CR	DECIMAL(25,18) = 0.00,
	@NUMBERDEPENDENTS_SQ			DECIMAL(25,18) = 0.00,
	@NUMBERDEPENDENTS_CR			DECIMAL(25,18) = 0.00,
	@MAX_PERC_OUTS_3M_SQ			DECIMAL(25,18) = 0.00,
	@NEWEST_CREDIT_SQ				DECIMAL(25,18) = 0.00,
	@BALANCEARREARS_POUND_6M_LN		DECIMAL(25,18) = 0.00,
	@BALANCEARREARS_POUND_6M		DECIMAL(25,18) = 0.00,
	@COUNT_DAYSARREAR_60MORE_17M_LN DECIMAL(25,18) = 0.00,
	@COUNT_DAYSARREAR_30MORE_17M_LN DECIMAL(25,18) = 0.00,
	@MAX_PERC_OUTSARREARS_6M_LN		DECIMAL(25,18) = 0.00,
	@NUMBER_ACCOUNT_17M				DECIMAL(25,18) = 0.00,
	@AVG_AGREEMENT_TOTAL_1M_SQ		DECIMAL(25,18) = 0.00,
	@AVG_BALANCE_ARREARS_1M_LN		DECIMAL(25,18) = 0.00,
	@DAYSARREARS_POUND_6M			DECIMAL(25,18) = 0.00,
	@AVG_BALANCE_ARREARS_12M_LN		DECIMAL(25,18) = 0.00,
	@TIMECURRENTADDRESS_WOE			DECIMAL(25,18) = 0.00,
	
	

--  *************************************************** EQUIFAX ***************************

	@EX_OCCUPATION_WOE					DECIMAL(25,18) = ( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='OCCUPATION_WOE' ),
	@EX_RATIO_TCURRENTEMPLOY_TO_AGE		DECIMAL(25,18) = ( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='RATIO_TCURRENTEMPLOY_TO_AGE') ,
	@EX_MARITALSTATUS_WOE				DECIMAL(25,18) = ( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='MARITALSTATUS_WOE' ),
	@EX_AGE								DECIMAL(25,18) = ( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='AGE' ),
	@EX_RESIDENTIALSTATUS_WOE			DECIMAL(25,18) = ( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='RESIDENTIALSTATUS_WOE' ),
	@EX_FLAG_CUSTOMERSTATUS_HIS_WOE		DECIMAL(25,18) = ( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='FLAG_CUSTOMERSTATUS_HIS_WOE' ),
	@EX_MOBILENUMBER_WOE				DECIMAL(25,18) = ( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='MOBILENUMBER_WOE' ),
	@EX_RATIO_NDEPENDENT_TO_AGE			DECIMAL(25,18) = ( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='RATIO_NDEPENDENT_TO_AGE' ),
	@EX_TIMECURRENTADDRESS				DECIMAL(25,18) =	( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='TIMECURRENTADDRESS' ),
	@EX_TIMECURRENTADDRESS_LN			DECIMAL(25,18) =	( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='TIMECURRENTADDRESS_LN' ),
	@EX_EMPLOYMENTSTATUS_WOE			DECIMAL(25,18) = ( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='EMPLOYMENTSTATUS_WOE' ),
	@EX_GENDER_WOE						DECIMAL(25,18) = ( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='GENDER_WOE' ),
	@EX_POSTCODE_WOE					DECIMAL(25,18) = ( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='POSTCODE_WOE' ),
	@EX_NUMBERDEPENDENTS				DECIMAL(25,18) = ( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='NUMBERDEPENDENTS' ),
	@EX_TIMECURRENTEMPLOYMENT_SR		DECIMAL(25,18) =	( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='TIMECURRENTEMPLOYMENT_SR' ),
	@EX_OLDEST_CREDIT_LN				DECIMAL(25,18) = ( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='OLDEST_CREDIT_LN' ),
	@EX_TIMECURRENTEMPLOYMENT_LN		DECIMAL(25,18) = ( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='TIMECURRENTEMPLOYMENT_LN' ),
	@EX_TIMECURRENTEMPLOYMENT			DECIMAL(25,18) =	( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='TIMECURRENTEMPLOYMENT' ),
	@EX_NUMBER_ACCOUNT_OPENED_3M		DECIMAL(25,18) = ( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='NUMBER_ACCOUNT_OPENED_3M' ),
	@EX_NUMBER_ACCOUNT_OPENED_3M_CR		DECIMAL(25,18) = ( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='NUMBER_ACCOUNT_OPENED_3M_CR' ),
	@EX_NUMBERDEPENDENTS_SQ				DECIMAL(25,18) = ( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='NUMBERDEPENDENTS_SQ' ),
	@EX_NUMBERDEPENDENTS_CR				DECIMAL(25,18) = ( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='NUMBERDEPENDENTS_CR' ),
	@EX_MAX_PERC_OUTS_3M_SQ				DECIMAL(25,18) = ( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='MAX_PERC_OUTS_3M_SQ' ),
	@EX_NEWEST_CREDIT_SQ				DECIMAL(25,18) = ( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='NEWEST_CREDIT_SQ' ),
	@EX_BALANCEARREARS_POUND_6M_LN		DECIMAL(25,18) = ( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='BALANCEARREARS_POUND_6M_LN' ),
	@EX_BALANCEARREARS_POUND_6M			DECIMAL(25,18) = ( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='BALANCEARREARS_POUND_6M' ),
	@EX_COUNT_DAYSARREAR_60MORE_17M_LN	DECIMAL(25,18) =	( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='COUNT_DAYSARREAR_60MORE_17M_LN' ),
	@EX_COUNT_DAYSARREAR_30MORE_17M_LN	DECIMAL(25,18) = ( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='COUNT_DAYSARREAR_30MORE_17M_LN' ),
	@EX_MAX_PERC_OUTSARREARS_6M_LN		DECIMAL(25,18) = ( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='MAX_PERC_OUTSARREARS_6M_LN' ),
	@EX_NUMBER_ACCOUNT_17M				DECIMAL(25,18) = ( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='NUMBER_ACCOUNT_17M' ),
	@EX_AVG_AGREEMENT_TOTAL_1M_SQ		DECIMAL(25,18) = ( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='AVG_AGREEMENT_TOTAL_1M_SQ' ),
	@EX_AVG_BALANCE_ARREARS_1M_LN		DECIMAL(25,18) = ( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='AVG_BALANCE_ARREARS_1M_LN' ),
	@EX_DAYSARREARS_POUND_6M			DECIMAL(25,18) = ( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='DAYSARREARS_POUND_6M' ),
	@EX_AVG_BALANCE_ARREARS_12M_LN		DECIMAL(25,18) = ( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='AVG_BALANCE_ARREARS_12M_LN' ),
	@EX_TIMECURRENTADDRESS_WOE			DECIMAL(25,18) = ( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='TIMECURRENTADDRESS' ),
	@EX_FLAG_CUSTOMERSTATUS_HIS_WOE_B	DECIMAL(25,18) = ( SELECT ISNULL(Weightage,0.00) FROM #Equifax_Variable WHERE Flag_CustomerStatus = @VAR_FLAG_CUSTOMERSTATUS_HIS_WOE AND variable ='FLAG_CUSTOMERSTATUS_HIS_WOE' )
------------------------------------------------------------------------------------
--  *************************************************** RULE *************************************************
--	 ***************************** Calculate Variable : Flag Customer Status History;  ******************

	IF(@VAR_FLAG_CUSTOMERSTATUS_HIS_WOE = 'N') 
		BEGIN 
			SET @FLAG_CUSTOMERSTATUS_HIS_WOE = @EX_FLAG_CUSTOMERSTATUS_HIS_WOE * @RL_FLAG_CUSTOMERSTATUS_HIS_WOE;
		END 
	ELSE
		BEGIN 
			SET @FLAG_CUSTOMERSTATUS_HIS_WOE = @EX_FLAG_CUSTOMERSTATUS_HIS_WOE_B * @RL_FLAG_CUSTOMERSTATUS_HIS_WOE;
		END 

-- *************************************** CALCULATE OCCUPATION_WOE (TN, TE ************************* 
	SET @OCCUPATION_WOE					= @EX_OCCUPATION_WOE * @RL_OCCUPATION_WOE;
--	-- *************************************** CALCULATE MARITALSTATUS_WOE (TN,TE *************************  
	SET @MARITALSTATUS_WOE				= @EX_MARITALSTATUS_WOE * @RL_MARITALSTATUS_WOE;
---- *************************************** CALCULATE AGE( TN,TE *************************  
	SET @AGE							= @EX_AGE * @RL_AGE;
---- *************************************** CALCULATE RESIDENTIALSTATUS_WOE (TN,TE  ****************************  
	SET @RESIDENTIALSTATUS_WOE			= @EX_RESIDENTIALSTATUS_WOE * @RL_RESIDENTIALSTATUS_WOE;
---- *************************************** CALCULATE FLAG_CUSTOMERSTATUS_HIS_WOE (TN ***************************  
	SET @FLAG_CUSTOMERSTATUS_HIS_WOE	= @EX_FLAG_CUSTOMERSTATUS_HIS_WOE * @RL_FLAG_CUSTOMERSTATUS_HIS_WOE;
--	--Already calculate.
---- *************************************** CALCULATE MOBILENUMBER_WOE (TN ***************************  
	SET @MOBILENUMBER_WOE				= @EX_MOBILENUMBER_WOE * @RL_MOBILENUMBER_WOE;
---- *************************************** CALCULATE TIMECURRENTADDRESS *************************  
	SET @TIMECURRENTADDRESS				= @EX_TIMECURRENTADDRESS * @RL_TIMECURRENTADDRESS;
---- *************************************** CALCULATE TIMECURRENTADDRESS_LN *****************************  
	SET @TIMECURRENTADDRESS_LN			= @EX_TIMECURRENTADDRESS_LN * @RL_TIMECURRENTADDRESS_LN;
---- *************************************** CALCULATE EMPLOYMENTSTATUS_WOE ******************************** 
	SET @EMPLOYMENTSTATUS_WOE			= @EX_EMPLOYMENTSTATUS_WOE * @RL_EMPLOYMENTSTATUS_WOE;
---- *************************************** CALCULATE GENDER_WOE *********************************  
	SET @GENDER_WOE						= @EX_GENDER_WOE * @RL_GENDER_WOE;
---- *************************************** CALCULATE POSTCODE_WOE ******************************  
	SET @POSTCODE_WOE					= @EX_POSTCODE_WOE * @RL_POSTCODE_WOE;
---- *************************************** CALCULATE NUMBERDEPENDENTS *********************************  
	SET @NUMBERDEPENDENTS				= @EX_NUMBERDEPENDENTS * @RL_NUMBERDEPENDENTS;
---- *************************************** CALCULATE TIMECURRENTEMPLOYMENT_SR ******************************** 
	SET @TIMECURRENTEMPLOYMENT_SR		= @EX_TIMECURRENTEMPLOYMENT_SR * @RL_TIMECURRENTEMPLOYMENT_SR;
---- *************************************** CALCULATE TIMECURRENTEMPLOYMENT **********************************  
	SET @TIMECURRENTEMPLOYMENT			= @EX_TIMECURRENTEMPLOYMENT * @RL_TIMECURRENTEMPLOYMENT;
---- *************************************** CALCULATE TIMECURRENTEMPLOYMENT_LN ********************************  
	SET @TIMECURRENTEMPLOYMENT_LN		= @EX_TIMECURRENTEMPLOYMENT_LN * @RL_TIMECURRENTEMPLOYMENT_LN;
---- *************************************** CALCULATE NUMBER_ACCOUNT_OPENED_3M (TE ******************************  
	SET @NUMBER_ACCOUNT_OPENED_3M		= @EX_NUMBER_ACCOUNT_OPENED_3M * @RL_NUMBER_ACCOUNT_OPENED_3M;
---- *************************************** CALCULATE NUMBER_ACCOUNT_OPENED_3M_CR *****************************  
	SET @NUMBER_ACCOUNT_OPENED_3M_CR	= @EX_NUMBER_ACCOUNT_OPENED_3M_CR * @RL_NUMBER_ACCOUNT_OPENED_3M_CR;
---- *************************************** CALCULATE NUMBERDEPENDENTS_SQ *********************************** ***  
	SET @NUMBERDEPENDENTS_SQ			= @EX_NUMBERDEPENDENTS_SQ * @RL_NUMBERDEPENDENTS_SQ;
---- *************************************** CALCULATE NUMBERDEPENDENTS_CR ****************************  
	SET @NUMBERDEPENDENTS_CR			= @EX_NUMBERDEPENDENTS_CR * @RL_NUMBERDEPENDENTS_CR;
---- ********************************** CALCULATE RATIO_TCURRENTEMPLOY_TO_AGE **************************	
	SET @RATIO_TCURRENTEMPLOY_TO_AGE	= @EX_RATIO_TCURRENTEMPLOY_TO_AGE * @RL_RATIO_TCURRENTEMPLOY_TO_AGE;
---- ********************************** CALCULATE RATIO_NDEPENDENT_TO_AGE ********************************
	SET @RATIO_NDEPENDENT_TO_AGE		= @EX_RATIO_NDEPENDENT_TO_AGE * @RL_RATIO_NDEPENDENT_TO_AGE;
----**************************************CALCULATE OLDEST_CREDIT_LN *********************************************
	SET @OLDEST_CREDIT_LN				= @EX_OLDEST_CREDIT_LN * @RL_OLDEST_CREDIT_LN;
------**************************************************NEWEST_CREDIT_SQ TT BZ***************************************************
	SET @NEWEST_CREDIT_SQ				= @EX_NEWEST_CREDIT_SQ * @RL_NEWEST_CREDIT_SQ;
-----****************************************** COUNT_DAYSARREAR_60MORE_17M_LN (TE **************************  
	SET @COUNT_DAYSARREAR_60MORE_17M_LN  = @EX_COUNT_DAYSARREAR_60MORE_17M_LN * @RL_COUNT_DAYSARREAR_60MORE_17M_LN;
----****************************************** COUNT_DAYSARREAR_30MORE_17M_LN BB*********************************  
	SET @COUNT_DAYSARREAR_30MORE_17M_LN  = @EX_COUNT_DAYSARREAR_30MORE_17M_LN * @RL_COUNT_DAYSARREAR_30MORE_17M_LN;
----***************************************** NUMBER_ACCOUNT_17M BZ *********************************************
	SET @NUMBER_ACCOUNT_17M				= @EX_NUMBER_ACCOUNT_17M * @RL_NUMBER_ACCOUNT_17M;
----************************************************** MAX_PERC_OUTS_3M_SQ (TT BZ *************************  
	SET @MAX_PERC_OUTS_3M_SQ			= @EX_MAX_PERC_OUTS_3M_SQ * @RL_MAX_PERC_OUTS_3M_SQ;

----*************************************************** MAX_PERC_OUTSARREARS_6M_LN  BB ***************************  
	SET @MAX_PERC_OUTSARREARS_6M_LN		= @EX_MAX_PERC_OUTSARREARS_6M_LN * @RL_MAX_PERC_OUTSARREARS_6M_LN;

----*******************************************AVG_AGREEMENT_TOTAL_1M_SQ  BZ ***********************************
	SET @AVG_AGREEMENT_TOTAL_1M_SQ		= @EX_AVG_AGREEMENT_TOTAL_1M_SQ * @RL_AVG_AGREEMENT_TOTAL_1M_SQ;

----******************************************* AVG_BALANCE_ARREARS_1M_LN BZ *******************************  
	SET @AVG_BALANCE_ARREARS_1M_LN		= @EX_AVG_BALANCE_ARREARS_1M_LN * @RL_AVG_BALANCE_ARREARS_1M_LN;

----******************************************* AVG_BALANCE_ARREARS_12M_LN **********************************  
	SET @AVG_BALANCE_ARREARS_12M_LN		= @EX_AVG_BALANCE_ARREARS_12M_LN * @RL_AVG_BALANCE_ARREARS_12M_LN;
----************************************************* BALANCEARREARS_POUND_6M_LN 
	SET @BALANCEARREARS_POUND_6M_LN		= @EX_BALANCEARREARS_POUND_6M_LN * @RL_BALANCEARREARS_POUND_6M_LN;
----************************************************* BALANCEARREARS_POUND_6M
	SET @BALANCEARREARS_POUND_6M		= @EX_BALANCEARREARS_POUND_6M * @RL_BALANCEARREARS_POUND_6M;
----************************************************ DAYSARREARS_POUND_6M bz **********
	SET @DAYSARREARS_POUND_6M			= @EX_DAYSARREARS_POUND_6M * @RL_DAYSARREARS_POUND_6M;
----********************************************* NUMBER_ACCOUNT_OPENED_3M ***
	SET @NUMBER_ACCOUNT_OPENED_3M		= @EX_NUMBER_ACCOUNT_OPENED_3M * @RL_NUMBER_ACCOUNT_OPENED_3M;
----************************************************* NUMBER_ACCOUNT_OPENED_3M_CR *******
	SET @NUMBER_ACCOUNT_OPENED_3M_CR	= @EX_NUMBER_ACCOUNT_OPENED_3M_CR * @RL_NUMBER_ACCOUNT_OPENED_3M_CR;
---------------------------------------------------------------------------------------------------------
	BEGIN

	--select 
	--@InterceptValuewithSign  as 'InterceptValuewithSign'
	--			, @AGE   as 'AGE'
	--			, @Flag_CustomerStatus_His_WOE  as 'Flag_CustomerStatus_His_WOE'
	--			, @OCCUPATION_WOE   as 'OCCUPATION_WOE'
	--			, @MARITALSTATUS_WOE  as 'MARITALSTATUS_WOE'
	--			, @RESIDENTIALSTATUS_WOE  as 'RESIDENTIALSTATUS_WOE'
	--			, @MOBILENUMBER_WOE  as 'MOBILENUMBER_WOE'
	--			, @TIMECURRENTADDRESS    as 'TIMECURRENTADDRESS'
	--			, @TIMECURRENTADDRESS_LN  as 'TIMECURRENTADDRESS_LN'
	--			, @TIMECURRENTADDRESS_WOE   as 'TIMECURRENTADDRESS_WOE'
	--			, @EMPLOYMENTSTATUS_WOE   as 'EMPLOYMENTSTATUS_WOE'
	--			, @GENDER_WOE   as 'GENDER_WOE'
	--			, @POSTCODE_WOE   as 'POSTCODE_WOE'
	--			, @NUMBERDEPENDENTS  as 'NUMBERDEPENDENTS'
	--			, @NUMBERDEPENDENTS_SQ   as 'NUMBERDEPENDENTS_SQ'
	--			, @NUMBERDEPENDENTS_CR  as 'NUMBERDEPENDENTS_CR'
	--			, @TIMECURRENTEMPLOYMENT_SR  as 'TIMECURRENTEMPLOYMENT_SR'
	--			, @TIMECURRENTEMPLOYMENT_LN   as 'TIMECURRENTEMPLOYMENT_LN'
	--			, @TIMECURRENTEMPLOYMENT  as 'TIMECURRENTEMPLOYMENT'
	--			, @RATIO_TCURRENTEMPLOY_TO_AGE  as 'RATIO_TCURRENTEMPLOY_TO_AGE'
	--			, @RATIO_NDEPENDENT_TO_AGE  as 'RATIO_NDEPENDENT_TO_AGE'
	--			, @NUMBER_ACCOUNT_OPENED_3M   as 'NUMBER_ACCOUNT_OPENED_3M'
	--			, @NUMBER_ACCOUNT_OPENED_3M_CR   as 'NUMBER_ACCOUNT_OPENED_3M_CR'
	--			, @OLDEST_CREDIT_LN   as 'OLDEST_CREDIT_LN'
	--			, @NEWEST_CREDIT_SQ  as 'NEWEST_CREDIT_SQ'
	--			, @COUNT_DAYSARREAR_60MORE_17M_LN   as 'COUNT_DAYSARREAR_60MORE_17M_LN'
	--			, @COUNT_DAYSARREAR_30MORE_17M_LN   as 'COUNT_DAYSARREAR_30MORE_17M_LN'
	--			, @NUMBER_ACCOUNT_17M   as 'NUMBER_ACCOUNT_17M'
	--			, @MAX_PERC_OUTS_3M_SQ   as 'MAX_PERC_OUTS_3M_SQ'
	--			, @MAX_PERC_OUTSARREARS_6M_LN   as 'EX_MAX_PERC_OUTSARREARS_6M_LN'
	--			, @AVG_AGREEMENT_TOTAL_1M_SQ   as 'AVG_AGREEMENT_TOTAL_1M_SQ'
	--			, @AVG_BALANCE_ARREARS_1M_LN   as 'AVG_BALANCE_ARREARS_1M_LN'
	--			, @AVG_BALANCE_ARREARS_12M_LN  as 'AVG_BALANCE_ARREARS_12M_LN'
	--			, @BALANCEARREARS_POUND_6M_LN   as 'BALANCEARREARS_POUND_6M_LN'
	--			, @BALANCEARREARS_POUND_6M   as 'BALANCEARREARS_POUND_6M'
	--			, @DAYSARREARS_POUND_6M  as 'DAYSARREARS_POUND_6M'

	
			SET NOCOUNT ON;
			--DECLARE @CHK decimal(25,15)
				--DECLARE @CHK decimal(25,15) = (@InterceptScore
				DECLARE @CHK DECIMAL(25,18) = (
				@InterceptValuewithSign 
				+ @AGE
				+@Flag_CustomerStatus_His_WOE  
				+ @OCCUPATION_WOE 
				+ @MARITALSTATUS_WOE 
				+ @RESIDENTIALSTATUS_WOE
				+ @MOBILENUMBER_WOE
				+ @TIMECURRENTADDRESS 
				+ @TIMECURRENTADDRESS_LN
				+ @TIMECURRENTADDRESS_WOE 
				+ @EMPLOYMENTSTATUS_WOE
				+ @GENDER_WOE 
				+ @POSTCODE_WOE 
				+ @NUMBERDEPENDENTS
				+ @NUMBERDEPENDENTS_SQ 
				+ @NUMBERDEPENDENTS_CR
				+ @TIMECURRENTEMPLOYMENT_SR
				+ @TIMECURRENTEMPLOYMENT_LN 
				+ @TIMECURRENTEMPLOYMENT
				+ @RATIO_TCURRENTEMPLOY_TO_AGE
				+ @RATIO_NDEPENDENT_TO_AGE
				+ @NUMBER_ACCOUNT_OPENED_3M 
				+ @NUMBER_ACCOUNT_OPENED_3M_CR 
				+ @OLDEST_CREDIT_LN 
				+ @NEWEST_CREDIT_SQ
				+ @COUNT_DAYSARREAR_60MORE_17M_LN 
				+ @COUNT_DAYSARREAR_30MORE_17M_LN 
				+ @NUMBER_ACCOUNT_17M
				+ @MAX_PERC_OUTS_3M_SQ 
				+ @MAX_PERC_OUTSARREARS_6M_LN 
				+ @AVG_AGREEMENT_TOTAL_1M_SQ 
				+ @AVG_BALANCE_ARREARS_1M_LN 
				+ @AVG_BALANCE_ARREARS_12M_LN
				+ @BALANCEARREARS_POUND_6M_LN 
				+ @BALANCEARREARS_POUND_6M 
				+ @DAYSARREARS_POUND_6M )

		END		
		
		SET @LOGODDS  = @CHK -  @LOGValue 
		--SELECT @CHK AS '@CHK'
		--SELECT @LOGValue AS 'LOGValue'
		--SELECT @LOGODDS AS 'LOGODDS'
		SET @Score =  round (((exp (@LOGODDS) / (1 + exp (@LOGODDS))) * 1000),0)
		
		IF @Score < 1
			BEGIN
			SET @Score =1
			END
		ELSE IF @Score > 999
			BEGIN
			SET @Score = 999
			END
		ELSE 
			BEGIN
			SET @Score = @Score
			END	
	SET @Return= @Score;
--------------------------------------------------------------------------------
		
		IF EXISTS (SELECT * FROM [dbo].[EquifaxScore] WHERE CustId =@customerID AND AccountNo = @accountNo AND Country = @country AND ScoreCard = @scoreType )
		BEGIN

			UPDATE [dbo].[EquifaxScore]
			SET 
			InterceptScore = @InterceptScore,
			LOGODDS = @LOGODDS,
			[LOG] = @LOGValue,
			SCORE = @SCORE,
			AGE = @AGE,
			OCCUPATION_WOE = @OCCUPATION_WOE,
			MARITALSTATUS_WOE = @MARITALSTATUS_WOE ,
			RESIDENTIALSTATUS_WOE = @RESIDENTIALSTATUS_WOE,
			MOBILENUMBER_WOE = @MOBILENUMBER_WOE,
			TIMECURRENTADDRESS = @TIMECURRENTADDRESS ,
			TIMECURRENTADDRESS_LN = @TIMECURRENTADDRESS_LN,
			TIMECURRENTADDRESS_WOE = @TIMECURRENTADDRESS_WOE,
			EMPLOYMENTSTATUS_WOE =@EMPLOYMENTSTATUS_WOE,
			GENDER_WOE = @GENDER_WOE,
			POSTCODE_WOE = @POSTCODE_WOE ,
			NUMBERDEPENDENTS =@NUMBERDEPENDENTS,
			NUMBERDEPENDENTS_SQ =@NUMBERDEPENDENTS_SQ ,
			NUMBERDEPENDENTS_CR =@NUMBERDEPENDENTS_CR,
			TIMECURRENTEMPLOYMENT_SR =@TIMECURRENTEMPLOYMENT_SR ,
			TIMECURRENTEMPLOYMENT_LN =@TIMECURRENTEMPLOYMENT_LN ,
			TIMECURRENTEMPLOYMENT = @TIMECURRENTEMPLOYMENT ,
			RATIO_TCURRENTEMPLOY_TO_AGE =@RATIO_TCURRENTEMPLOY_TO_AGE,
			RATIO_NDEPENDENT_TO_AGE = @RATIO_NDEPENDENT_TO_AGE,
			NUMBER_ACCOUNT_OPENED_3M =@NUMBER_ACCOUNT_OPENED_3M ,
			NUMBER_ACCOUNT_OPENED_3M_CR =@NUMBER_ACCOUNT_OPENED_3M_CR ,
			OLDEST_CREDIT_LN  =@OLDEST_CREDIT_LN,
			NEWEST_CREDIT_SQ =@NEWEST_CREDIT_SQ,
			COUNT_DAYSARREAR_60MORE_17M_LN =@COUNT_DAYSARREAR_60MORE_17M_LN,
			COUNT_DAYSARREAR_30MORE_17M_LN =@COUNT_DAYSARREAR_30MORE_17M_LN ,
			NUMBER_ACCOUNT_17M =@NUMBER_ACCOUNT_17M ,
			MAX_PERC_OUTS_3M_SQ =@MAX_PERC_OUTS_3M_SQ ,
			MAX_PERC_OUTSARREARS_6M_LN =@MAX_PERC_OUTSARREARS_6M_LN ,
			AVG_AGREEMENT_TOTAL_1M_SQ =@AVG_AGREEMENT_TOTAL_1M_SQ,
			AVG_BALANCE_ARREARS_1M_LN =@AVG_BALANCE_ARREARS_1M_LN ,
			AVG_BALANCE_ARREARS_12M_LN = @AVG_BALANCE_ARREARS_12M_LN,
			BALANCEARREARS_POUND_6M_LN =@BALANCEARREARS_POUND_6M_LN,
			BALANCEARREARS_POUND_6M =@BALANCEARREARS_POUND_6M ,
			DAYSARREARS_POUND_6M  =@DAYSARREARS_POUND_6M,
			FLAG_CUSTOMERSTATUS_HIS_WOE  =@FLAG_CUSTOMERSTATUS_HIS_WOE, 

			RL_AGE =@RL_AGE,
			RL_OCCUPATION_WOE =@RL_OCCUPATION_WOE,
			RL_MARITALSTATUS_WOE =@RL_MARITALSTATUS_WOE,
			RL_RESIDENTIALSTATUS_WOE =@RL_RESIDENTIALSTATUS_WOE,
			RL_MOBILENUMBER_WOE =@RL_MOBILENUMBER_WOE,
			RL_TIMECURRENTADDRESS =@RL_TIMECURRENTADDRESS,
			RL_TIMECURRENTADDRESS_LN =@RL_TIMECURRENTADDRESS_LN,
			--RL_TIMECURRENTADDRESS_WOE =@RL_TIMECURRENTADDRESS_WOE ,
			RL_EMPLOYMENTSTATUS_WOE =@RL_EMPLOYMENTSTATUS_WOE ,
			RL_GENDER_WOE =@RL_GENDER_WOE,
			RL_POSTCODE_WOE =@RL_POSTCODE_WOE,
			RL_NUMBERDEPENDENTS =@RL_NUMBERDEPENDENTS,
			RL_NUMBERDEPENDENTS_SQ =@RL_NUMBERDEPENDENTS_SQ ,
			RL_NUMBERDEPENDENTS_CR =@RL_NUMBERDEPENDENTS_CR ,
			RL_TIMECURRENTEMPLOYMENT_SR =@RL_TIMECURRENTEMPLOYMENT_SR,
			RL_TIMECURRENTEMPLOYMENT_LN  =@RL_TIMECURRENTEMPLOYMENT_LN,
			RL_TIMECURRENTEMPLOYMENT =@RL_TIMECURRENTEMPLOYMENT,
			RL_RATIO_TCURRENTEMPLOY_TO_AGE =@RL_RATIO_TCURRENTEMPLOY_TO_AGE,
			RL_RATIO_NDEPENDENT_TO_AGE =@RL_RATIO_NDEPENDENT_TO_AGE,
			RL_NUMBER_ACCOUNT_OPENED_3M  =@RL_NUMBER_ACCOUNT_OPENED_3M ,
			RL_NUMBER_ACCOUNT_OPENED_3M_CR =@RL_NUMBER_ACCOUNT_OPENED_3M_CR,
			RL_OLDEST_CREDIT_LN =@RL_OLDEST_CREDIT_LN ,
			RL_NEWEST_CREDIT_SQ =@RL_NEWEST_CREDIT_SQ,
			RL_COUNT_DAYSARREAR_60MORE_17M_LN =@RL_COUNT_DAYSARREAR_60MORE_17M_LN ,
			RL_COUNT_DAYSARREAR_30MORE_17M_LN =@RL_COUNT_DAYSARREAR_30MORE_17M_LN,
			RL_NUMBER_ACCOUNT_17M =@RL_NUMBER_ACCOUNT_17M,
			RL_MAX_PERC_OUTS_3M_SQ =@RL_MAX_PERC_OUTS_3M_SQ,
			RL_MAX_PERC_OUTSARREARS_6M_LN =@RL_MAX_PERC_OUTSARREARS_6M_LN ,
			RL_AVG_AGREEMENT_TOTAL_1M_SQ  =@RL_AVG_AGREEMENT_TOTAL_1M_SQ,
			RL_AVG_BALANCE_ARREARS_1M_LN =@RL_AVG_BALANCE_ARREARS_1M_LN,
			RL_AVG_BALANCE_ARREARS_12M_LN =@RL_AVG_BALANCE_ARREARS_12M_LN,
			RL_BALANCEARREARS_POUND_6M_LN =@RL_BALANCEARREARS_POUND_6M_LN,
			RL_BALANCEARREARS_POUND_6M =@RL_BALANCEARREARS_POUND_6M,
			RL_DAYSARREARS_POUND_6M  =@RL_DAYSARREARS_POUND_6M,
			RL_FLAG_CUSTOMERSTATUS_HIS_WOE  =@RL_FLAG_CUSTOMERSTATUS_HIS_WOE,

			EX_AGE =@EX_AGE,
			EX_OCCUPATION_WOE =@EX_OCCUPATION_WOE ,
			EX_MARITALSTATUS_WOE =@EX_MARITALSTATUS_WOE,
			EX_RESIDENTIALSTATUS_WOE =@EX_RESIDENTIALSTATUS_WOE,
			EX_MOBILENUMBER_WOE = @EX_MOBILENUMBER_WOE,
			EX_TIMECURRENTADDRESS =@EX_TIMECURRENTADDRESS,
			EX_TIMECURRENTADDRESS_LN =@EX_TIMECURRENTADDRESS_LN,
			EX_TIMECURRENTADDRESS_WOE = @EX_TIMECURRENTADDRESS_WOE,
			EX_EMPLOYMENTSTATUS_WOE =@EX_EMPLOYMENTSTATUS_WOE,
			EX_GENDER_WOE =@EX_GENDER_WOE,
			EX_POSTCODE_WOE =@EX_POSTCODE_WOE,
			EX_NUMBERDEPENDENTS =@EX_NUMBERDEPENDENTS,
			EX_NUMBERDEPENDENTS_SQ =@EX_NUMBERDEPENDENTS_SQ ,
			EX_NUMBERDEPENDENTS_CR =@EX_NUMBERDEPENDENTS_CR,
			EX_TIMECURRENTEMPLOYMENT_SR =@EX_TIMECURRENTEMPLOYMENT_SR,
			EX_TIMECURRENTEMPLOYMENT_LN =@EX_TIMECURRENTEMPLOYMENT_LN,
			EX_TIMECURRENTEMPLOYMENT =@EX_TIMECURRENTEMPLOYMENT,
			EX_RATIO_TCURRENTEMPLOY_TO_AGE =@EX_RATIO_TCURRENTEMPLOY_TO_AGE,
			EX_RATIO_NDEPENDENT_TO_AGE =@EX_RATIO_NDEPENDENT_TO_AGE,
			EX_NUMBER_ACCOUNT_OPENED_3M =@EX_NUMBER_ACCOUNT_OPENED_3M,
			EX_NUMBER_ACCOUNT_OPENED_3M_CR =@EX_NUMBER_ACCOUNT_OPENED_3M_CR ,
			EX_OLDEST_CREDIT_LN =@EX_OLDEST_CREDIT_LN,
			EX_NEWEST_CREDIT_SQ =@EX_NEWEST_CREDIT_SQ,
			EX_COUNT_DAYSARREAR_60MORE_17M_LN =@EX_COUNT_DAYSARREAR_60MORE_17M_LN ,
			EX_COUNT_DAYSARREAR_30MORE_17M_LN =@EX_COUNT_DAYSARREAR_30MORE_17M_LN,
			EX_NUMBER_ACCOUNT_17M =@EX_NUMBER_ACCOUNT_17M,
			EX_MAX_PERC_OUTS_3M_SQ  =@EX_MAX_PERC_OUTS_3M_SQ,
			EX_MAX_PERC_OUTSARREARS_6M_LN  =@EX_MAX_PERC_OUTSARREARS_6M_LN,
			EX_AVG_AGREEMENT_TOTAL_1M_SQ =@EX_AVG_AGREEMENT_TOTAL_1M_SQ,
			EX_AVG_BALANCE_ARREARS_1M_LN =@EX_AVG_BALANCE_ARREARS_1M_LN,
			EX_AVG_BALANCE_ARREARS_12M_LN =@EX_AVG_BALANCE_ARREARS_12M_LN,
			EX_BALANCEARREARS_POUND_6M_LN =@EX_BALANCEARREARS_POUND_6M_LN,
			EX_BALANCEARREARS_POUND_6M =@EX_BALANCEARREARS_POUND_6M,
			EX_DAYSARREARS_POUND_6M =@EX_DAYSARREARS_POUND_6M,
			EX_FLAG_CUSTOMERSTATUS_HIS_WOE =@EX_FLAG_CUSTOMERSTATUS_HIS_WOE,  
			EX_FLAG_CUSTOMERSTATUS_HIS_WOE_B =@EX_FLAG_CUSTOMERSTATUS_HIS_WOE_B, 
			SCOREDATE = GETDATE()
			WHERE CustId =@customerID AND AccountNo = @accountNo AND Country = @country AND ScoreCard = @scoreType

		END
		ELSE
		BEGIN
		
		INSERT INTO [dbo].[EquifaxScore] VALUES (

		@customerID ,
		@accountNo ,
		@country ,
		@scoreType,	
		@InterceptValuewithSign ,
		@LOGODDS ,
		@LOGValue ,
		@Score ,
		@AGE ,
		@OCCUPATION_WOE,
		@MARITALSTATUS_WOE ,
		@RESIDENTIALSTATUS_WOE ,
		@MOBILENUMBER_WOE ,
		@TIMECURRENTADDRESS ,
		@TIMECURRENTADDRESS_LN ,
		@TIMECURRENTADDRESS_WOE ,
		@EMPLOYMENTSTATUS_WOE ,
		@GENDER_WOE ,
		@POSTCODE_WOE ,
		@NUMBERDEPENDENTS ,
		@NUMBERDEPENDENTS_SQ  ,
		@NUMBERDEPENDENTS_CR ,
		@TIMECURRENTEMPLOYMENT_SR ,
		@TIMECURRENTEMPLOYMENT_LN ,
		@TIMECURRENTEMPLOYMENT ,
		@RATIO_TCURRENTEMPLOY_TO_AGE ,
		@RATIO_NDEPENDENT_TO_AGE,
		@NUMBER_ACCOUNT_OPENED_3M  ,
		@NUMBER_ACCOUNT_OPENED_3M_CR  ,
		@OLDEST_CREDIT_LN,
		@NEWEST_CREDIT_SQ,
		@COUNT_DAYSARREAR_60MORE_17M_LN ,
		@COUNT_DAYSARREAR_30MORE_17M_LN ,
		@NUMBER_ACCOUNT_17M ,
		@MAX_PERC_OUTS_3M_SQ  ,
		@MAX_PERC_OUTSARREARS_6M_LN  ,
		@AVG_AGREEMENT_TOTAL_1M_SQ ,
		@AVG_BALANCE_ARREARS_1M_LN  ,
		@AVG_BALANCE_ARREARS_12M_LN,
		@BALANCEARREARS_POUND_6M_LN ,
		@BALANCEARREARS_POUND_6M  ,
		@DAYSARREARS_POUND_6M  ,
		--@Flag_Customerstatus_His_Woe, 
		@RL_AGE ,
		@RL_OCCUPATION_WOE ,
		@RL_MARITALSTATUS_WOE ,
		@RL_RESIDENTIALSTATUS_WOE ,
		@RL_MOBILENUMBER_WOE ,
		@RL_TIMECURRENTADDRESS ,
		@RL_TIMECURRENTADDRESS_LN ,
		@RL_TIMECURRENTADDRESS ,
		@RL_EMPLOYMENTSTATUS_WOE ,
		@RL_GENDER_WOE ,
		@RL_POSTCODE_WOE ,
		@RL_NUMBERDEPENDENTS ,
		@RL_NUMBERDEPENDENTS_SQ  ,
		@RL_NUMBERDEPENDENTS_CR ,
		@RL_TIMECURRENTEMPLOYMENT_SR ,
		@RL_TIMECURRENTEMPLOYMENT_LN  ,
		@RL_TIMECURRENTEMPLOYMENT ,
		@RL_RATIO_TCURRENTEMPLOY_TO_AGE,
		@RL_RATIO_NDEPENDENT_TO_AGE ,
		@RL_NUMBER_ACCOUNT_OPENED_3M  ,
		@RL_NUMBER_ACCOUNT_OPENED_3M_CR ,
		@RL_OLDEST_CREDIT_LN ,
		@RL_NEWEST_CREDIT_SQ ,
		@RL_COUNT_DAYSARREAR_60MORE_17M_LN  ,
		@RL_COUNT_DAYSARREAR_30MORE_17M_LN ,
		@RL_NUMBER_ACCOUNT_17M ,
		@RL_MAX_PERC_OUTS_3M_SQ ,
		@RL_MAX_PERC_OUTSARREARS_6M_LN  ,
		@RL_AVG_AGREEMENT_TOTAL_1M_SQ  ,
		@RL_AVG_BALANCE_ARREARS_1M_LN ,
		@RL_AVG_BALANCE_ARREARS_12M_LN ,
		@RL_BALANCEARREARS_POUND_6M_LN ,
		@RL_BALANCEARREARS_POUND_6M ,
		@RL_DAYSARREARS_POUND_6M  ,
		--@Rl_Flag_Customerstatus_His_Woe, 
		@EX_AGE ,
		@EX_OCCUPATION_WOE ,
		@EX_MARITALSTATUS_WOE ,
		@EX_RESIDENTIALSTATUS_WOE ,
		@EX_MOBILENUMBER_WOE,
		@EX_TIMECURRENTADDRESS ,
		@EX_TIMECURRENTADDRESS_LN ,
		@EX_TIMECURRENTADDRESS_WOE ,
		@EX_EMPLOYMENTSTATUS_WOE ,
		@EX_GENDER_WOE ,
		@EX_POSTCODE_WOE ,
		@EX_NUMBERDEPENDENTS ,
		@EX_NUMBERDEPENDENTS_SQ  ,
		@EX_NUMBERDEPENDENTS_CR ,
		@EX_TIMECURRENTEMPLOYMENT_SR ,
		@EX_TIMECURRENTEMPLOYMENT_LN ,
		@EX_TIMECURRENTEMPLOYMENT ,
		@EX_RATIO_TCURRENTEMPLOY_TO_AGE ,
		@EX_RATIO_NDEPENDENT_TO_AGE ,
		@EX_NUMBER_ACCOUNT_OPENED_3M ,
		@EX_NUMBER_ACCOUNT_OPENED_3M_CR  ,
		@EX_OLDEST_CREDIT_LN ,
		@EX_NEWEST_CREDIT_SQ ,
		@EX_COUNT_DAYSARREAR_60MORE_17M_LN  ,
		@EX_COUNT_DAYSARREAR_30MORE_17M_LN ,
		@EX_NUMBER_ACCOUNT_17M ,
		@EX_MAX_PERC_OUTS_3M_SQ  ,
		@EX_MAX_PERC_OUTSARREARS_6M_LN  ,
		@EX_AVG_AGREEMENT_TOTAL_1M_SQ ,
		@EX_AVG_BALANCE_ARREARS_1M_LN ,
		@EX_AVG_BALANCE_ARREARS_12M_LN ,
		@EX_BALANCEARREARS_POUND_6M_LN ,
		@EX_BALANCEARREARS_POUND_6M ,
		@EX_DAYSARREARS_POUND_6M ,
		GETDATE(),		
		@Flag_Customerstatus_His_Woe,
		@Rl_Flag_Customerstatus_His_Woe,
		@Ex_Flag_Customerstatus_His_Woe, 
		@Ex_Flag_Customerstatus_His_Woe_B
		)
		END
--------------------------------------------------------------------------------
	Select @Score as '@Score'	 
-----------------------------------------------------------------------------------
END  TRY
BEGIN  CATCH
	DECLARE @err_msg VARCHAR(MAX)                                
	SELECT @err_msg =                               
			   'Procedure ' + CONVERT(VARCHAR(50),ERROR_PROCEDURE()) +                                
			   ', Error ' + CONVERT(VARCHAR(50), ERROR_NUMBER()) +                                
			   ', Severity ' + CONVERT(VARCHAR(5), ERROR_SEVERITY()) +                                
			   ', State ' + CONVERT(VARCHAR(5), ERROR_STATE()) +                                 
			   ', Line ' + CONVERT(VARCHAR(5), ERROR_LINE()) +                                 
			   ', ErrorMessage ' +  CONVERT(VARCHAR(8000), ERROR_MESSAGE()) 
	RAISERROR (@err_msg, 16, 1); 
END  CATCH; 
GO