//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.269.
// 
#pragma warning disable 1591

namespace STL.PL.WSStoreCard {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WStoreCardSoap", Namespace="http://schemas.bluebridgeltd.com/cosacs/storecard/2010/11/")]
    public partial class WStoreCard : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private Authentication authenticationValueField;
        
        private System.Threading.SendOrPostCallback AccountUpdateOutstandingBalanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveStoreCardRatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStoreCardRatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback RateInUseOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetAwaitingActivationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerateStoreCardOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WStoreCard() {
            this.Url = global::STL.PL.Properties.Settings.Default.Courts_NET_PL_WSStoreCard_WStoreCard;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public Authentication AuthenticationValue {
            get {
                return this.authenticationValueField;
            }
            set {
                this.authenticationValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AccountUpdateOutstandingBalanceCompletedEventHandler AccountUpdateOutstandingBalanceCompleted;
        
        /// <remarks/>
        public event SaveStoreCardRatesCompletedEventHandler SaveStoreCardRatesCompleted;
        
        /// <remarks/>
        public event GetStoreCardRatesCompletedEventHandler GetStoreCardRatesCompleted;
        
        /// <remarks/>
        public event RateInUseCompletedEventHandler RateInUseCompleted;
        
        /// <remarks/>
        public event SetAwaitingActivationCompletedEventHandler SetAwaitingActivationCompleted;
        
        /// <remarks/>
        public event GenerateStoreCardCompletedEventHandler GenerateStoreCardCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.bluebridgeltd.com/cosacs/storecard/2010/11/AccountUpdateOutstandin" +
            "gBalance", RequestNamespace="http://schemas.bluebridgeltd.com/cosacs/storecard/2010/11/", ResponseNamespace="http://schemas.bluebridgeltd.com/cosacs/storecard/2010/11/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AccountUpdateOutstandingBalance(string acctno) {
            this.Invoke("AccountUpdateOutstandingBalance", new object[] {
                        acctno});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginAccountUpdateOutstandingBalance(string acctno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("AccountUpdateOutstandingBalance", new object[] {
                        acctno}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndAccountUpdateOutstandingBalance(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void AccountUpdateOutstandingBalanceAsync(string acctno) {
            this.AccountUpdateOutstandingBalanceAsync(acctno, null);
        }
        
        /// <remarks/>
        public void AccountUpdateOutstandingBalanceAsync(string acctno, object userState) {
            if ((this.AccountUpdateOutstandingBalanceOperationCompleted == null)) {
                this.AccountUpdateOutstandingBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAccountUpdateOutstandingBalanceOperationCompleted);
            }
            this.InvokeAsync("AccountUpdateOutstandingBalance", new object[] {
                        acctno}, this.AccountUpdateOutstandingBalanceOperationCompleted, userState);
        }
        
        private void OnAccountUpdateOutstandingBalanceOperationCompleted(object arg) {
            if ((this.AccountUpdateOutstandingBalanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AccountUpdateOutstandingBalanceCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.bluebridgeltd.com/cosacs/storecard/2010/11/SaveStoreCardRates", RequestNamespace="http://schemas.bluebridgeltd.com/cosacs/storecard/2010/11/", ResponseNamespace="http://schemas.bluebridgeltd.com/cosacs/storecard/2010/11/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SaveStoreCardRates(StoreCardRate[] Rates) {
            this.Invoke("SaveStoreCardRates", new object[] {
                        Rates});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSaveStoreCardRates(StoreCardRate[] Rates, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SaveStoreCardRates", new object[] {
                        Rates}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndSaveStoreCardRates(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        public void SaveStoreCardRatesAsync(StoreCardRate[] Rates) {
            this.SaveStoreCardRatesAsync(Rates, null);
        }
        
        /// <remarks/>
        public void SaveStoreCardRatesAsync(StoreCardRate[] Rates, object userState) {
            if ((this.SaveStoreCardRatesOperationCompleted == null)) {
                this.SaveStoreCardRatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveStoreCardRatesOperationCompleted);
            }
            this.InvokeAsync("SaveStoreCardRates", new object[] {
                        Rates}, this.SaveStoreCardRatesOperationCompleted, userState);
        }
        
        private void OnSaveStoreCardRatesOperationCompleted(object arg) {
            if ((this.SaveStoreCardRatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveStoreCardRatesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.bluebridgeltd.com/cosacs/storecard/2010/11/GetStoreCardRates", RequestNamespace="http://schemas.bluebridgeltd.com/cosacs/storecard/2010/11/", ResponseNamespace="http://schemas.bluebridgeltd.com/cosacs/storecard/2010/11/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StoreCardRate[] GetStoreCardRates() {
            object[] results = this.Invoke("GetStoreCardRates", new object[0]);
            return ((StoreCardRate[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetStoreCardRates(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetStoreCardRates", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public StoreCardRate[] EndGetStoreCardRates(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((StoreCardRate[])(results[0]));
        }
        
        /// <remarks/>
        public void GetStoreCardRatesAsync() {
            this.GetStoreCardRatesAsync(null);
        }
        
        /// <remarks/>
        public void GetStoreCardRatesAsync(object userState) {
            if ((this.GetStoreCardRatesOperationCompleted == null)) {
                this.GetStoreCardRatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStoreCardRatesOperationCompleted);
            }
            this.InvokeAsync("GetStoreCardRates", new object[0], this.GetStoreCardRatesOperationCompleted, userState);
        }
        
        private void OnGetStoreCardRatesOperationCompleted(object arg) {
            if ((this.GetStoreCardRatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStoreCardRatesCompleted(this, new GetStoreCardRatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.bluebridgeltd.com/cosacs/storecard/2010/11/RateInUse", RequestNamespace="http://schemas.bluebridgeltd.com/cosacs/storecard/2010/11/", ResponseNamespace="http://schemas.bluebridgeltd.com/cosacs/storecard/2010/11/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RateInUse(int id) {
            object[] results = this.Invoke("RateInUse", new object[] {
                        id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRateInUse(int id, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RateInUse", new object[] {
                        id}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndRateInUse(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RateInUseAsync(int id) {
            this.RateInUseAsync(id, null);
        }
        
        /// <remarks/>
        public void RateInUseAsync(int id, object userState) {
            if ((this.RateInUseOperationCompleted == null)) {
                this.RateInUseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRateInUseOperationCompleted);
            }
            this.InvokeAsync("RateInUse", new object[] {
                        id}, this.RateInUseOperationCompleted, userState);
        }
        
        private void OnRateInUseOperationCompleted(object arg) {
            if ((this.RateInUseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RateInUseCompleted(this, new RateInUseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.bluebridgeltd.com/cosacs/storecard/2010/11/SetAwaitingActivation", RequestNamespace="http://schemas.bluebridgeltd.com/cosacs/storecard/2010/11/", ResponseNamespace="http://schemas.bluebridgeltd.com/cosacs/storecard/2010/11/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> SetAwaitingActivation(string acctno) {
            object[] results = this.Invoke("SetAwaitingActivation", new object[] {
                        acctno});
            return ((System.Nullable<bool>)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSetAwaitingActivation(string acctno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SetAwaitingActivation", new object[] {
                        acctno}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Nullable<bool> EndSetAwaitingActivation(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Nullable<bool>)(results[0]));
        }
        
        /// <remarks/>
        public void SetAwaitingActivationAsync(string acctno) {
            this.SetAwaitingActivationAsync(acctno, null);
        }
        
        /// <remarks/>
        public void SetAwaitingActivationAsync(string acctno, object userState) {
            if ((this.SetAwaitingActivationOperationCompleted == null)) {
                this.SetAwaitingActivationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetAwaitingActivationOperationCompleted);
            }
            this.InvokeAsync("SetAwaitingActivation", new object[] {
                        acctno}, this.SetAwaitingActivationOperationCompleted, userState);
        }
        
        private void OnSetAwaitingActivationOperationCompleted(object arg) {
            if ((this.SetAwaitingActivationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetAwaitingActivationCompleted(this, new SetAwaitingActivationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthenticationValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://schemas.bluebridgeltd.com/cosacs/storecard/2010/11/GenerateStoreCard", RequestNamespace="http://schemas.bluebridgeltd.com/cosacs/storecard/2010/11/", ResponseNamespace="http://schemas.bluebridgeltd.com/cosacs/storecard/2010/11/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long GenerateStoreCard() {
            object[] results = this.Invoke("GenerateStoreCard", new object[0]);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGenerateStoreCard(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GenerateStoreCard", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public long EndGenerateStoreCard(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void GenerateStoreCardAsync() {
            this.GenerateStoreCardAsync(null);
        }
        
        /// <remarks/>
        public void GenerateStoreCardAsync(object userState) {
            if ((this.GenerateStoreCardOperationCompleted == null)) {
                this.GenerateStoreCardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateStoreCardOperationCompleted);
            }
            this.InvokeAsync("GenerateStoreCard", new object[0], this.GenerateStoreCardOperationCompleted, userState);
        }
        
        private void OnGenerateStoreCardOperationCompleted(object arg) {
            if ((this.GenerateStoreCardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerateStoreCardCompleted(this, new GenerateStoreCardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.bluebridgeltd.com/cosacs/storecard/2010/11/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.bluebridgeltd.com/cosacs/storecard/2010/11/", IsNullable=false)]
    public partial class Authentication : System.Web.Services.Protocols.SoapHeader {
        
        private string userField;
        
        private int userIdField;
        
        private string cookieField;
        
        private string passwordField;
        
        private string cultureField;
        
        private string countryField;
        
        private string versionField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string Cookie {
            get {
                return this.cookieField;
            }
            set {
                this.cookieField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Culture {
            get {
                return this.cultureField;
            }
            set {
                this.cultureField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.bluebridgeltd.com/cosacs/storecard/2010/11/")]
    public partial class StoreCardRateDetails {
        
        private int idField;
        
        private System.Nullable<int> parentIDField;
        
        private System.Nullable<int> appScoreFromField;
        
        private System.Nullable<int> appScoreToField;
        
        private System.Nullable<decimal> purchaseInterestRateField;
        
        private System.Nullable<short> behaveScoreFromField;
        
        private System.Nullable<short> behaveScoreToField;
        
        private System.Nullable<decimal> creditLimitPercentField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ParentID {
            get {
                return this.parentIDField;
            }
            set {
                this.parentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> AppScoreFrom {
            get {
                return this.appScoreFromField;
            }
            set {
                this.appScoreFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> AppScoreTo {
            get {
                return this.appScoreToField;
            }
            set {
                this.appScoreToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> PurchaseInterestRate {
            get {
                return this.purchaseInterestRateField;
            }
            set {
                this.purchaseInterestRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> BehaveScoreFrom {
            get {
                return this.behaveScoreFromField;
            }
            set {
                this.behaveScoreFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> BehaveScoreTo {
            get {
                return this.behaveScoreToField;
            }
            set {
                this.behaveScoreToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> CreditLimitPercent {
            get {
                return this.creditLimitPercentField;
            }
            set {
                this.creditLimitPercentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.bluebridgeltd.com/cosacs/storecard/2010/11/")]
    public partial class StoreCardRate {
        
        private decimal rateField;
        
        private StoreCardRateDetails[] rateDetailsField;
        
        private bool modifiedField;
        
        private int idField;
        
        private int versionField;
        
        private bool isDeletedField;
        
        private string nameField;
        
        private bool rateFixedField;
        
        private bool isDefaultRateField;
        
        /// <remarks/>
        public decimal Rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
            }
        }
        
        /// <remarks/>
        public StoreCardRateDetails[] RateDetails {
            get {
                return this.rateDetailsField;
            }
            set {
                this.rateDetailsField = value;
            }
        }
        
        /// <remarks/>
        public bool Modified {
            get {
                return this.modifiedField;
            }
            set {
                this.modifiedField = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDeleted {
            get {
                return this.isDeletedField;
            }
            set {
                this.isDeletedField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public bool RateFixed {
            get {
                return this.rateFixedField;
            }
            set {
                this.rateFixedField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDefaultRate {
            get {
                return this.isDefaultRateField;
            }
            set {
                this.isDefaultRateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AccountUpdateOutstandingBalanceCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SaveStoreCardRatesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetStoreCardRatesCompletedEventHandler(object sender, GetStoreCardRatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStoreCardRatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStoreCardRatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StoreCardRate[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StoreCardRate[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void RateInUseCompletedEventHandler(object sender, RateInUseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RateInUseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RateInUseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SetAwaitingActivationCompletedEventHandler(object sender, SetAwaitingActivationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetAwaitingActivationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetAwaitingActivationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Nullable<bool> Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Nullable<bool>)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GenerateStoreCardCompletedEventHandler(object sender, GenerateStoreCardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerateStoreCardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerateStoreCardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591