//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.6421
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Blue.Cosacs.Messages.Warehouse {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bluebridgeltd.com/cosacs/2012/schema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.bluebridgeltd.com/cosacs/2012/schema.xsd", IsNullable=false)]
    public partial class BookingSubmit {
        
        private int idField;
        
        private string recipientField;
        
        private string addressLine1Field;
        
        private string addressLine2Field;
        
        private string addressLine3Field;
        
        private string postCodeField;
        
        private short stockBranchField;
        
        private short receivingLocationField;
        
        private bool receivingLocationFieldSpecified;
        
        private short deliveryBranchField;
        
        private string typeField;
        
        private System.DateTime requestedDateField;
        
        private string sKUField;
        
        private int itemIdField;
        
        private string itemUPCField;
        
        private string productDescriptionField;
        
        private string productBrandField;
        
        private string productModelField;
        
        private string productAreaField;
        
        private string productCategoryField;
        
        private short quantityField;
        
        private int repoItemIdField;
        
        private string commentField;
        
        private string deliveryZoneField;
        
        private string contactInfoField;
        
        private System.DateTime orderedOnField;
        
        private bool damagedField;
        
        private bool assemblyReqField;
        
        private bool expressField;
        
        private string referenceField;
        
        private decimal unitPriceField;
        
        private int createdByField;
        
        private string addressNotesField;
        
        private string fasciaField;
        
        private bool pickUpField;
        
        private System.Nullable<short> salesBranchField;
        
        private string nonStockServiceTypeField;
        
        private string nonStockServiceItemNoField;
        
        private string nonStockServiceDescriptionField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Recipient {
            get {
                return this.recipientField;
            }
            set {
                this.recipientField = value;
            }
        }
        
        /// <remarks/>
        public string AddressLine1 {
            get {
                return this.addressLine1Field;
            }
            set {
                this.addressLine1Field = value;
            }
        }
        
        /// <remarks/>
        public string AddressLine2 {
            get {
                return this.addressLine2Field;
            }
            set {
                this.addressLine2Field = value;
            }
        }
        
        /// <remarks/>
        public string AddressLine3 {
            get {
                return this.addressLine3Field;
            }
            set {
                this.addressLine3Field = value;
            }
        }
        
        /// <remarks/>
        public string PostCode {
            get {
                return this.postCodeField;
            }
            set {
                this.postCodeField = value;
            }
        }
        
        /// <remarks/>
        public short StockBranch {
            get {
                return this.stockBranchField;
            }
            set {
                this.stockBranchField = value;
            }
        }
        
        /// <remarks/>
        public short ReceivingLocation {
            get {
                return this.receivingLocationField;
            }
            set {
                this.receivingLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReceivingLocationSpecified {
            get {
                return this.receivingLocationFieldSpecified;
            }
            set {
                this.receivingLocationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public short DeliveryBranch {
            get {
                return this.deliveryBranchField;
            }
            set {
                this.deliveryBranchField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RequestedDate {
            get {
                return this.requestedDateField;
            }
            set {
                this.requestedDateField = value;
            }
        }
        
        /// <remarks/>
        public string SKU {
            get {
                return this.sKUField;
            }
            set {
                this.sKUField = value;
            }
        }
        
        /// <remarks/>
        public int ItemId {
            get {
                return this.itemIdField;
            }
            set {
                this.itemIdField = value;
            }
        }
        
        /// <remarks/>
        public string ItemUPC {
            get {
                return this.itemUPCField;
            }
            set {
                this.itemUPCField = value;
            }
        }
        
        /// <remarks/>
        public string ProductDescription {
            get {
                return this.productDescriptionField;
            }
            set {
                this.productDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string ProductBrand {
            get {
                return this.productBrandField;
            }
            set {
                this.productBrandField = value;
            }
        }
        
        /// <remarks/>
        public string ProductModel {
            get {
                return this.productModelField;
            }
            set {
                this.productModelField = value;
            }
        }
        
        /// <remarks/>
        public string ProductArea {
            get {
                return this.productAreaField;
            }
            set {
                this.productAreaField = value;
            }
        }
        
        /// <remarks/>
        public string ProductCategory {
            get {
                return this.productCategoryField;
            }
            set {
                this.productCategoryField = value;
            }
        }
        
        /// <remarks/>
        public short Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public int RepoItemId {
            get {
                return this.repoItemIdField;
            }
            set {
                this.repoItemIdField = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        public string DeliveryZone {
            get {
                return this.deliveryZoneField;
            }
            set {
                this.deliveryZoneField = value;
            }
        }
        
        /// <remarks/>
        public string ContactInfo {
            get {
                return this.contactInfoField;
            }
            set {
                this.contactInfoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime OrderedOn {
            get {
                return this.orderedOnField;
            }
            set {
                this.orderedOnField = value;
            }
        }
        
        /// <remarks/>
        public bool Damaged {
            get {
                return this.damagedField;
            }
            set {
                this.damagedField = value;
            }
        }
        
        /// <remarks/>
        public bool AssemblyReq {
            get {
                return this.assemblyReqField;
            }
            set {
                this.assemblyReqField = value;
            }
        }
        
        /// <remarks/>
        public bool Express {
            get {
                return this.expressField;
            }
            set {
                this.expressField = value;
            }
        }
        
        /// <remarks/>
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        public decimal UnitPrice {
            get {
                return this.unitPriceField;
            }
            set {
                this.unitPriceField = value;
            }
        }
        
        /// <remarks/>
        public int CreatedBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
            }
        }
        
        /// <remarks/>
        public string AddressNotes {
            get {
                return this.addressNotesField;
            }
            set {
                this.addressNotesField = value;
            }
        }
        
        /// <remarks/>
        public string Fascia {
            get {
                return this.fasciaField;
            }
            set {
                this.fasciaField = value;
            }
        }
        
        /// <remarks/>
        public bool PickUp {
            get {
                return this.pickUpField;
            }
            set {
                this.pickUpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> SalesBranch {
            get {
                return this.salesBranchField;
            }
            set {
                this.salesBranchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NonStockServiceType {
            get {
                return this.nonStockServiceTypeField;
            }
            set {
                this.nonStockServiceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NonStockServiceItemNo {
            get {
                return this.nonStockServiceItemNoField;
            }
            set {
                this.nonStockServiceItemNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NonStockServiceDescription {
            get {
                return this.nonStockServiceDescriptionField;
            }
            set {
                this.nonStockServiceDescriptionField = value;
            }
        }
    }
}
