//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8689
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Blue.Cosacs.Messages.Warranty {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bluebridgeltd.com/cosacs/2012/schema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.bluebridgeltd.com/cosacs/2012/schema.xsd", IsNullable=false)]
    public partial class SalesOrder {
        
        private string invoiceNumberField;
        
        private short saleBranchField;
        
        private System.DateTime soldOnField;
        
        private SalesOrderSoldBy soldByField;
        
        private System.DateTime deliveredOnField;
        
        private bool secondEffortField;
        
        private Customer customerField;
        
        private Item itemField;
        
        /// <remarks/>
        public string InvoiceNumber {
            get {
                return this.invoiceNumberField;
            }
            set {
                this.invoiceNumberField = value;
            }
        }
        
        /// <remarks/>
        public short SaleBranch {
            get {
                return this.saleBranchField;
            }
            set {
                this.saleBranchField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SoldOn {
            get {
                return this.soldOnField;
            }
            set {
                this.soldOnField = value;
            }
        }
        
        /// <remarks/>
        public SalesOrderSoldBy SoldBy {
            get {
                return this.soldByField;
            }
            set {
                this.soldByField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DeliveredOn {
            get {
                return this.deliveredOnField;
            }
            set {
                this.deliveredOnField = value;
            }
        }
        
        /// <remarks/>
        public bool SecondEffort {
            get {
                return this.secondEffortField;
            }
            set {
                this.secondEffortField = value;
            }
        }
        
        /// <remarks/>
        public Customer Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        public Item Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bluebridgeltd.com/cosacs/2012/schema.xsd")]
    public partial class SalesOrderSoldBy {
        
        private int soldByIdField;
        
        private bool soldByIdFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int SoldById {
            get {
                return this.soldByIdField;
            }
            set {
                this.soldByIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SoldByIdSpecified {
            get {
                return this.soldByIdFieldSpecified;
            }
            set {
                this.soldByIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bluebridgeltd.com/cosacs/2012/schema.xsd")]
    public partial class Warranty {
        
        private int idField;
        
        private short lengthField;
        
        private string numberField;
        
        private decimal taxRateField;
        
        private string departmentField;
        
        private string typeCodeField;
        
        private decimal costPriceField;
        
        private decimal retailPriceField;
        
        private decimal salePriceField;
        
        private string contractNumberField;
        
        private int warrantyGroupIdField;
        
        private System.DateTime effectiveDateField;
        
        private string redeemContractNumberField;
        
        private string reLinkContractNoField;
        
        private System.Nullable<System.DateTime> warrantyDeliveredOnField;
        
        private bool warrantyDeliveredOnFieldSpecified;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public short Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public decimal TaxRate {
            get {
                return this.taxRateField;
            }
            set {
                this.taxRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        public string TypeCode {
            get {
                return this.typeCodeField;
            }
            set {
                this.typeCodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal CostPrice {
            get {
                return this.costPriceField;
            }
            set {
                this.costPriceField = value;
            }
        }
        
        /// <remarks/>
        public decimal RetailPrice {
            get {
                return this.retailPriceField;
            }
            set {
                this.retailPriceField = value;
            }
        }
        
        /// <remarks/>
        public decimal SalePrice {
            get {
                return this.salePriceField;
            }
            set {
                this.salePriceField = value;
            }
        }
        
        /// <remarks/>
        public string ContractNumber {
            get {
                return this.contractNumberField;
            }
            set {
                this.contractNumberField = value;
            }
        }
        
        /// <remarks/>
        public int WarrantyGroupId {
            get {
                return this.warrantyGroupIdField;
            }
            set {
                this.warrantyGroupIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EffectiveDate {
            get {
                return this.effectiveDateField;
            }
            set {
                this.effectiveDateField = value;
            }
        }
        
        /// <remarks/>
        public string RedeemContractNumber {
            get {
                return this.redeemContractNumberField;
            }
            set {
                this.redeemContractNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ReLinkContractNo {
            get {
                return this.reLinkContractNoField;
            }
            set {
                this.reLinkContractNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> WarrantyDeliveredOn {
            get {
                return this.warrantyDeliveredOnField;
            }
            set {
                this.warrantyDeliveredOnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WarrantyDeliveredOnSpecified {
            get {
                return this.warrantyDeliveredOnFieldSpecified;
            }
            set {
                this.warrantyDeliveredOnFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bluebridgeltd.com/cosacs/2012/schema.xsd")]
    public partial class Item {
        
        private int idField;
        
        private short stockLocationField;
        
        private int quantityField;
        
        private string numberField;
        
        private string uPCField;
        
        private decimal priceField;
        
        private decimal costPriceField;
        
        private string descriptionField;
        
        private string supplierField;
        
        private string brandField;
        
        private string modelField;
        
        private string departmentField;
        
        private Warranty[] warrantyField;
        
        private System.Nullable<int> totalQuantityField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public short StockLocation {
            get {
                return this.stockLocationField;
            }
            set {
                this.stockLocationField = value;
            }
        }
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public string UPC {
            get {
                return this.uPCField;
            }
            set {
                this.uPCField = value;
            }
        }
        
        /// <remarks/>
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public decimal CostPrice {
            get {
                return this.costPriceField;
            }
            set {
                this.costPriceField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Supplier {
            get {
                return this.supplierField;
            }
            set {
                this.supplierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Brand {
            get {
                return this.brandField;
            }
            set {
                this.brandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Warranty")]
        public Warranty[] Warranty {
            get {
                return this.warrantyField;
            }
            set {
                this.warrantyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TotalQuantity {
            get {
                return this.totalQuantityField;
            }
            set {
                this.totalQuantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bluebridgeltd.com/cosacs/2012/schema.xsd")]
    public partial class Customer {
        
        private string customerIdField;
        
        private string accountNumberField;
        
        private string accountTypeField;
        
        private string titleField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string homePhoneField;
        
        private string workPhoneField;
        
        private string mobilePhoneField;
        
        private string addressLine1Field;
        
        private string addressLine2Field;
        
        private string addressLine3Field;
        
        private string postCodeField;
        
        private string emailField;
        
        private string notesField;
        
        /// <remarks/>
        public string CustomerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string AccountType {
            get {
                return this.accountTypeField;
            }
            set {
                this.accountTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string HomePhone {
            get {
                return this.homePhoneField;
            }
            set {
                this.homePhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string WorkPhone {
            get {
                return this.workPhoneField;
            }
            set {
                this.workPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MobilePhone {
            get {
                return this.mobilePhoneField;
            }
            set {
                this.mobilePhoneField = value;
            }
        }
        
        /// <remarks/>
        public string AddressLine1 {
            get {
                return this.addressLine1Field;
            }
            set {
                this.addressLine1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddressLine2 {
            get {
                return this.addressLine2Field;
            }
            set {
                this.addressLine2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AddressLine3 {
            get {
                return this.addressLine3Field;
            }
            set {
                this.addressLine3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PostCode {
            get {
                return this.postCodeField;
            }
            set {
                this.postCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bluebridgeltd.com/cosacs/2012/schema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.bluebridgeltd.com/cosacs/2012/schema.xsd", IsNullable=false)]
    public partial class SalesOrderCancel {
        
        private string contractNumberField;
        
        private short saleBranchField;
        
        private string statusField;
        
        private System.Nullable<int> itemQuantityField;
        
        private System.Nullable<bool> isRepossessedField;
        
        private System.DateTime cancelledDateField;
        
        public SalesOrderCancel() {
            this.isRepossessedField = false;
        }
        
        /// <remarks/>
        public string ContractNumber {
            get {
                return this.contractNumberField;
            }
            set {
                this.contractNumberField = value;
            }
        }
        
        /// <remarks/>
        public short SaleBranch {
            get {
                return this.saleBranchField;
            }
            set {
                this.saleBranchField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ItemQuantity {
            get {
                return this.itemQuantityField;
            }
            set {
                this.itemQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public System.Nullable<bool> IsRepossessed {
            get {
                return this.isRepossessedField;
            }
            set {
                this.isRepossessedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CancelledDate {
            get {
                return this.cancelledDateField;
            }
            set {
                this.cancelledDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bluebridgeltd.com/cosacs/2012/schema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.bluebridgeltd.com/cosacs/2012/schema.xsd", IsNullable=false)]
    public partial class SalesOrderCancelItem {
        
        private string accountNumberField;
        
        private string invoiceNumberField;
        
        private short saleBranchField;
        
        private int itemIdField;
        
        private int quantityField;
        
        private System.Nullable<int> totalQuantityField;
        
        /// <remarks/>
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string InvoiceNumber {
            get {
                return this.invoiceNumberField;
            }
            set {
                this.invoiceNumberField = value;
            }
        }
        
        /// <remarks/>
        public short SaleBranch {
            get {
                return this.saleBranchField;
            }
            set {
                this.saleBranchField = value;
            }
        }
        
        /// <remarks/>
        public int ItemId {
            get {
                return this.itemIdField;
            }
            set {
                this.itemIdField = value;
            }
        }
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TotalQuantity {
            get {
                return this.totalQuantityField;
            }
            set {
                this.totalQuantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bluebridgeltd.com/cosacs/2012/schema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.bluebridgeltd.com/cosacs/2012/schema.xsd", IsNullable=false)]
    public partial class PotentialSales {
        
        private string invoiceNumberField;
        
        private short saleBranchField;
        
        private System.DateTime soldOnField;
        
        private int soldByField;
        
        private System.DateTime deliveredOnField;
        
        private bool secondEffortField;
        
        private Customer customerField;
        
        private Item[] itemsField;
        
        private string accountNumberField;
        
        /// <remarks/>
        public string InvoiceNumber {
            get {
                return this.invoiceNumberField;
            }
            set {
                this.invoiceNumberField = value;
            }
        }
        
        /// <remarks/>
        public short SaleBranch {
            get {
                return this.saleBranchField;
            }
            set {
                this.saleBranchField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SoldOn {
            get {
                return this.soldOnField;
            }
            set {
                this.soldOnField = value;
            }
        }
        
        /// <remarks/>
        public int SoldBy {
            get {
                return this.soldByField;
            }
            set {
                this.soldByField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DeliveredOn {
            get {
                return this.deliveredOnField;
            }
            set {
                this.deliveredOnField = value;
            }
        }
        
        /// <remarks/>
        public bool SecondEffort {
            get {
                return this.secondEffortField;
            }
            set {
                this.secondEffortField = value;
            }
        }
        
        /// <remarks/>
        public Customer Customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Items")]
        public Item[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
    }
}
