//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8689
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Blue.Cosacs.Messages.Merchandising.StockAdjustment {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bluebridgeltd.com/cosacs/2012/schema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.bluebridgeltd.com/cosacs/2012/schema.xsd", IsNullable=false)]
    public partial class StockAdjustmentMessage {
        
        private int adjustmentIdField;
        
        private System.DateTime dateCreatedField;
        
        private int locationIdField;
        
        private string salesLocationIdField;
        
        private System.DateTime createdDateField;
        
        private int secondaryReasonField;
        
        private string descriptionField;
        
        private decimal aWCField;
        
        private StockAdjustmentMessageProduct[] productsField;
        
        /// <remarks/>
        public int AdjustmentId {
            get {
                return this.adjustmentIdField;
            }
            set {
                this.adjustmentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DateCreated {
            get {
                return this.dateCreatedField;
            }
            set {
                this.dateCreatedField = value;
            }
        }
        
        /// <remarks/>
        public int LocationId {
            get {
                return this.locationIdField;
            }
            set {
                this.locationIdField = value;
            }
        }
        
        /// <remarks/>
        public string SalesLocationId {
            get {
                return this.salesLocationIdField;
            }
            set {
                this.salesLocationIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        public int SecondaryReason {
            get {
                return this.secondaryReasonField;
            }
            set {
                this.secondaryReasonField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public decimal AWC {
            get {
                return this.aWCField;
            }
            set {
                this.aWCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Product", IsNullable=false)]
        public StockAdjustmentMessageProduct[] Products {
            get {
                return this.productsField;
            }
            set {
                this.productsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bluebridgeltd.com/cosacs/2012/schema.xsd")]
    public partial class StockAdjustmentMessageProduct {
        
        private int idField;
        
        private string typeField;
        
        private string departmentCodeField;
        
        private decimal costField;
        
        private int unitsField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string DepartmentCode {
            get {
                return this.departmentCodeField;
            }
            set {
                this.departmentCodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Cost {
            get {
                return this.costField;
            }
            set {
                this.costField = value;
            }
        }
        
        /// <remarks/>
        public int Units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
            }
        }
    }
}
