//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8689
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Blue.Cosacs.Messages.Merchandising.Transfer
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.bluebridgeltd.com/cosacs/2012/schema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.bluebridgeltd.com/cosacs/2012/schema.xsd", IsNullable = false)]
    public partial class TransferMessage
    {

        private int idField;

        private string typeField;

        private int warehouseLocationIdField;

        private string warehouseLocationSalesIdField;

        private int receivingLocationIdField;

        private string receivingLocationSalesIdField;

        private System.DateTime createdDateField;

        private string descriptionField;

        private decimal aWCField;

        private TransferMessageProduct[] productsField;

        /// <remarks/>
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public int WarehouseLocationId
        {
            get
            {
                return this.warehouseLocationIdField;
            }
            set
            {
                this.warehouseLocationIdField = value;
            }
        }

        /// <remarks/>
        public string WarehouseLocationSalesId
        {
            get
            {
                return this.warehouseLocationSalesIdField;
            }
            set
            {
                this.warehouseLocationSalesIdField = value;
            }
        }

        /// <remarks/>
        public int ReceivingLocationId
        {
            get
            {
                return this.receivingLocationIdField;
            }
            set
            {
                this.receivingLocationIdField = value;
            }
        }

        /// <remarks/>
        public string ReceivingLocationSalesId
        {
            get
            {
                return this.receivingLocationSalesIdField;
            }
            set
            {
                this.receivingLocationSalesIdField = value;
            }
        }

        /// <remarks/>
        public System.DateTime CreatedDate
        {
            get
            {
                return this.createdDateField;
            }
            set
            {
                this.createdDateField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public decimal AWC
        {
            get
            {
                return this.aWCField;
            }
            set
            {
                this.aWCField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Product", IsNullable = false)]
        public TransferMessageProduct[] Products
        {
            get
            {
                return this.productsField;
            }
            set
            {
                this.productsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.bluebridgeltd.com/cosacs/2012/schema.xsd")]
    public partial class TransferMessageProduct
    {

        private int idField;

        private string typeField;

        private string departmentCodeField;

        private decimal costField;

        private int unitsField;

        /// <remarks/>
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public string DepartmentCode
        {
            get
            {
                return this.departmentCodeField;
            }
            set
            {
                this.departmentCodeField = value;
            }
        }

        /// <remarks/>
        public decimal Cost
        {
            get
            {
                return this.costField;
            }
            set
            {
                this.costField = value;
            }
        }

        /// <remarks/>
        public int Units
        {
            get
            {
                return this.unitsField;
            }
            set
            {
                this.unitsField = value;
            }
        }
    }
}
