//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8689
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Blue.Cosacs.Messages.Merchandising.VendorReturn {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bluebridgeltd.com/cosacs/2012/schema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.bluebridgeltd.com/cosacs/2012/schema.xsd", IsNullable=false)]
    public partial class Product {
        
        private int idField;
        
        private string typeField;
        
        private string departmentCodeField;
        
        private float costField;
        
        private int unitsField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string DepartmentCode {
            get {
                return this.departmentCodeField;
            }
            set {
                this.departmentCodeField = value;
            }
        }
        
        /// <remarks/>
        public float Cost {
            get {
                return this.costField;
            }
            set {
                this.costField = value;
            }
        }
        
        /// <remarks/>
        public int Units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bluebridgeltd.com/cosacs/2012/schema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.bluebridgeltd.com/cosacs/2012/schema.xsd", IsNullable=false)]
    public partial class Products {
        
        private Product[] productField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Product")]
        public Product[] Product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bluebridgeltd.com/cosacs/2012/schema.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.bluebridgeltd.com/cosacs/2012/schema.xsd", IsNullable=false)]
    public partial class VendorReturnMessage {
        
        private int vendorReturnIdField;
        
        private string receiptTypeField;
        
        private int locationIdField;
        
        private string salesLocationIdField;
        
        private System.DateTime createdDateField;
        
        private int vendorIdField;
        
        private string vendorTypeField;
        
        private string descriptionField;
        
        private Product[] productsField;
        
        private float totalLandedCostField;
        
        /// <remarks/>
        public int VendorReturnId {
            get {
                return this.vendorReturnIdField;
            }
            set {
                this.vendorReturnIdField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiptType {
            get {
                return this.receiptTypeField;
            }
            set {
                this.receiptTypeField = value;
            }
        }
        
        /// <remarks/>
        public int LocationId {
            get {
                return this.locationIdField;
            }
            set {
                this.locationIdField = value;
            }
        }
        
        /// <remarks/>
        public string SalesLocationId {
            get {
                return this.salesLocationIdField;
            }
            set {
                this.salesLocationIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        public int VendorId {
            get {
                return this.vendorIdField;
            }
            set {
                this.vendorIdField = value;
            }
        }
        
        /// <remarks/>
        public string VendorType {
            get {
                return this.vendorTypeField;
            }
            set {
                this.vendorTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Product", IsNullable=false)]
        public Product[] Products {
            get {
                return this.productsField;
            }
            set {
                this.productsField = value;
            }
        }
        
        /// <remarks/>
        public float TotalLandedCost {
            get {
                return this.totalLandedCostField;
            }
            set {
                this.totalLandedCostField = value;
            }
        }
    }
}
