INSERT INTO transtype
        ( origbr ,
          transtypecode ,
          tccodedr ,
          tccodecr ,
          description ,
          balordue ,
          exportfilesuffix ,
          batchtype ,
          interfaceaccount ,
          interfacesecaccount ,
          branchsplit ,
          isdeposit ,
          interfacebalancing ,
          IncludeinGFT ,
          empeenochange ,
          referencemandatory ,
          referenceunique ,
          interfacesecbalancing ,
          branchsplitbalancing
        )
SELECT origbr ,
    'SCT' ,
    tccodedr ,
    tccodecr ,
    'StoreCard Transactions and Payments' ,
    balordue ,
    exportfilesuffix ,
    batchtype ,
    interfaceaccount ,
    interfacesecaccount ,
    branchsplit ,
    isdeposit ,
    interfacebalancing ,
    IncludeinGFT ,
    empeenochange ,
    referencemandatory ,
    referenceunique ,
    interfacesecbalancing ,
    branchsplitbalancing FROM transtype
	WHERE transtypecode = 'XFR'