CREATE TABLE Service.Contact
	(
	Id int NOT NULL IDENTITY (1, 1),
	RequestId int NOT NULL,
	Type int NOT NULL,
	Value varchar(255) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE Service.Contact ADD CONSTRAINT
	PK_Table_1 PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE Service.Contact SET (LOCK_ESCALATION = TABLE)
GO
