SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
GO
CREATE TABLE Service.Technician
	(
	UserId int NOT NULL,
	Enabled bit NOT NULL,
	Internal bit NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE Service.Technician ADD CONSTRAINT
	PK_Techician PRIMARY KEY CLUSTERED 
	(
	UserId
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO

ALTER TABLE Service.Technician SET (LOCK_ESCALATION = TABLE)
GO
