BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.bailcommnbas
	DROP CONSTRAINT pk_bailcommnbas
GO
ALTER TABLE dbo.bailcommnbas ADD CONSTRAINT
	pk_bailcommnbas PRIMARY KEY CLUSTERED 
	(
	empeeno,
	statuscode,
	collecttype,
	empeetype
	) WITH( PAD_INDEX = OFF, FILLFACTOR = 90, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.bailcommnbas SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
