CREATE TABLE Service.FoodLoss
	(
	Id int NOT NULL IDENTITY (1, 1),
	RequestId int NOT NULL,
	Item varchar(200) NOT NULL,
	Value money NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE SERVICE.FoodLoss ADD CONSTRAINT
	PK_FoodLoss PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE SERVICE.FoodLoss SET (LOCK_ESCALATION = TABLE)
GO

ALTER TABLE Service.FoodLoss 
ADD CONSTRAINT FK_FoodLoss_Request 
FOREIGN KEY ( RequestId ) REFERENCES Service.Request (Id) 
ON DELETE  CASCADE 
GO	 
