
 
IF  NOT EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('NonStockAccounts') AND TYPE IN (N'U'))
BEGIN

	CREATE TABLE [dbo].NonStockAccounts
	(
		[Id] INT PRIMARY KEY IDENTITY(1,1),
		[Acctno] VARCHAR(12) NOT NULL,
	)
END
GO
